// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the code between BEGIN USER CODE and END USER CODE
// Other code you write will be lost the next time you deploy the project.

/**
 * @param {MxObject[]} listOfObjects - List of objects you want to convert
 * @returns {string}
 */
function JS_ConvertData(listOfObjects) {
	// BEGIN USER CODE
	if (!listOfObjects) {
        throw new TypeError("Input parameter 'listOfObjects' is required");
    }
	return JSON.stringify(listOfObjects);
	// END USER CODE
}