// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {string} title
 * @param {string} message
 * @returns {Promise.<boolean>}
 */
export async function ShowMessage(title, message) {
	// BEGIN USER CODE

   if (!title) {
       throw new TypeError("Input parameter 'Title' is required");
   }

   if (navigator && navigator.product === "ReactNative") {
       const Alert = require("react-native").Alert;

       return new Promise(resolve => {
           Alert.alert(title, message, [{ text: "OK", onPress: () => resolve(true) }]);
       });
   }

   if (window && window.alert) {
       window.alert(`${title}\n\n${message || ""}`);
       return Promise.resolve(true);
   }

   return Promise.resolve(false);

	// END USER CODE
}
