// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package headersort.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the HeaderSort module
	public static headersort.proxies.Category dS_GetCategory(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("HeaderSort.DS_GetCategory").withParams(params).execute(context);
		return result == null ? null : headersort.proxies.Category.initialize(context, result);
	}
	public static java.util.List<headersort.proxies.Color> dSL_Color(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		java.util.List<IMendixObject> objs = Core.microflowCall("HeaderSort.DSL_Color").withParams(params).execute(context);
		java.util.List<headersort.proxies.Color> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(headersort.proxies.Color.initialize(context, obj));
		}
		return result;
	}
	public static java.util.List<headersort.proxies.Color> dSL_Colors(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		java.util.List<IMendixObject> objs = Core.microflowCall("HeaderSort.DSL_Colors").withParams(params).execute(context);
		java.util.List<headersort.proxies.Color> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(headersort.proxies.Color.initialize(context, obj));
		}
		return result;
	}
	public static headersort.proxies.Color dSO_Color(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("HeaderSort.DSO_Color").withParams(params).execute(context);
		return result == null ? null : headersort.proxies.Color.initialize(context, result);
	}
	public static void iVK_Commit(IContext context, headersort.proxies.Color _employee)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Employee", _employee == null ? null : _employee.getMendixObject());
		Core.microflowCall("HeaderSort.IVK_Commit").withParams(params).execute(context);
	}
	public static void iVK_CreateSampleData(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("HeaderSort.IVK_CreateSampleData").withParams(params).execute(context);
	}
	public static boolean iVK_CustomWidgetOnclick(IContext context, headersort.proxies.Color _employee)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Employee", _employee == null ? null : _employee.getMendixObject());
		return (java.lang.Boolean) Core.microflowCall("HeaderSort.IVK_CustomWidgetOnclick").withParams(params).execute(context);
	}
	public static void iVK_RefreshInClient(IContext context, headersort.proxies.Color _employee)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Employee", _employee == null ? null : _employee.getMendixObject());
		Core.microflowCall("HeaderSort.IVK_RefreshInClient").withParams(params).execute(context);
	}
	public static void iVK_ShowValidations(IContext context, headersort.proxies.Color _employee)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Employee", _employee == null ? null : _employee.getMendixObject());
		Core.microflowCall("HeaderSort.IVK_ShowValidations").withParams(params).execute(context);
	}
	public static void oCh_Color(IContext context, headersort.proxies.Color _employee)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Employee", _employee == null ? null : _employee.getMendixObject());
		Core.microflowCall("HeaderSort.OCh_Color").withParams(params).execute(context);
	}
}