// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package pagination.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the Pagination module
	public static void aCT_AddMore(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("Pagination.ACT_AddMore").withParams(params).execute(context);
	}
	public static boolean aCT_CreateData(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		return (java.lang.Boolean) Core.microflowCall("Pagination.ACT_CreateData").withParams(params).execute(context);
	}
	public static boolean aCT_CreateData_General(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		return (java.lang.Boolean) Core.microflowCall("Pagination.ACT_CreateData_General").withParams(params).execute(context);
	}
	public static boolean aCT_CreateData_With_P(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		return (java.lang.Boolean) Core.microflowCall("Pagination.ACT_CreateData_With_P").withParams(params).execute(context);
	}
	public static void aCT_Delete_ALL(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("Pagination.ACT_Delete_ALL").withParams(params).execute(context);
	}
	public static void aCT_Delete_First(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("Pagination.ACT_Delete_First").withParams(params).execute(context);
	}
	public static void aCT_Delete_Last(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("Pagination.ACT_Delete_Last").withParams(params).execute(context);
	}
	public static void aCT_DeleteALL(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("Pagination.ACT_DeleteALL").withParams(params).execute(context);
	}
	public static void aCT_DeleteColor(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("Pagination.ACT_DeleteColor").withParams(params).execute(context);
	}
	public static void aCT_DeleteColorSelected(IContext context, pagination.proxies.Color _color)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Color", _color == null ? null : _color.getMendixObject());
		Core.microflowCall("Pagination.ACT_DeleteColorSelected").withParams(params).execute(context);
	}
	public static void color_New(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("Pagination.Color_New").withParams(params).execute(context);
	}
	public static java.util.List<pagination.proxies.Color> dSL_Color(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		java.util.List<IMendixObject> objs = Core.microflowCall("Pagination.DSL_Color").withParams(params).execute(context);
		java.util.List<pagination.proxies.Color> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(pagination.proxies.Color.initialize(context, obj));
		}
		return result;
	}
	public static java.util.List<pagination.proxies.Color> dSL_Colors(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		java.util.List<IMendixObject> objs = Core.microflowCall("Pagination.DSL_Colors").withParams(params).execute(context);
		java.util.List<pagination.proxies.Color> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(pagination.proxies.Color.initialize(context, obj));
		}
		return result;
	}
	public static pagination.proxies.Color dSO_Color(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("Pagination.DSO_Color").withParams(params).execute(context);
		return result == null ? null : pagination.proxies.Color.initialize(context, result);
	}
	public static pagination.proxies.Color dSS_Color(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("Pagination.DSS_Color").withParams(params).execute(context);
		return result == null ? null : pagination.proxies.Color.initialize(context, result);
	}
	public static void iVK_Commit(IContext context, pagination.proxies.Color _employee)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Employee", _employee == null ? null : _employee.getMendixObject());
		Core.microflowCall("Pagination.IVK_Commit").withParams(params).execute(context);
	}
	public static boolean iVK_CustomWidgetOnclick(IContext context, pagination.proxies.Color _employee)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Employee", _employee == null ? null : _employee.getMendixObject());
		return (java.lang.Boolean) Core.microflowCall("Pagination.IVK_CustomWidgetOnclick").withParams(params).execute(context);
	}
	public static void iVK_RefreshInClient(IContext context, pagination.proxies.Color _employee)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Employee", _employee == null ? null : _employee.getMendixObject());
		Core.microflowCall("Pagination.IVK_RefreshInClient").withParams(params).execute(context);
	}
	public static void iVK_ShowValidations(IContext context, pagination.proxies.Color _employee)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Employee", _employee == null ? null : _employee.getMendixObject());
		Core.microflowCall("Pagination.IVK_ShowValidations").withParams(params).execute(context);
	}
	public static void oCh_Color(IContext context, pagination.proxies.Color _employee)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Employee", _employee == null ? null : _employee.getMendixObject());
		Core.microflowCall("Pagination.OCh_Color").withParams(params).execute(context);
	}
}