// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package bootstrapbadge.proxies;

public class Badge implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject badgeMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "BootstrapBadge.Badge";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		DataString("DataString"),
		BootstrapStyle("BootstrapStyle"),
		LabelAttribute("LabelAttribute"),
		DataLong("DataLong"),
		DataInteger("DataInteger"),
		DataDecimal("DataDecimal"),
		DefaultValue("DefaultValue");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Badge(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Badge(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject badgeMendixObject)
	{
		if (badgeMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!badgeMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.badgeMendixObject = badgeMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static bootstrapbadge.proxies.Badge initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new bootstrapbadge.proxies.Badge(context, mendixObject);
	}

	public static bootstrapbadge.proxies.Badge load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return bootstrapbadge.proxies.Badge.initialize(context, mendixObject);
	}

	public static java.util.List<bootstrapbadge.proxies.Badge> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> bootstrapbadge.proxies.Badge.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of DataString
	 */
	public final java.lang.String getDataString()
	{
		return getDataString(getContext());
	}

	/**
	 * @param context
	 * @return value of DataString
	 */
	public final java.lang.String getDataString(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DataString.toString());
	}

	/**
	 * Set value of DataString
	 * @param datastring
	 */
	public final void setDataString(java.lang.String datastring)
	{
		setDataString(getContext(), datastring);
	}

	/**
	 * Set value of DataString
	 * @param context
	 * @param datastring
	 */
	public final void setDataString(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String datastring)
	{
		getMendixObject().setValue(context, MemberNames.DataString.toString(), datastring);
	}

	/**
	 * Get value of BootstrapStyle
	 * @param bootstrapstyle
	 */
	public final bootstrapbadge.proxies.bootstrapStyle getBootstrapStyle()
	{
		return getBootstrapStyle(getContext());
	}

	/**
	 * @param context
	 * @return value of BootstrapStyle
	 */
	public final bootstrapbadge.proxies.bootstrapStyle getBootstrapStyle(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.BootstrapStyle.toString());
		if (obj == null) {
			return null;
		}
		return bootstrapbadge.proxies.bootstrapStyle.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of BootstrapStyle
	 * @param bootstrapstyle
	 */
	public final void setBootstrapStyle(bootstrapbadge.proxies.bootstrapStyle bootstrapstyle)
	{
		setBootstrapStyle(getContext(), bootstrapstyle);
	}

	/**
	 * Set value of BootstrapStyle
	 * @param context
	 * @param bootstrapstyle
	 */
	public final void setBootstrapStyle(com.mendix.systemwideinterfaces.core.IContext context, bootstrapbadge.proxies.bootstrapStyle bootstrapstyle)
	{
		if (bootstrapstyle != null) {
			getMendixObject().setValue(context, MemberNames.BootstrapStyle.toString(), bootstrapstyle.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.BootstrapStyle.toString(), null);
		}
	}

	/**
	 * @return value of LabelAttribute
	 */
	public final java.lang.String getLabelAttribute()
	{
		return getLabelAttribute(getContext());
	}

	/**
	 * @param context
	 * @return value of LabelAttribute
	 */
	public final java.lang.String getLabelAttribute(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.LabelAttribute.toString());
	}

	/**
	 * Set value of LabelAttribute
	 * @param labelattribute
	 */
	public final void setLabelAttribute(java.lang.String labelattribute)
	{
		setLabelAttribute(getContext(), labelattribute);
	}

	/**
	 * Set value of LabelAttribute
	 * @param context
	 * @param labelattribute
	 */
	public final void setLabelAttribute(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String labelattribute)
	{
		getMendixObject().setValue(context, MemberNames.LabelAttribute.toString(), labelattribute);
	}

	/**
	 * @return value of DataLong
	 */
	public final java.lang.Long getDataLong()
	{
		return getDataLong(getContext());
	}

	/**
	 * @param context
	 * @return value of DataLong
	 */
	public final java.lang.Long getDataLong(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.DataLong.toString());
	}

	/**
	 * Set value of DataLong
	 * @param datalong
	 */
	public final void setDataLong(java.lang.Long datalong)
	{
		setDataLong(getContext(), datalong);
	}

	/**
	 * Set value of DataLong
	 * @param context
	 * @param datalong
	 */
	public final void setDataLong(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long datalong)
	{
		getMendixObject().setValue(context, MemberNames.DataLong.toString(), datalong);
	}

	/**
	 * @return value of DataInteger
	 */
	public final java.lang.Integer getDataInteger()
	{
		return getDataInteger(getContext());
	}

	/**
	 * @param context
	 * @return value of DataInteger
	 */
	public final java.lang.Integer getDataInteger(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.DataInteger.toString());
	}

	/**
	 * Set value of DataInteger
	 * @param datainteger
	 */
	public final void setDataInteger(java.lang.Integer datainteger)
	{
		setDataInteger(getContext(), datainteger);
	}

	/**
	 * Set value of DataInteger
	 * @param context
	 * @param datainteger
	 */
	public final void setDataInteger(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer datainteger)
	{
		getMendixObject().setValue(context, MemberNames.DataInteger.toString(), datainteger);
	}

	/**
	 * @return value of DataDecimal
	 */
	public final java.math.BigDecimal getDataDecimal()
	{
		return getDataDecimal(getContext());
	}

	/**
	 * @param context
	 * @return value of DataDecimal
	 */
	public final java.math.BigDecimal getDataDecimal(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.DataDecimal.toString());
	}

	/**
	 * Set value of DataDecimal
	 * @param datadecimal
	 */
	public final void setDataDecimal(java.math.BigDecimal datadecimal)
	{
		setDataDecimal(getContext(), datadecimal);
	}

	/**
	 * Set value of DataDecimal
	 * @param context
	 * @param datadecimal
	 */
	public final void setDataDecimal(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal datadecimal)
	{
		getMendixObject().setValue(context, MemberNames.DataDecimal.toString(), datadecimal);
	}

	/**
	 * @return value of DefaultValue
	 */
	public final java.lang.String getDefaultValue()
	{
		return getDefaultValue(getContext());
	}

	/**
	 * @param context
	 * @return value of DefaultValue
	 */
	public final java.lang.String getDefaultValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DefaultValue.toString());
	}

	/**
	 * Set value of DefaultValue
	 * @param defaultvalue
	 */
	public final void setDefaultValue(java.lang.String defaultvalue)
	{
		setDefaultValue(getContext(), defaultvalue);
	}

	/**
	 * Set value of DefaultValue
	 * @param context
	 * @param defaultvalue
	 */
	public final void setDefaultValue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String defaultvalue)
	{
		getMendixObject().setValue(context, MemberNames.DefaultValue.toString(), defaultvalue);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return badgeMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final bootstrapbadge.proxies.Badge that = (bootstrapbadge.proxies.Badge) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
