// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package bootstrapbadge.proxies;

public enum bootstrapStyle
{
	primary("7c5689bd-9e01-4255-a126-140d5e59b429"),
	success("e308688e-75f7-4ba2-a78e-e8d65a8e3ca1"),
	info("5b6ef0bf-f438-46c5-bff0-730fc2d7bdfa"),
	warning("d89cd354-c54c-455a-81b4-ee216636a10c"),
	danger("efeedb1a-6d41-4281-ad22-20b88e30de89");

	private final java.lang.String i18nCaptionKey;
	
	private bootstrapStyle(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
