// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package charts_howto.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the Charts_HowTo module
	public static anychartmodule.proxies.Chart dSS_AnyChart_LineData(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("Charts_HowTo.DSS_AnyChart_LineData").withParams(params).execute(context);
		return result == null ? null : anychartmodule.proxies.Chart.initialize(context, result);
	}
	public static charts_howto.proxies.Values iVK_NewValues(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("Charts_HowTo.IVK_NewValues").withParams(params).execute(context);
		return result == null ? null : charts_howto.proxies.Values.initialize(context, result);
	}
	public static system.proxies.HttpResponse pRS_GetGetSeriesData(IContext context, system.proxies.HttpRequest _httpRequest, java.lang.String _name)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("httpRequest", _httpRequest == null ? null : _httpRequest.getMendixObject());
		params.put("Name", _name);
		IMendixObject result = (IMendixObject)Core.microflowCall("Charts_HowTo.PRS_GetGetSeriesData").withParams(params).execute(context);
		return result == null ? null : system.proxies.HttpResponse.initialize(context, result);
	}
	public static anychartmodule.proxies.Root sUB_CreateDataStructure(IContext context, java.util.List<anychartmodule.proxies.DataPoint> _dataPointList)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		java.util.ArrayList<IMendixObject> listparam_dataPointList = null;
		if (_dataPointList != null)
		{
			listparam_dataPointList = new java.util.ArrayList<>();
			for (anychartmodule.proxies.DataPoint obj : _dataPointList)
				listparam_dataPointList.add(obj.getMendixObject());
		}
		params.put("DataPointList", listparam_dataPointList);

		IMendixObject result = (IMendixObject)Core.microflowCall("Charts_HowTo.SUB_CreateDataStructure").withParams(params).execute(context);
		return result == null ? null : anychartmodule.proxies.Root.initialize(context, result);
	}
}