// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package employeedb.proxies.constants;

import com.mendix.core.Core;

public final class Constants
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Constants() {}

	// These are the constants for the EmployeeDB module

	public static java.lang.Long getStartID()
	{
		return (java.lang.Long)Core.getConfiguration().getConstantValue("EmployeeDB.StartID");
	}
}