// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package pagination.proxies;

public class TestItem
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject testItemMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Pagination.TestItem";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		AutoNumber("AutoNumber");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public TestItem(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Pagination.TestItem"));
	}

	protected TestItem(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject testItemMendixObject)
	{
		if (testItemMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Pagination.TestItem", testItemMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Pagination.TestItem");

		this.testItemMendixObject = testItemMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'TestItem.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static pagination.proxies.TestItem initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return pagination.proxies.TestItem.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static pagination.proxies.TestItem initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new pagination.proxies.TestItem(context, mendixObject);
	}

	public static pagination.proxies.TestItem load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return pagination.proxies.TestItem.initialize(context, mendixObject);
	}

	public static java.util.List<pagination.proxies.TestItem> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<pagination.proxies.TestItem> result = new java.util.ArrayList<pagination.proxies.TestItem>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//Pagination.TestItem" + xpathConstraint))
			result.add(pagination.proxies.TestItem.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of AutoNumber
	 */
	public final java.lang.Long getAutoNumber()
	{
		return getAutoNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of AutoNumber
	 */
	public final java.lang.Long getAutoNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.AutoNumber.toString());
	}

	/**
	 * Set value of AutoNumber
	 * @param autonumber
	 */
	public final void setAutoNumber(java.lang.Long autonumber)
	{
		setAutoNumber(getContext(), autonumber);
	}

	/**
	 * Set value of AutoNumber
	 * @param context
	 * @param autonumber
	 */
	public final void setAutoNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long autonumber)
	{
		getMendixObject().setValue(context, MemberNames.AutoNumber.toString(), autonumber);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return testItemMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final pagination.proxies.TestItem that = (pagination.proxies.TestItem) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Pagination.TestItem";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
