// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package feedbackmodule.proxies;

public class Feedback implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject feedbackMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "FeedbackModule.Feedback";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Subject("Subject"),
		Description("Description"),
		SubmitterUUID("SubmitterUUID"),
		SubmitterEmail("SubmitterEmail"),
		SubmitterDisplayName("SubmitterDisplayName"),
		ImageB64("ImageB64"),
		ActiveUserRoles("ActiveUserRoles"),
		PageName("PageName"),
		Browser("Browser"),
		EnvironmentURL("EnvironmentURL"),
		ScreenshotName("ScreenshotName"),
		AppID("AppID"),
		Priority("Priority"),
		ScreenWidth("ScreenWidth"),
		ScreenHeight("ScreenHeight"),
		_showEmail("_showEmail");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Feedback(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Feedback(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject feedbackMendixObject)
	{
		if (feedbackMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!feedbackMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.feedbackMendixObject = feedbackMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static feedbackmodule.proxies.Feedback initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new feedbackmodule.proxies.Feedback(context, mendixObject);
	}

	public static feedbackmodule.proxies.Feedback load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return feedbackmodule.proxies.Feedback.initialize(context, mendixObject);
	}

	/**
	 * @return value of Subject
	 */
	public final java.lang.String getSubject()
	{
		return getSubject(getContext());
	}

	/**
	 * @param context
	 * @return value of Subject
	 */
	public final java.lang.String getSubject(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Subject.toString());
	}

	/**
	 * Set value of Subject
	 * @param subject
	 */
	public final void setSubject(java.lang.String subject)
	{
		setSubject(getContext(), subject);
	}

	/**
	 * Set value of Subject
	 * @param context
	 * @param subject
	 */
	public final void setSubject(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String subject)
	{
		getMendixObject().setValue(context, MemberNames.Subject.toString(), subject);
	}

	/**
	 * @return value of Description
	 */
	public final java.lang.String getDescription()
	{
		return getDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of Description
	 */
	public final java.lang.String getDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Description.toString());
	}

	/**
	 * Set value of Description
	 * @param description
	 */
	public final void setDescription(java.lang.String description)
	{
		setDescription(getContext(), description);
	}

	/**
	 * Set value of Description
	 * @param context
	 * @param description
	 */
	public final void setDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String description)
	{
		getMendixObject().setValue(context, MemberNames.Description.toString(), description);
	}

	/**
	 * @return value of SubmitterUUID
	 */
	public final java.lang.String getSubmitterUUID()
	{
		return getSubmitterUUID(getContext());
	}

	/**
	 * @param context
	 * @return value of SubmitterUUID
	 */
	public final java.lang.String getSubmitterUUID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SubmitterUUID.toString());
	}

	/**
	 * Set value of SubmitterUUID
	 * @param submitteruuid
	 */
	public final void setSubmitterUUID(java.lang.String submitteruuid)
	{
		setSubmitterUUID(getContext(), submitteruuid);
	}

	/**
	 * Set value of SubmitterUUID
	 * @param context
	 * @param submitteruuid
	 */
	public final void setSubmitterUUID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String submitteruuid)
	{
		getMendixObject().setValue(context, MemberNames.SubmitterUUID.toString(), submitteruuid);
	}

	/**
	 * @return value of SubmitterEmail
	 */
	public final java.lang.String getSubmitterEmail()
	{
		return getSubmitterEmail(getContext());
	}

	/**
	 * @param context
	 * @return value of SubmitterEmail
	 */
	public final java.lang.String getSubmitterEmail(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SubmitterEmail.toString());
	}

	/**
	 * Set value of SubmitterEmail
	 * @param submitteremail
	 */
	public final void setSubmitterEmail(java.lang.String submitteremail)
	{
		setSubmitterEmail(getContext(), submitteremail);
	}

	/**
	 * Set value of SubmitterEmail
	 * @param context
	 * @param submitteremail
	 */
	public final void setSubmitterEmail(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String submitteremail)
	{
		getMendixObject().setValue(context, MemberNames.SubmitterEmail.toString(), submitteremail);
	}

	/**
	 * @return value of SubmitterDisplayName
	 */
	public final java.lang.String getSubmitterDisplayName()
	{
		return getSubmitterDisplayName(getContext());
	}

	/**
	 * @param context
	 * @return value of SubmitterDisplayName
	 */
	public final java.lang.String getSubmitterDisplayName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SubmitterDisplayName.toString());
	}

	/**
	 * Set value of SubmitterDisplayName
	 * @param submitterdisplayname
	 */
	public final void setSubmitterDisplayName(java.lang.String submitterdisplayname)
	{
		setSubmitterDisplayName(getContext(), submitterdisplayname);
	}

	/**
	 * Set value of SubmitterDisplayName
	 * @param context
	 * @param submitterdisplayname
	 */
	public final void setSubmitterDisplayName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String submitterdisplayname)
	{
		getMendixObject().setValue(context, MemberNames.SubmitterDisplayName.toString(), submitterdisplayname);
	}

	/**
	 * @return value of ImageB64
	 */
	public final java.lang.String getImageB64()
	{
		return getImageB64(getContext());
	}

	/**
	 * @param context
	 * @return value of ImageB64
	 */
	public final java.lang.String getImageB64(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ImageB64.toString());
	}

	/**
	 * Set value of ImageB64
	 * @param imageb64
	 */
	public final void setImageB64(java.lang.String imageb64)
	{
		setImageB64(getContext(), imageb64);
	}

	/**
	 * Set value of ImageB64
	 * @param context
	 * @param imageb64
	 */
	public final void setImageB64(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String imageb64)
	{
		getMendixObject().setValue(context, MemberNames.ImageB64.toString(), imageb64);
	}

	/**
	 * @return value of ActiveUserRoles
	 */
	public final java.lang.String getActiveUserRoles()
	{
		return getActiveUserRoles(getContext());
	}

	/**
	 * @param context
	 * @return value of ActiveUserRoles
	 */
	public final java.lang.String getActiveUserRoles(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ActiveUserRoles.toString());
	}

	/**
	 * Set value of ActiveUserRoles
	 * @param activeuserroles
	 */
	public final void setActiveUserRoles(java.lang.String activeuserroles)
	{
		setActiveUserRoles(getContext(), activeuserroles);
	}

	/**
	 * Set value of ActiveUserRoles
	 * @param context
	 * @param activeuserroles
	 */
	public final void setActiveUserRoles(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String activeuserroles)
	{
		getMendixObject().setValue(context, MemberNames.ActiveUserRoles.toString(), activeuserroles);
	}

	/**
	 * @return value of PageName
	 */
	public final java.lang.String getPageName()
	{
		return getPageName(getContext());
	}

	/**
	 * @param context
	 * @return value of PageName
	 */
	public final java.lang.String getPageName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.PageName.toString());
	}

	/**
	 * Set value of PageName
	 * @param pagename
	 */
	public final void setPageName(java.lang.String pagename)
	{
		setPageName(getContext(), pagename);
	}

	/**
	 * Set value of PageName
	 * @param context
	 * @param pagename
	 */
	public final void setPageName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String pagename)
	{
		getMendixObject().setValue(context, MemberNames.PageName.toString(), pagename);
	}

	/**
	 * @return value of Browser
	 */
	public final java.lang.String getBrowser()
	{
		return getBrowser(getContext());
	}

	/**
	 * @param context
	 * @return value of Browser
	 */
	public final java.lang.String getBrowser(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Browser.toString());
	}

	/**
	 * Set value of Browser
	 * @param browser
	 */
	public final void setBrowser(java.lang.String browser)
	{
		setBrowser(getContext(), browser);
	}

	/**
	 * Set value of Browser
	 * @param context
	 * @param browser
	 */
	public final void setBrowser(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String browser)
	{
		getMendixObject().setValue(context, MemberNames.Browser.toString(), browser);
	}

	/**
	 * @return value of EnvironmentURL
	 */
	public final java.lang.String getEnvironmentURL()
	{
		return getEnvironmentURL(getContext());
	}

	/**
	 * @param context
	 * @return value of EnvironmentURL
	 */
	public final java.lang.String getEnvironmentURL(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EnvironmentURL.toString());
	}

	/**
	 * Set value of EnvironmentURL
	 * @param environmenturl
	 */
	public final void setEnvironmentURL(java.lang.String environmenturl)
	{
		setEnvironmentURL(getContext(), environmenturl);
	}

	/**
	 * Set value of EnvironmentURL
	 * @param context
	 * @param environmenturl
	 */
	public final void setEnvironmentURL(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String environmenturl)
	{
		getMendixObject().setValue(context, MemberNames.EnvironmentURL.toString(), environmenturl);
	}

	/**
	 * @return value of ScreenshotName
	 */
	public final java.lang.String getScreenshotName()
	{
		return getScreenshotName(getContext());
	}

	/**
	 * @param context
	 * @return value of ScreenshotName
	 */
	public final java.lang.String getScreenshotName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ScreenshotName.toString());
	}

	/**
	 * Set value of ScreenshotName
	 * @param screenshotname
	 */
	public final void setScreenshotName(java.lang.String screenshotname)
	{
		setScreenshotName(getContext(), screenshotname);
	}

	/**
	 * Set value of ScreenshotName
	 * @param context
	 * @param screenshotname
	 */
	public final void setScreenshotName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String screenshotname)
	{
		getMendixObject().setValue(context, MemberNames.ScreenshotName.toString(), screenshotname);
	}

	/**
	 * @return value of AppID
	 */
	public final java.lang.String getAppID()
	{
		return getAppID(getContext());
	}

	/**
	 * @param context
	 * @return value of AppID
	 */
	public final java.lang.String getAppID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.AppID.toString());
	}

	/**
	 * Set value of AppID
	 * @param appid
	 */
	public final void setAppID(java.lang.String appid)
	{
		setAppID(getContext(), appid);
	}

	/**
	 * Set value of AppID
	 * @param context
	 * @param appid
	 */
	public final void setAppID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String appid)
	{
		getMendixObject().setValue(context, MemberNames.AppID.toString(), appid);
	}

	/**
	 * @return value of Priority
	 */
	public final java.lang.String getPriority()
	{
		return getPriority(getContext());
	}

	/**
	 * @param context
	 * @return value of Priority
	 */
	public final java.lang.String getPriority(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Priority.toString());
	}

	/**
	 * Set value of Priority
	 * @param priority
	 */
	public final void setPriority(java.lang.String priority)
	{
		setPriority(getContext(), priority);
	}

	/**
	 * Set value of Priority
	 * @param context
	 * @param priority
	 */
	public final void setPriority(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String priority)
	{
		getMendixObject().setValue(context, MemberNames.Priority.toString(), priority);
	}

	/**
	 * @return value of ScreenWidth
	 */
	public final java.lang.Integer getScreenWidth()
	{
		return getScreenWidth(getContext());
	}

	/**
	 * @param context
	 * @return value of ScreenWidth
	 */
	public final java.lang.Integer getScreenWidth(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.ScreenWidth.toString());
	}

	/**
	 * Set value of ScreenWidth
	 * @param screenwidth
	 */
	public final void setScreenWidth(java.lang.Integer screenwidth)
	{
		setScreenWidth(getContext(), screenwidth);
	}

	/**
	 * Set value of ScreenWidth
	 * @param context
	 * @param screenwidth
	 */
	public final void setScreenWidth(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer screenwidth)
	{
		getMendixObject().setValue(context, MemberNames.ScreenWidth.toString(), screenwidth);
	}

	/**
	 * @return value of ScreenHeight
	 */
	public final java.lang.Integer getScreenHeight()
	{
		return getScreenHeight(getContext());
	}

	/**
	 * @param context
	 * @return value of ScreenHeight
	 */
	public final java.lang.Integer getScreenHeight(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.ScreenHeight.toString());
	}

	/**
	 * Set value of ScreenHeight
	 * @param screenheight
	 */
	public final void setScreenHeight(java.lang.Integer screenheight)
	{
		setScreenHeight(getContext(), screenheight);
	}

	/**
	 * Set value of ScreenHeight
	 * @param context
	 * @param screenheight
	 */
	public final void setScreenHeight(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer screenheight)
	{
		getMendixObject().setValue(context, MemberNames.ScreenHeight.toString(), screenheight);
	}

	/**
	 * @return value of _showEmail
	 */
	public final java.lang.Boolean get_showEmail()
	{
		return get_showEmail(getContext());
	}

	/**
	 * @param context
	 * @return value of _showEmail
	 */
	public final java.lang.Boolean get_showEmail(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames._showEmail.toString());
	}

	/**
	 * Set value of _showEmail
	 * @param _showemail
	 */
	public final void set_showEmail(java.lang.Boolean _showemail)
	{
		set_showEmail(getContext(), _showemail);
	}

	/**
	 * Set value of _showEmail
	 * @param context
	 * @param _showemail
	 */
	public final void set_showEmail(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean _showemail)
	{
		getMendixObject().setValue(context, MemberNames._showEmail.toString(), _showemail);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return feedbackMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final feedbackmodule.proxies.Feedback that = (feedbackmodule.proxies.Feedback) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
