// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package feedbackmodule.proxies;

public enum TranslationLanguages
{
	Dutch("f28efc63-907e-45c5-8517-9db8c776eac1"),
	English("a799a8ec-08af-4db8-b868-6b0fe6eb1b7c"),
	French("0e33daec-2857-405a-a2e2-6ea49b417026"),
	German("25839ede-ce84-429f-b5f8-10c19562b9a5"),
	Hindi("e5192772-7081-49d4-bbb0-2a4e357afab9"),
	Portuguese("f2dc33aa-48a6-4d10-a016-cf5d3a9d99f6"),
	Spanish("410b3c7c-1fb8-4e6f-97a3-a151fdafdb54"),
	Turkish("aef6435e-dafa-4008-9ff4-09d2239df6a2");

	private final java.lang.String i18nCaptionKey;
	
	private TranslationLanguages(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
