// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package feedbackmodule.proxies;

public enum TranslationLanguages
{
	Dutch("34fa51f6-9af8-43dd-b11c-7601ac85d892"),
	English("4fad1bdf-0acc-45aa-a191-e26b2346cb8a"),
	French("c73260b7-3570-4721-a040-ec8c6ae920bb"),
	German("bcc0f32f-43b2-4337-82e9-f194019f8416"),
	Hindi("4cbb74de-cf04-4e5d-8f66-cb0ce2339ab2"),
	Portuguese("b8947c2f-1a69-4dbf-b196-e507c8a920dd"),
	Spanish("0055bf4a-40f9-4946-8dd2-f06c7dbe86d7"),
	Turkish("28a59f8d-2e14-4331-8902-b30a28419213");

	private final java.lang.String i18nCaptionKey;
	
	private TranslationLanguages(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
