// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nanoflowcommons.proxies;

public enum GeocodingProvider
{
	Google("999c0f19-2622-4e53-baf7-8c38d1fcb1f4"),
	Geocodio("8af55307-d741-4d39-9b27-f337a1ec16cf"),
	LocationIQ("29562a46-73c7-45d7-8ccb-1290ed26e85e"),
	MapQuest("eebba00d-836d-4d2d-a13b-d5a8fdc1a336");

	private final java.lang.String i18nCaptionKey;
	
	private GeocodingProvider(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
