// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package native_.proxies;

public class Demo_BottomSheet
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject demo_BottomSheetMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Native_.Demo_BottomSheet";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		deleted("deleted");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Demo_BottomSheet(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Native_.Demo_BottomSheet"));
	}

	protected Demo_BottomSheet(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject demo_BottomSheetMendixObject)
	{
		if (demo_BottomSheetMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Native_.Demo_BottomSheet", demo_BottomSheetMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Native_.Demo_BottomSheet");

		this.demo_BottomSheetMendixObject = demo_BottomSheetMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Demo_BottomSheet.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static native_.proxies.Demo_BottomSheet initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return native_.proxies.Demo_BottomSheet.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static native_.proxies.Demo_BottomSheet initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new native_.proxies.Demo_BottomSheet(context, mendixObject);
	}

	public static native_.proxies.Demo_BottomSheet load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return native_.proxies.Demo_BottomSheet.initialize(context, mendixObject);
	}

	public static java.util.List<native_.proxies.Demo_BottomSheet> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<native_.proxies.Demo_BottomSheet> result = new java.util.ArrayList<native_.proxies.Demo_BottomSheet>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//Native_.Demo_BottomSheet" + xpathConstraint))
			result.add(native_.proxies.Demo_BottomSheet.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of deleted
	 */
	public final java.lang.Boolean getdeleted()
	{
		return getdeleted(getContext());
	}

	/**
	 * @param context
	 * @return value of deleted
	 */
	public final java.lang.Boolean getdeleted(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.deleted.toString());
	}

	/**
	 * Set value of deleted
	 * @param deleted
	 */
	public final void setdeleted(java.lang.Boolean deleted)
	{
		setdeleted(getContext(), deleted);
	}

	/**
	 * Set value of deleted
	 * @param context
	 * @param deleted
	 */
	public final void setdeleted(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean deleted)
	{
		getMendixObject().setValue(context, MemberNames.deleted.toString(), deleted);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return demo_BottomSheetMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final native_.proxies.Demo_BottomSheet that = (native_.proxies.Demo_BottomSheet) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Native_.Demo_BottomSheet";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
