// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the MyFirstModule module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder copy_MountainBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.Copy_Mountain");
		return builder;
	}

	public static myfirstmodule.proxies.Img copy_Mountain(IContext context)
	{
		Object result = copy_MountainBuilder().execute(context);
		return result == null ? null : myfirstmodule.proxies.Img.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder set_Fresh_ImgBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.Set_Fresh_Img");
		return builder;
	}

	public static myfirstmodule.proxies.FileHolder set_Fresh_Img(IContext context)
	{
		Object result = set_Fresh_ImgBuilder().execute(context);
		return result == null ? null : myfirstmodule.proxies.FileHolder.initialize(context, (IMendixObject) result);
	}
}
