// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the MyFirstModule module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder copy_MountainBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.Copy_Mountain");
		return builder;
	}

	public static myfirstmodule.proxies.Img copy_Mountain(IContext context)
	{
		Object result = copy_MountainBuilder().execute(context);
		return result == null ? null : myfirstmodule.proxies.Img.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder myFirstLogicBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.MyFirstLogic");
		return builder;
	}

	public static void myFirstLogic(IContext context)
	{
		myFirstLogicBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder set_Fresh_ImgBuilder(
		myfirstmodule.proxies.FileHolder _fileHolder
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.Set_Fresh_Img");
		builder = builder.withParam("FileHolder", _fileHolder);
		return builder;
	}

	public static myfirstmodule.proxies.Img set_Fresh_Img(
		IContext context,
		myfirstmodule.proxies.FileHolder _fileHolder
	)
	{
		Object result = set_Fresh_ImgBuilder(
				_fileHolder
			)
			.execute(context);
		return result == null ? null : myfirstmodule.proxies.Img.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder show_HomeBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.Show_Home");
		return builder;
	}

	public static void show_Home(IContext context)
	{
		show_HomeBuilder().execute(context);
	}
}
