// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the MyFirstModule module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder mF_Change_ParameterBuilder(
		myfirstmodule.proxies.Person _person,
		myfirstmodule.proxies.Filter _filter
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.MF_Change_Parameter");
		builder = builder.withParam("Person", _person);
		builder = builder.withParam("Filter", _filter);
		return builder;
	}

	public static void mF_Change_Parameter(
		IContext context,
		myfirstmodule.proxies.Person _person,
		myfirstmodule.proxies.Filter _filter
	)
	{
		mF_Change_ParameterBuilder(
				_person,
				_filter
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder startupMF_CreatePersonBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.StartupMF_CreatePerson");
		return builder;
	}

	public static boolean startupMF_CreatePerson(IContext context)
	{
		Object result = startupMF_CreatePersonBuilder().execute(context);
		return (boolean) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder startupMF_MainBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.StartupMF_Main");
		return builder;
	}

	public static boolean startupMF_Main(IContext context)
	{
		Object result = startupMF_MainBuilder().execute(context);
		return (boolean) result;
	}
}
