// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package atlas_ui_data.proxies;

public class Chat
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject chatMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Atlas_UI_Data.Chat";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Chat_Message("Atlas_UI_Data.Chat_Message");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Chat(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Atlas_UI_Data.Chat"));
	}

	protected Chat(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject chatMendixObject)
	{
		if (chatMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Atlas_UI_Data.Chat", chatMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Atlas_UI_Data.Chat");

		this.chatMendixObject = chatMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Chat.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static atlas_ui_data.proxies.Chat initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return atlas_ui_data.proxies.Chat.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static atlas_ui_data.proxies.Chat initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new atlas_ui_data.proxies.Chat(context, mendixObject);
	}

	public static atlas_ui_data.proxies.Chat load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return atlas_ui_data.proxies.Chat.initialize(context, mendixObject);
	}

	public static java.util.List<atlas_ui_data.proxies.Chat> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<atlas_ui_data.proxies.Chat> result = new java.util.ArrayList<atlas_ui_data.proxies.Chat>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//Atlas_UI_Data.Chat" + xpathConstraint))
			result.add(atlas_ui_data.proxies.Chat.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Chat_Message
	 */
	public final atlas_ui_data.proxies.Message getChat_Message() throws com.mendix.core.CoreException
	{
		return getChat_Message(getContext());
	}

	/**
	 * @param context
	 * @return value of Chat_Message
	 */
	public final atlas_ui_data.proxies.Message getChat_Message(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		atlas_ui_data.proxies.Message result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Chat_Message.toString());
		if (identifier != null)
			result = atlas_ui_data.proxies.Message.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Chat_Message
	 * @param chat_message
	 */
	public final void setChat_Message(atlas_ui_data.proxies.Message chat_message)
	{
		setChat_Message(getContext(), chat_message);
	}

	/**
	 * Set value of Chat_Message
	 * @param context
	 * @param chat_message
	 */
	public final void setChat_Message(com.mendix.systemwideinterfaces.core.IContext context, atlas_ui_data.proxies.Message chat_message)
	{
		if (chat_message == null)
			getMendixObject().setValue(context, MemberNames.Chat_Message.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Chat_Message.toString(), chat_message.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return chatMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final atlas_ui_data.proxies.Chat that = (atlas_ui_data.proxies.Chat) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Atlas_UI_Data.Chat";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
