// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package atlas_ui_data.proxies;

public class PeopleDepartments
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject peopleDepartmentsMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Atlas_UI_Data.PeopleDepartments";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Department("Department"),
		PeopleCategory_People("Atlas_UI_Data.PeopleCategory_People");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public PeopleDepartments(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Atlas_UI_Data.PeopleDepartments"));
	}

	protected PeopleDepartments(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject peopleDepartmentsMendixObject)
	{
		if (peopleDepartmentsMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Atlas_UI_Data.PeopleDepartments", peopleDepartmentsMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Atlas_UI_Data.PeopleDepartments");

		this.peopleDepartmentsMendixObject = peopleDepartmentsMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'PeopleDepartments.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static atlas_ui_data.proxies.PeopleDepartments initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return atlas_ui_data.proxies.PeopleDepartments.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static atlas_ui_data.proxies.PeopleDepartments initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new atlas_ui_data.proxies.PeopleDepartments(context, mendixObject);
	}

	public static atlas_ui_data.proxies.PeopleDepartments load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return atlas_ui_data.proxies.PeopleDepartments.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * Set value of Department
	 * @param department
	 */
	public final atlas_ui_data.proxies.Departments getDepartment()
	{
		return getDepartment(getContext());
	}

	/**
	 * @param context
	 * @return value of Department
	 */
	public final atlas_ui_data.proxies.Departments getDepartment(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Department.toString());
		if (obj == null)
			return null;

		return atlas_ui_data.proxies.Departments.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Department
	 * @param department
	 */
	public final void setDepartment(atlas_ui_data.proxies.Departments department)
	{
		setDepartment(getContext(), department);
	}

	/**
	 * Set value of Department
	 * @param context
	 * @param department
	 */
	public final void setDepartment(com.mendix.systemwideinterfaces.core.IContext context, atlas_ui_data.proxies.Departments department)
	{
		if (department != null)
			getMendixObject().setValue(context, MemberNames.Department.toString(), department.toString());
		else
			getMendixObject().setValue(context, MemberNames.Department.toString(), null);
	}

	/**
	 * @return value of PeopleCategory_People
	 */
	public final atlas_ui_data.proxies.AtlasPeople getPeopleCategory_People() throws com.mendix.core.CoreException
	{
		return getPeopleCategory_People(getContext());
	}

	/**
	 * @param context
	 * @return value of PeopleCategory_People
	 */
	public final atlas_ui_data.proxies.AtlasPeople getPeopleCategory_People(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		atlas_ui_data.proxies.AtlasPeople result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.PeopleCategory_People.toString());
		if (identifier != null)
			result = atlas_ui_data.proxies.AtlasPeople.load(context, identifier);
		return result;
	}

	/**
	 * Set value of PeopleCategory_People
	 * @param peoplecategory_people
	 */
	public final void setPeopleCategory_People(atlas_ui_data.proxies.AtlasPeople peoplecategory_people)
	{
		setPeopleCategory_People(getContext(), peoplecategory_people);
	}

	/**
	 * Set value of PeopleCategory_People
	 * @param context
	 * @param peoplecategory_people
	 */
	public final void setPeopleCategory_People(com.mendix.systemwideinterfaces.core.IContext context, atlas_ui_data.proxies.AtlasPeople peoplecategory_people)
	{
		if (peoplecategory_people == null)
			getMendixObject().setValue(context, MemberNames.PeopleCategory_People.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.PeopleCategory_People.toString(), peoplecategory_people.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return peopleDepartmentsMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final atlas_ui_data.proxies.PeopleDepartments that = (atlas_ui_data.proxies.PeopleDepartments) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Atlas_UI_Data.PeopleDepartments";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
