// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package fileuploader.proxies;

public class FileDocument extends system.proxies.FileDocument
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "FileUploader.FileDocument";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Size("Size"),
		FileDocument_FileContext("FileUploader.FileDocument_FileContext");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public FileDocument(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected FileDocument(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject fileDocumentMendixObject)
	{
		super(context, fileDocumentMendixObject);
		if (!com.mendix.core.Core.isSubClassOf(entityName, fileDocumentMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * @deprecated Use 'FileDocument.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static fileuploader.proxies.FileDocument initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return fileuploader.proxies.FileDocument.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static fileuploader.proxies.FileDocument initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new fileuploader.proxies.FileDocument(context, mendixObject);
	}

	public static fileuploader.proxies.FileDocument load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return fileuploader.proxies.FileDocument.initialize(context, mendixObject);
	}

	public static java.util.List<fileuploader.proxies.FileDocument> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> fileuploader.proxies.FileDocument.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of FileDocument_FileContext
	 */
	public final fileuploader.proxies.FileContext getFileDocument_FileContext() throws com.mendix.core.CoreException
	{
		return getFileDocument_FileContext(getContext());
	}

	/**
	 * @param context
	 * @return value of FileDocument_FileContext
	 * @throws com.mendix.core.CoreException
	 */
	public final fileuploader.proxies.FileContext getFileDocument_FileContext(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		fileuploader.proxies.FileContext result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.FileDocument_FileContext.toString());
		if (identifier != null) {
			result = fileuploader.proxies.FileContext.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of FileDocument_FileContext
	 * @param filedocument_filecontext
	 */
	public final void setFileDocument_FileContext(fileuploader.proxies.FileContext filedocument_filecontext)
	{
		setFileDocument_FileContext(getContext(), filedocument_filecontext);
	}

	/**
	 * Set value of FileDocument_FileContext
	 * @param context
	 * @param filedocument_filecontext
	 */
	public final void setFileDocument_FileContext(com.mendix.systemwideinterfaces.core.IContext context, fileuploader.proxies.FileContext filedocument_filecontext)
	{
		if (filedocument_filecontext == null) {
			getMendixObject().setValue(context, MemberNames.FileDocument_FileContext.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.FileDocument_FileContext.toString(), filedocument_filecontext.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final fileuploader.proxies.FileDocument that = (fileuploader.proxies.FileDocument) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
