// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package fileuploader.proxies;

public class UploadedImage extends system.proxies.Image
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "FileUploader.UploadedImage";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		PublicThumbnailPath("PublicThumbnailPath"),
		EnableCaching("EnableCaching"),
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Size("Size"),
		UploadedImage_FileUploadContext("FileUploader.UploadedImage_FileUploadContext");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public UploadedImage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected UploadedImage(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject uploadedImageMendixObject)
	{
		super(context, uploadedImageMendixObject);
		if (!uploadedImageMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static fileuploader.proxies.UploadedImage initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new fileuploader.proxies.UploadedImage(context, mendixObject);
	}

	public static fileuploader.proxies.UploadedImage load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return fileuploader.proxies.UploadedImage.initialize(context, mendixObject);
	}

	public static java.util.List<fileuploader.proxies.UploadedImage> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> fileuploader.proxies.UploadedImage.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of UploadedImage_FileUploadContext
	 */
	public final fileuploader.proxies.FileUploadContext getUploadedImage_FileUploadContext() throws com.mendix.core.CoreException
	{
		return getUploadedImage_FileUploadContext(getContext());
	}

	/**
	 * @param context
	 * @return value of UploadedImage_FileUploadContext
	 * @throws com.mendix.core.CoreException
	 */
	public final fileuploader.proxies.FileUploadContext getUploadedImage_FileUploadContext(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		fileuploader.proxies.FileUploadContext result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.UploadedImage_FileUploadContext.toString());
		if (identifier != null) {
			result = fileuploader.proxies.FileUploadContext.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of UploadedImage_FileUploadContext
	 * @param uploadedimage_fileuploadcontext
	 */
	public final void setUploadedImage_FileUploadContext(fileuploader.proxies.FileUploadContext uploadedimage_fileuploadcontext)
	{
		setUploadedImage_FileUploadContext(getContext(), uploadedimage_fileuploadcontext);
	}

	/**
	 * Set value of UploadedImage_FileUploadContext
	 * @param context
	 * @param uploadedimage_fileuploadcontext
	 */
	public final void setUploadedImage_FileUploadContext(com.mendix.systemwideinterfaces.core.IContext context, fileuploader.proxies.FileUploadContext uploadedimage_fileuploadcontext)
	{
		if (uploadedimage_fileuploadcontext == null) {
			getMendixObject().setValue(context, MemberNames.UploadedImage_FileUploadContext.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.UploadedImage_FileUploadContext.toString(), uploadedimage_fileuploadcontext.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final fileuploader.proxies.UploadedImage that = (fileuploader.proxies.UploadedImage) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
