// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package atlas_ui_data.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the Atlas_UI_Data module
	public static java.util.List<atlas_ui_data.proxies.AtlasChartData> dS_CreateAtlasChartData(IContext context, atlas_ui_data.proxies.AtlasStatistics _atlasStatistics)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("AtlasStatistics", _atlasStatistics == null ? null : _atlasStatistics.getMendixObject());
		java.util.List<IMendixObject> objs = Core.microflowCall("Atlas_UI_Data.DS_CreateAtlasChartData").withParams(params).execute(context);
		java.util.List<atlas_ui_data.proxies.AtlasChartData> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(atlas_ui_data.proxies.AtlasChartData.initialize(context, obj));
		}
		return result;
	}
	public static atlas_ui_data.proxies.AtlasGenericObject dS_DuplicateGenericObject(IContext context, atlas_ui_data.proxies.AtlasGenericObject _defaultObject)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("DefaultObject", _defaultObject == null ? null : _defaultObject.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("Atlas_UI_Data.DS_DuplicateGenericObject").withParams(params).execute(context);
		return result == null ? null : atlas_ui_data.proxies.AtlasGenericObject.initialize(context, result);
	}
	public static atlas_ui_data.proxies.AtlasLocationDate dS_DuplicateLocationDate(IContext context, atlas_ui_data.proxies.AtlasLocationDate _locationDateObjectParam)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("LocationDateObjectParam", _locationDateObjectParam == null ? null : _locationDateObjectParam.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("Atlas_UI_Data.DS_DuplicateLocationDate").withParams(params).execute(context);
		return result == null ? null : atlas_ui_data.proxies.AtlasLocationDate.initialize(context, result);
	}
	public static atlas_ui_data.proxies.AtlasPeople dS_DuplicatePeople(IContext context, atlas_ui_data.proxies.AtlasPeople _atlasUserParam)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("AtlasUserParam", _atlasUserParam == null ? null : _atlasUserParam.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("Atlas_UI_Data.DS_DuplicatePeople").withParams(params).execute(context);
		return result == null ? null : atlas_ui_data.proxies.AtlasPeople.initialize(context, result);
	}
	public static atlas_ui_data.proxies.AtlasStatistics dS_DuplicateStatistic(IContext context, atlas_ui_data.proxies.AtlasStatistics _atlasStatisticsParam)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("AtlasStatisticsParam", _atlasStatisticsParam == null ? null : _atlasStatisticsParam.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("Atlas_UI_Data.DS_DuplicateStatistic").withParams(params).execute(context);
		return result == null ? null : atlas_ui_data.proxies.AtlasStatistics.initialize(context, result);
	}
	public static atlas_ui_data.proxies.AtlasGenericObject dS_EmptyGenericObject(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("Atlas_UI_Data.DS_EmptyGenericObject").withParams(params).execute(context);
		return result == null ? null : atlas_ui_data.proxies.AtlasGenericObject.initialize(context, result);
	}
	public static atlas_ui_data.proxies.AtlasGenericObject iVK_GetFirstGenericObject(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("Atlas_UI_Data.IVK_GetFirstGenericObject").withParams(params).execute(context);
		return result == null ? null : atlas_ui_data.proxies.AtlasGenericObject.initialize(context, result);
	}
	public static atlas_ui_data.proxies.AtlasLocationDate iVK_GetFirstLocationDateObject(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("Atlas_UI_Data.IVK_GetFirstLocationDateObject").withParams(params).execute(context);
		return result == null ? null : atlas_ui_data.proxies.AtlasLocationDate.initialize(context, result);
	}
	public static atlas_ui_data.proxies.AtlasPeople iVK_GetFirstPeopleObject(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("Atlas_UI_Data.IVK_GetFirstPeopleObject").withParams(params).execute(context);
		return result == null ? null : atlas_ui_data.proxies.AtlasPeople.initialize(context, result);
	}
	public static atlas_ui_data.proxies.AtlasStatistics iVK_GetFirstStatisticObject(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("Atlas_UI_Data.IVK_GetFirstStatisticObject").withParams(params).execute(context);
		return result == null ? null : atlas_ui_data.proxies.AtlasStatistics.initialize(context, result);
	}
	public static java.util.List<atlas_ui_data.proxies.AtlasGenericObject> iVK_RetrieveAllGenericObjects(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		java.util.List<IMendixObject> objs = Core.microflowCall("Atlas_UI_Data.IVK_RetrieveAllGenericObjects").withParams(params).execute(context);
		java.util.List<atlas_ui_data.proxies.AtlasGenericObject> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(atlas_ui_data.proxies.AtlasGenericObject.initialize(context, obj));
		}
		return result;
	}
	public static java.util.List<atlas_ui_data.proxies.AtlasLocationDate> iVK_RetrieveAllLocationDateObjects(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		java.util.List<IMendixObject> objs = Core.microflowCall("Atlas_UI_Data.IVK_RetrieveAllLocationDateObjects").withParams(params).execute(context);
		java.util.List<atlas_ui_data.proxies.AtlasLocationDate> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(atlas_ui_data.proxies.AtlasLocationDate.initialize(context, obj));
		}
		return result;
	}
	public static java.util.List<atlas_ui_data.proxies.AtlasPeople> iVK_RetrieveAllPeopleObjects(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		java.util.List<IMendixObject> objs = Core.microflowCall("Atlas_UI_Data.IVK_RetrieveAllPeopleObjects").withParams(params).execute(context);
		java.util.List<atlas_ui_data.proxies.AtlasPeople> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(atlas_ui_data.proxies.AtlasPeople.initialize(context, obj));
		}
		return result;
	}
	public static java.util.List<atlas_ui_data.proxies.AtlasStatistics> iVK_RetrieveAllStatisticObjects(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		java.util.List<IMendixObject> objs = Core.microflowCall("Atlas_UI_Data.IVK_RetrieveAllStatisticObjects").withParams(params).execute(context);
		java.util.List<atlas_ui_data.proxies.AtlasStatistics> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(atlas_ui_data.proxies.AtlasStatistics.initialize(context, obj));
		}
		return result;
	}
}