// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package rest.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the Rest module
	public static void iVK_RestEventClick(IContext context, myfirstmodule.proxies.Values _values)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Values", _values == null ? null : _values.getMendixObject());
		Core.microflowCall("Rest.IVK_RestEventClick").withParams(params).execute(context);
	}
	public static system.proxies.HttpResponse rEST_GetHeatMapData(IContext context, system.proxies.HttpRequest _httpRequest, java.lang.String _contextId, java.lang.String _serieName)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("HttpRequest", _httpRequest == null ? null : _httpRequest.getMendixObject());
		params.put("contextId", _contextId);
		params.put("serieName", _serieName);
		IMendixObject result = (IMendixObject)Core.microflowCall("Rest.REST_GetHeatMapData").withParams(params).execute(context);
		return result == null ? null : system.proxies.HttpResponse.initialize(context, result);
	}
	public static void rEST_GetLine_Date(IContext context, system.proxies.HttpRequest _httpRequest, java.lang.String _name, java.lang.String _contextId, java.lang.String _seriesName)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("HttpRequest", _httpRequest == null ? null : _httpRequest.getMendixObject());
		params.put("Name", _name);
		params.put("contextId", _contextId);
		params.put("seriesName", _seriesName);
		Core.microflowCall("Rest.REST_GetLine_Date").withParams(params).execute(context);
	}
	public static system.proxies.HttpResponse rEST_GetLine_Enumeration(IContext context, system.proxies.HttpRequest _httpRequest, java.lang.String _name, java.lang.String _contextId, java.lang.String _seriesName)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("HttpRequest", _httpRequest == null ? null : _httpRequest.getMendixObject());
		params.put("Name", _name);
		params.put("contextId", _contextId);
		params.put("seriesName", _seriesName);
		IMendixObject result = (IMendixObject)Core.microflowCall("Rest.REST_GetLine_Enumeration").withParams(params).execute(context);
		return result == null ? null : system.proxies.HttpResponse.initialize(context, result);
	}
	public static system.proxies.HttpResponse rEST_GetLineChart(IContext context, system.proxies.HttpRequest _httpRequest, java.lang.String _name, java.lang.String _contextId, java.lang.String _seriesName)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("HttpRequest", _httpRequest == null ? null : _httpRequest.getMendixObject());
		params.put("Name", _name);
		params.put("contextId", _contextId);
		params.put("seriesName", _seriesName);
		IMendixObject result = (IMendixObject)Core.microflowCall("Rest.REST_GetLineChart").withParams(params).execute(context);
		return result == null ? null : system.proxies.HttpResponse.initialize(context, result);
	}
	public static system.proxies.HttpResponse rEST_GetLineChart_Decimal(IContext context, system.proxies.HttpRequest _httpRequest, java.lang.String _name, java.lang.String _contextId, java.lang.String _seriesName)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("HttpRequest", _httpRequest == null ? null : _httpRequest.getMendixObject());
		params.put("Name", _name);
		params.put("contextId", _contextId);
		params.put("seriesName", _seriesName);
		IMendixObject result = (IMendixObject)Core.microflowCall("Rest.REST_GetLineChart_Decimal").withParams(params).execute(context);
		return result == null ? null : system.proxies.HttpResponse.initialize(context, result);
	}
	public static system.proxies.HttpResponse rEST_GetLineChart_Dynamic(IContext context, system.proxies.HttpRequest _httpRequest, java.lang.String _name, java.lang.String _contextId, java.lang.String _seriesName)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("HttpRequest", _httpRequest == null ? null : _httpRequest.getMendixObject());
		params.put("Name", _name);
		params.put("contextId", _contextId);
		params.put("seriesName", _seriesName);
		IMendixObject result = (IMendixObject)Core.microflowCall("Rest.REST_GetLineChart_Dynamic").withParams(params).execute(context);
		return result == null ? null : system.proxies.HttpResponse.initialize(context, result);
	}
	public static system.proxies.HttpResponse rEST_GetLineChart_Dynamic_Series_4(IContext context, system.proxies.HttpRequest _httpRequest)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("HttpRequest", _httpRequest == null ? null : _httpRequest.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("Rest.REST_GetLineChart_Dynamic_Series_4").withParams(params).execute(context);
		return result == null ? null : system.proxies.HttpResponse.initialize(context, result);
	}
	public static system.proxies.HttpResponse rEST_GetLineChart_Dynamic_Series_5(IContext context, system.proxies.HttpRequest _httpRequest)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("HttpRequest", _httpRequest == null ? null : _httpRequest.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("Rest.REST_GetLineChart_Dynamic_Series_5").withParams(params).execute(context);
		return result == null ? null : system.proxies.HttpResponse.initialize(context, result);
	}
	public static system.proxies.HttpResponse rEST_GetLineChart_Shared(IContext context, system.proxies.HttpRequest _httpRequest, java.lang.String _name, java.lang.String _contextId, java.lang.String _seriesName)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("HttpRequest", _httpRequest == null ? null : _httpRequest.getMendixObject());
		params.put("Name", _name);
		params.put("contextId", _contextId);
		params.put("seriesName", _seriesName);
		IMendixObject result = (IMendixObject)Core.microflowCall("Rest.REST_GetLineChart_Shared").withParams(params).execute(context);
		return result == null ? null : system.proxies.HttpResponse.initialize(context, result);
	}
	public static system.proxies.HttpResponse rEST_GetPieData(IContext context, system.proxies.HttpRequest _httpRequest, java.lang.String _contextId)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("HttpRequest", _httpRequest == null ? null : _httpRequest.getMendixObject());
		params.put("contextId", _contextId);
		IMendixObject result = (IMendixObject)Core.microflowCall("Rest.REST_GetPieData").withParams(params).execute(context);
		return result == null ? null : system.proxies.HttpResponse.initialize(context, result);
	}
}