// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public enum Months
{
	Jan(new java.lang.String[][] { new java.lang.String[] { "en_US", "Jan" } }),
	Feb(new java.lang.String[][] { new java.lang.String[] { "en_US", "Feb" } }),
	Mar(new java.lang.String[][] { new java.lang.String[] { "en_US", "Mar" } }),
	Apr(new java.lang.String[][] { new java.lang.String[] { "en_US", "Apr" } }),
	May(new java.lang.String[][] { new java.lang.String[] { "en_US", "May" } }),
	June(new java.lang.String[][] { new java.lang.String[] { "en_US", "June" } }),
	July(new java.lang.String[][] { new java.lang.String[] { "en_US", "July" } }),
	Aug(new java.lang.String[][] { new java.lang.String[] { "en_US", "Aug" } }),
	Sept(new java.lang.String[][] { new java.lang.String[] { "en_US", "Sept" } }),
	Oct(new java.lang.String[][] { new java.lang.String[] { "en_US", "Oct" } }),
	Nov(new java.lang.String[][] { new java.lang.String[] { "en_US", "Nov" } }),
	Dec(new java.lang.String[][] { new java.lang.String[] { "en_US", "Dec" } });

	private java.util.Map<java.lang.String, java.lang.String> captions;

	private Months(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<java.lang.String, java.lang.String>();
		for (java.lang.String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
