// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public enum Roles
{
	Architect(new java.lang.String[][] { new java.lang.String[] { "en_US", "Architect" } }),
	Product_Designer(new java.lang.String[][] { new java.lang.String[] { "en_US", "Product Designer" } }),
	Product_Manager(new java.lang.String[][] { new java.lang.String[] { "en_US", "Product Manager" } }),
	QA_Engineer(new java.lang.String[][] { new java.lang.String[] { "en_US", "QA Engineer" } }),
	Software_Development_Manager(new java.lang.String[][] { new java.lang.String[] { "en_US", "Software Development Manager" } }),
	Software_Engineer(new java.lang.String[][] { new java.lang.String[] { "en_US", "Software Engineer" } }),
	Team_Lead(new java.lang.String[][] { new java.lang.String[] { "en_US", "Team Lead" } }),
	Tech_Lead(new java.lang.String[][] { new java.lang.String[] { "en_US", "Tech Lead" } });

	private java.util.Map<java.lang.String, java.lang.String> captions;

	private Roles(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<java.lang.String, java.lang.String>();
		for (java.lang.String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
