// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class SeriesCore
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject seriesCoreMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.SeriesCore";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		name("name"),
		color("color"),
		fillColor("fillColor"),
		EnumName("EnumName"),
		SeriesCore_Chart("MyFirstModule.SeriesCore_Chart");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public SeriesCore(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MyFirstModule.SeriesCore"));
	}

	protected SeriesCore(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject seriesCoreMendixObject)
	{
		if (seriesCoreMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MyFirstModule.SeriesCore", seriesCoreMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MyFirstModule.SeriesCore");

		this.seriesCoreMendixObject = seriesCoreMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'SeriesCore.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static myfirstmodule.proxies.SeriesCore initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.SeriesCore.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static myfirstmodule.proxies.SeriesCore initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.SeriesCore(context, mendixObject);
	}

	public static myfirstmodule.proxies.SeriesCore load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.SeriesCore.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.SeriesCore> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<myfirstmodule.proxies.SeriesCore> result = new java.util.ArrayList<myfirstmodule.proxies.SeriesCore>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//MyFirstModule.SeriesCore" + xpathConstraint))
			result.add(myfirstmodule.proxies.SeriesCore.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of name
	 */
	public final java.lang.String getname()
	{
		return getname(getContext());
	}

	/**
	 * @param context
	 * @return value of name
	 */
	public final java.lang.String getname(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.name.toString());
	}

	/**
	 * Set value of name
	 * @param name
	 */
	public final void setname(java.lang.String name)
	{
		setname(getContext(), name);
	}

	/**
	 * Set value of name
	 * @param context
	 * @param name
	 */
	public final void setname(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.name.toString(), name);
	}

	/**
	 * @return value of color
	 */
	public final java.lang.String getcolor()
	{
		return getcolor(getContext());
	}

	/**
	 * @param context
	 * @return value of color
	 */
	public final java.lang.String getcolor(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.color.toString());
	}

	/**
	 * Set value of color
	 * @param color
	 */
	public final void setcolor(java.lang.String color)
	{
		setcolor(getContext(), color);
	}

	/**
	 * Set value of color
	 * @param context
	 * @param color
	 */
	public final void setcolor(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String color)
	{
		getMendixObject().setValue(context, MemberNames.color.toString(), color);
	}

	/**
	 * @return value of fillColor
	 */
	public final java.lang.String getfillColor()
	{
		return getfillColor(getContext());
	}

	/**
	 * @param context
	 * @return value of fillColor
	 */
	public final java.lang.String getfillColor(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.fillColor.toString());
	}

	/**
	 * Set value of fillColor
	 * @param fillcolor
	 */
	public final void setfillColor(java.lang.String fillcolor)
	{
		setfillColor(getContext(), fillcolor);
	}

	/**
	 * Set value of fillColor
	 * @param context
	 * @param fillcolor
	 */
	public final void setfillColor(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String fillcolor)
	{
		getMendixObject().setValue(context, MemberNames.fillColor.toString(), fillcolor);
	}

	/**
	 * Set value of EnumName
	 * @param enumname
	 */
	public final myfirstmodule.proxies.DynamicSeries_Names getEnumName()
	{
		return getEnumName(getContext());
	}

	/**
	 * @param context
	 * @return value of EnumName
	 */
	public final myfirstmodule.proxies.DynamicSeries_Names getEnumName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.EnumName.toString());
		if (obj == null)
			return null;

		return myfirstmodule.proxies.DynamicSeries_Names.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of EnumName
	 * @param enumname
	 */
	public final void setEnumName(myfirstmodule.proxies.DynamicSeries_Names enumname)
	{
		setEnumName(getContext(), enumname);
	}

	/**
	 * Set value of EnumName
	 * @param context
	 * @param enumname
	 */
	public final void setEnumName(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.DynamicSeries_Names enumname)
	{
		if (enumname != null)
			getMendixObject().setValue(context, MemberNames.EnumName.toString(), enumname.toString());
		else
			getMendixObject().setValue(context, MemberNames.EnumName.toString(), null);
	}

	/**
	 * @return value of SeriesCore_Chart
	 */
	public final myfirstmodule.proxies.Chart getSeriesCore_Chart() throws com.mendix.core.CoreException
	{
		return getSeriesCore_Chart(getContext());
	}

	/**
	 * @param context
	 * @return value of SeriesCore_Chart
	 */
	public final myfirstmodule.proxies.Chart getSeriesCore_Chart(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Chart result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.SeriesCore_Chart.toString());
		if (identifier != null)
			result = myfirstmodule.proxies.Chart.load(context, identifier);
		return result;
	}

	/**
	 * Set value of SeriesCore_Chart
	 * @param seriescore_chart
	 */
	public final void setSeriesCore_Chart(myfirstmodule.proxies.Chart seriescore_chart)
	{
		setSeriesCore_Chart(getContext(), seriescore_chart);
	}

	/**
	 * Set value of SeriesCore_Chart
	 * @param context
	 * @param seriescore_chart
	 */
	public final void setSeriesCore_Chart(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Chart seriescore_chart)
	{
		if (seriescore_chart == null)
			getMendixObject().setValue(context, MemberNames.SeriesCore_Chart.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.SeriesCore_Chart.toString(), seriescore_chart.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return seriesCoreMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.SeriesCore that = (myfirstmodule.proxies.SeriesCore) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MyFirstModule.SeriesCore";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
