// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class ValuesNpe
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject valuesNpeMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.ValuesNpe";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		xValue("xValue"),
		yValue("yValue"),
		weird("weird");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ValuesNpe(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MyFirstModule.ValuesNpe"));
	}

	protected ValuesNpe(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject valuesNpeMendixObject)
	{
		if (valuesNpeMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MyFirstModule.ValuesNpe", valuesNpeMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MyFirstModule.ValuesNpe");

		this.valuesNpeMendixObject = valuesNpeMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'ValuesNpe.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static myfirstmodule.proxies.ValuesNpe initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.ValuesNpe.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static myfirstmodule.proxies.ValuesNpe initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.ValuesNpe(context, mendixObject);
	}

	public static myfirstmodule.proxies.ValuesNpe load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.ValuesNpe.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of xValue
	 */
	public final java.lang.String getxValue()
	{
		return getxValue(getContext());
	}

	/**
	 * @param context
	 * @return value of xValue
	 */
	public final java.lang.String getxValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.xValue.toString());
	}

	/**
	 * Set value of xValue
	 * @param xvalue
	 */
	public final void setxValue(java.lang.String xvalue)
	{
		setxValue(getContext(), xvalue);
	}

	/**
	 * Set value of xValue
	 * @param context
	 * @param xvalue
	 */
	public final void setxValue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xvalue)
	{
		getMendixObject().setValue(context, MemberNames.xValue.toString(), xvalue);
	}

	/**
	 * @return value of yValue
	 */
	public final java.lang.Integer getyValue()
	{
		return getyValue(getContext());
	}

	/**
	 * @param context
	 * @return value of yValue
	 */
	public final java.lang.Integer getyValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.yValue.toString());
	}

	/**
	 * Set value of yValue
	 * @param yvalue
	 */
	public final void setyValue(java.lang.Integer yvalue)
	{
		setyValue(getContext(), yvalue);
	}

	/**
	 * Set value of yValue
	 * @param context
	 * @param yvalue
	 */
	public final void setyValue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer yvalue)
	{
		getMendixObject().setValue(context, MemberNames.yValue.toString(), yvalue);
	}

	/**
	 * @return value of weird
	 */
	public final java.lang.String getweird()
	{
		return getweird(getContext());
	}

	/**
	 * @param context
	 * @return value of weird
	 */
	public final java.lang.String getweird(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.weird.toString());
	}

	/**
	 * Set value of weird
	 * @param weird
	 */
	public final void setweird(java.lang.String weird)
	{
		setweird(getContext(), weird);
	}

	/**
	 * Set value of weird
	 * @param context
	 * @param weird
	 */
	public final void setweird(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String weird)
	{
		getMendixObject().setValue(context, MemberNames.weird.toString(), weird);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return valuesNpeMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.ValuesNpe that = (myfirstmodule.proxies.ValuesNpe) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MyFirstModule.ValuesNpe";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
