// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class Values
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject valuesMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.Values";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		xValue("xValue"),
		yValue("yValue"),
		xValueEnum("xValueEnum"),
		bubbleSize("bubbleSize"),
		yValueDecimal("yValueDecimal"),
		Values_X_OverReference("MyFirstModule.Values_X_OverReference"),
		Values_SeriesCore("MyFirstModule.Values_SeriesCore");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Values(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MyFirstModule.Values"));
	}

	protected Values(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject valuesMendixObject)
	{
		if (valuesMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MyFirstModule.Values", valuesMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MyFirstModule.Values");

		this.valuesMendixObject = valuesMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Values.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static myfirstmodule.proxies.Values initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.Values.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static myfirstmodule.proxies.Values initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.Values(context, mendixObject);
	}

	public static myfirstmodule.proxies.Values load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.Values.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.Values> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<myfirstmodule.proxies.Values> result = new java.util.ArrayList<myfirstmodule.proxies.Values>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//MyFirstModule.Values" + xpathConstraint))
			result.add(myfirstmodule.proxies.Values.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of xValue
	 */
	public final java.lang.String getxValue()
	{
		return getxValue(getContext());
	}

	/**
	 * @param context
	 * @return value of xValue
	 */
	public final java.lang.String getxValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.xValue.toString());
	}

	/**
	 * Set value of xValue
	 * @param xvalue
	 */
	public final void setxValue(java.lang.String xvalue)
	{
		setxValue(getContext(), xvalue);
	}

	/**
	 * Set value of xValue
	 * @param context
	 * @param xvalue
	 */
	public final void setxValue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xvalue)
	{
		getMendixObject().setValue(context, MemberNames.xValue.toString(), xvalue);
	}

	/**
	 * @return value of yValue
	 */
	public final java.lang.Integer getyValue()
	{
		return getyValue(getContext());
	}

	/**
	 * @param context
	 * @return value of yValue
	 */
	public final java.lang.Integer getyValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.yValue.toString());
	}

	/**
	 * Set value of yValue
	 * @param yvalue
	 */
	public final void setyValue(java.lang.Integer yvalue)
	{
		setyValue(getContext(), yvalue);
	}

	/**
	 * Set value of yValue
	 * @param context
	 * @param yvalue
	 */
	public final void setyValue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer yvalue)
	{
		getMendixObject().setValue(context, MemberNames.yValue.toString(), yvalue);
	}

	/**
	 * Set value of xValueEnum
	 * @param xvalueenum
	 */
	public final myfirstmodule.proxies.Months getxValueEnum()
	{
		return getxValueEnum(getContext());
	}

	/**
	 * @param context
	 * @return value of xValueEnum
	 */
	public final myfirstmodule.proxies.Months getxValueEnum(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.xValueEnum.toString());
		if (obj == null)
			return null;

		return myfirstmodule.proxies.Months.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of xValueEnum
	 * @param xvalueenum
	 */
	public final void setxValueEnum(myfirstmodule.proxies.Months xvalueenum)
	{
		setxValueEnum(getContext(), xvalueenum);
	}

	/**
	 * Set value of xValueEnum
	 * @param context
	 * @param xvalueenum
	 */
	public final void setxValueEnum(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Months xvalueenum)
	{
		if (xvalueenum != null)
			getMendixObject().setValue(context, MemberNames.xValueEnum.toString(), xvalueenum.toString());
		else
			getMendixObject().setValue(context, MemberNames.xValueEnum.toString(), null);
	}

	/**
	 * @return value of bubbleSize
	 */
	public final java.lang.Integer getbubbleSize()
	{
		return getbubbleSize(getContext());
	}

	/**
	 * @param context
	 * @return value of bubbleSize
	 */
	public final java.lang.Integer getbubbleSize(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.bubbleSize.toString());
	}

	/**
	 * Set value of bubbleSize
	 * @param bubblesize
	 */
	public final void setbubbleSize(java.lang.Integer bubblesize)
	{
		setbubbleSize(getContext(), bubblesize);
	}

	/**
	 * Set value of bubbleSize
	 * @param context
	 * @param bubblesize
	 */
	public final void setbubbleSize(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer bubblesize)
	{
		getMendixObject().setValue(context, MemberNames.bubbleSize.toString(), bubblesize);
	}

	/**
	 * @return value of yValueDecimal
	 */
	public final java.math.BigDecimal getyValueDecimal()
	{
		return getyValueDecimal(getContext());
	}

	/**
	 * @param context
	 * @return value of yValueDecimal
	 */
	public final java.math.BigDecimal getyValueDecimal(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.yValueDecimal.toString());
	}

	/**
	 * Set value of yValueDecimal
	 * @param yvaluedecimal
	 */
	public final void setyValueDecimal(java.math.BigDecimal yvaluedecimal)
	{
		setyValueDecimal(getContext(), yvaluedecimal);
	}

	/**
	 * Set value of yValueDecimal
	 * @param context
	 * @param yvaluedecimal
	 */
	public final void setyValueDecimal(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal yvaluedecimal)
	{
		getMendixObject().setValue(context, MemberNames.yValueDecimal.toString(), yvaluedecimal);
	}

	/**
	 * @return value of Values_X_OverReference
	 */
	public final myfirstmodule.proxies.X_OverReference getValues_X_OverReference() throws com.mendix.core.CoreException
	{
		return getValues_X_OverReference(getContext());
	}

	/**
	 * @param context
	 * @return value of Values_X_OverReference
	 */
	public final myfirstmodule.proxies.X_OverReference getValues_X_OverReference(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.X_OverReference result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Values_X_OverReference.toString());
		if (identifier != null)
			result = myfirstmodule.proxies.X_OverReference.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Values_X_OverReference
	 * @param values_x_overreference
	 */
	public final void setValues_X_OverReference(myfirstmodule.proxies.X_OverReference values_x_overreference)
	{
		setValues_X_OverReference(getContext(), values_x_overreference);
	}

	/**
	 * Set value of Values_X_OverReference
	 * @param context
	 * @param values_x_overreference
	 */
	public final void setValues_X_OverReference(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.X_OverReference values_x_overreference)
	{
		if (values_x_overreference == null)
			getMendixObject().setValue(context, MemberNames.Values_X_OverReference.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Values_X_OverReference.toString(), values_x_overreference.getMendixObject().getId());
	}

	/**
	 * @return value of Values_SeriesCore
	 */
	public final myfirstmodule.proxies.SeriesCore getValues_SeriesCore() throws com.mendix.core.CoreException
	{
		return getValues_SeriesCore(getContext());
	}

	/**
	 * @param context
	 * @return value of Values_SeriesCore
	 */
	public final myfirstmodule.proxies.SeriesCore getValues_SeriesCore(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.SeriesCore result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Values_SeriesCore.toString());
		if (identifier != null)
			result = myfirstmodule.proxies.SeriesCore.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Values_SeriesCore
	 * @param values_seriescore
	 */
	public final void setValues_SeriesCore(myfirstmodule.proxies.SeriesCore values_seriescore)
	{
		setValues_SeriesCore(getContext(), values_seriescore);
	}

	/**
	 * Set value of Values_SeriesCore
	 * @param context
	 * @param values_seriescore
	 */
	public final void setValues_SeriesCore(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.SeriesCore values_seriescore)
	{
		if (values_seriescore == null)
			getMendixObject().setValue(context, MemberNames.Values_SeriesCore.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Values_SeriesCore.toString(), values_seriescore.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return valuesMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.Values that = (myfirstmodule.proxies.Values) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MyFirstModule.Values";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
