// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package allcustomwidgets.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;

public class Microflows
{
	// These are the microflows for the AllCustomWidgets module
	public static void aCT_AddMore(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("AllCustomWidgets.ACT_AddMore").withParams(params).execute(context);
	}
	public static void aCT_Delete_ALL(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("AllCustomWidgets.ACT_Delete_ALL").withParams(params).execute(context);
	}
	public static void aCT_Delete_First(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("AllCustomWidgets.ACT_Delete_First").withParams(params).execute(context);
	}
	public static void aCT_Delete_Last(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("AllCustomWidgets.ACT_Delete_Last").withParams(params).execute(context);
	}
	public static void iVK_CreateSampleData(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("AllCustomWidgets.IVK_CreateSampleData").withParams(params).execute(context);
	}
}