// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package testsuite.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the TestSuite module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_DeleteImageBuilder(
		testsuite.proxies.Image _image
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("TestSuite.ACT_DeleteImage");
		builder = builder.withParam("Image", _image);
		return builder;
	}

	public static void aCT_DeleteImage(
		IContext context,
		testsuite.proxies.Image _image
	)
	{
		aCT_DeleteImageBuilder(
				_image
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_OnClickImageBuilder(
		testsuite.proxies.Image _carouselImage
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("TestSuite.ACT_OnClickImage");
		builder = builder.withParam("CarouselImage", _carouselImage);
		return builder;
	}

	public static void aCT_OnClickImage(
		IContext context,
		testsuite.proxies.Image _carouselImage
	)
	{
		aCT_OnClickImageBuilder(
				_carouselImage
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_OnClickImage_ClosePageBuilder(
		testsuite.proxies.Image _carouselImage
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("TestSuite.ACT_OnClickImage_ClosePage");
		builder = builder.withParam("CarouselImage", _carouselImage);
		return builder;
	}

	public static void aCT_OnClickImage_ClosePage(
		IContext context,
		testsuite.proxies.Image _carouselImage
	)
	{
		aCT_OnClickImage_ClosePageBuilder(
				_carouselImage
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_OnClickImageNoContextBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("TestSuite.ACT_OnClickImageNoContext");
		return builder;
	}

	public static void aCT_OnClickImageNoContext(IContext context)
	{
		aCT_OnClickImageNoContextBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_OnClickImageNoContext_2Builder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("TestSuite.ACT_OnClickImageNoContext_2");
		return builder;
	}

	public static void aCT_OnClickImageNoContext_2(IContext context)
	{
		aCT_OnClickImageNoContext_2Builder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_OnClickImageNoContext_3Builder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("TestSuite.ACT_OnClickImageNoContext_3");
		return builder;
	}

	public static void aCT_OnClickImageNoContext_3(IContext context)
	{
		aCT_OnClickImageNoContext_3Builder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_OnClickImageNoContext_4Builder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("TestSuite.ACT_OnClickImageNoContext_4");
		return builder;
	}

	public static void aCT_OnClickImageNoContext_4(IContext context)
	{
		aCT_OnClickImageNoContext_4Builder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_SaveAndRefreshBuilder(
		testsuite.proxies.Image _image
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("TestSuite.ACT_SaveAndRefresh");
		builder = builder.withParam("Image", _image);
		return builder;
	}

	public static void aCT_SaveAndRefresh(
		IContext context,
		testsuite.proxies.Image _image
	)
	{
		aCT_SaveAndRefreshBuilder(
				_image
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_UploadBuilder(
		testsuite.proxies.Carousel _carousel
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("TestSuite.ACT_Upload");
		builder = builder.withParam("Carousel", _carousel);
		return builder;
	}

	public static void aCT_Upload(
		IContext context,
		testsuite.proxies.Carousel _carousel
	)
	{
		aCT_UploadBuilder(
				_carousel
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder afterStartupBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("TestSuite.AfterStartup");
		return builder;
	}

	public static boolean afterStartup(IContext context)
	{
		Object result = afterStartupBuilder().execute(context);
		return (boolean) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_GetCarouselBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("TestSuite.DS_GetCarousel");
		return builder;
	}

	public static testsuite.proxies.Carousel dS_GetCarousel(IContext context)
	{
		Object result = dS_GetCarouselBuilder().execute(context);
		return result == null ? null : testsuite.proxies.Carousel.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dSL_DatasourceTestDataBuilder(
		testsuite.proxies.Carousel _carousel
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("TestSuite.DSL_DatasourceTestData");
		builder = builder.withParam("Carousel", _carousel);
		return builder;
	}

	public static java.util.List<testsuite.proxies.Image> dSL_DatasourceTestData(
		IContext context,
		testsuite.proxies.Carousel _carousel
	)
	{
		Object result = dSL_DatasourceTestDataBuilder(
				_carousel
			)
			.execute(context);
		return result == null ? null : com.mendix.utils.ListUtils.map((java.util.List<IMendixObject>) result, obj -> testsuite.proxies.Image.initialize(context, obj));
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dSL_DatasourceTestData_NoContextBuilder(
		testsuite.proxies.Carousel _carousel
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("TestSuite.DSL_DatasourceTestData_NoContext");
		builder = builder.withParam("Carousel", _carousel);
		return builder;
	}

	public static java.util.List<testsuite.proxies.Image> dSL_DatasourceTestData_NoContext(
		IContext context,
		testsuite.proxies.Carousel _carousel
	)
	{
		Object result = dSL_DatasourceTestData_NoContextBuilder(
				_carousel
			)
			.execute(context);
		return result == null ? null : com.mendix.utils.ListUtils.map((java.util.List<IMendixObject>) result, obj -> testsuite.proxies.Image.initialize(context, obj));
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dSL_DatasourceTestData_withDelayBuilder(
		testsuite.proxies.Carousel _carousel
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("TestSuite.DSL_DatasourceTestData_withDelay");
		builder = builder.withParam("Carousel", _carousel);
		return builder;
	}

	public static java.util.List<testsuite.proxies.Image> dSL_DatasourceTestData_withDelay(
		IContext context,
		testsuite.proxies.Carousel _carousel
	)
	{
		Object result = dSL_DatasourceTestData_withDelayBuilder(
				_carousel
			)
			.execute(context);
		return result == null ? null : com.mendix.utils.ListUtils.map((java.util.List<IMendixObject>) result, obj -> testsuite.proxies.Image.initialize(context, obj));
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dSL_TestsBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("TestSuite.DSL_Tests");
		return builder;
	}

	public static java.util.List<testsuite.proxies.Carousel> dSL_Tests(IContext context)
	{
		Object result = dSL_TestsBuilder().execute(context);
		return result == null ? null : com.mendix.utils.ListUtils.map((java.util.List<IMendixObject>) result, obj -> testsuite.proxies.Carousel.initialize(context, obj));
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dSS_NoContextBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("TestSuite.DSS_NoContext");
		return builder;
	}

	public static testsuite.proxies.Carousel dSS_NoContext(IContext context)
	{
		Object result = dSS_NoContextBuilder().execute(context);
		return result == null ? null : testsuite.proxies.Carousel.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder gD_ReturnCarouselObjectBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("TestSuite.GD_ReturnCarouselObject");
		return builder;
	}

	public static testsuite.proxies.Carousel gD_ReturnCarouselObject(IContext context)
	{
		Object result = gD_ReturnCarouselObjectBuilder().execute(context);
		return result == null ? null : testsuite.proxies.Carousel.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder iVK_CommitBuilder(
		testsuite.proxies.Carousel _test
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("TestSuite.IVK_Commit");
		builder = builder.withParam("Test", _test);
		return builder;
	}

	public static void iVK_Commit(
		IContext context,
		testsuite.proxies.Carousel _test
	)
	{
		iVK_CommitBuilder(
				_test
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder iVK_MicroflowWithErrorBuilder(
		testsuite.proxies.Image _image
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("TestSuite.IVK_MicroflowWithError");
		builder = builder.withParam("Image", _image);
		return builder;
	}

	public static void iVK_MicroflowWithError(
		IContext context,
		testsuite.proxies.Image _image
	)
	{
		iVK_MicroflowWithErrorBuilder(
				_image
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder iVK_RefreshInClientBuilder(
		testsuite.proxies.Carousel _test
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("TestSuite.IVK_RefreshInClient");
		builder = builder.withParam("Test", _test);
		return builder;
	}

	public static void iVK_RefreshInClient(
		IContext context,
		testsuite.proxies.Carousel _test
	)
	{
		iVK_RefreshInClientBuilder(
				_test
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder iVK_ShowValidationsBuilder(
		testsuite.proxies.Carousel _test
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("TestSuite.IVK_ShowValidations");
		builder = builder.withParam("Test", _test);
		return builder;
	}

	public static void iVK_ShowValidations(
		IContext context,
		testsuite.proxies.Carousel _test
	)
	{
		iVK_ShowValidationsBuilder(
				_test
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder oCh_TestBuilder(
		testsuite.proxies.Carousel _test
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("TestSuite.OCh_Test");
		builder = builder.withParam("Test", _test);
		return builder;
	}

	public static void oCh_Test(
		IContext context,
		testsuite.proxies.Carousel _test
	)
	{
		oCh_TestBuilder(
				_test
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder onClick_DynamicBuilder(
		testsuite.proxies.Image _image
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("TestSuite.OnClick_Dynamic");
		builder = builder.withParam("Image", _image);
		return builder;
	}

	public static void onClick_Dynamic(
		IContext context,
		testsuite.proxies.Image _image
	)
	{
		onClick_DynamicBuilder(
				_image
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder onClick_Static1Builder(
		testsuite.proxies.Carousel _carousel
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("TestSuite.OnClick_Static1");
		builder = builder.withParam("Carousel", _carousel);
		return builder;
	}

	public static void onClick_Static1(
		IContext context,
		testsuite.proxies.Carousel _carousel
	)
	{
		onClick_Static1Builder(
				_carousel
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder onClick_Static2Builder(
		testsuite.proxies.Carousel _carousel
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("TestSuite.OnClick_Static2");
		builder = builder.withParam("Carousel", _carousel);
		return builder;
	}

	public static void onClick_Static2(
		IContext context,
		testsuite.proxies.Carousel _carousel
	)
	{
		onClick_Static2Builder(
				_carousel
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder onClickWithErrorBuilder(
		testsuite.proxies.Carousel _carousel
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("TestSuite.OnClickWithError");
		builder = builder.withParam("Carousel", _carousel);
		return builder;
	}

	public static void onClickWithError(
		IContext context,
		testsuite.proxies.Carousel _carousel
	)
	{
		onClickWithErrorBuilder(
				_carousel
			)
			.execute(context);
	}
}
