// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package native_widgets.proxies;

public class Chart
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject chartMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Native_Widgets.Chart";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		value("value"),
		value2("value2"),
		value3("value3");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Chart(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Native_Widgets.Chart"));
	}

	protected Chart(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject chartMendixObject)
	{
		if (chartMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Native_Widgets.Chart", chartMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Native_Widgets.Chart");

		this.chartMendixObject = chartMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Chart.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static native_widgets.proxies.Chart initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return native_widgets.proxies.Chart.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static native_widgets.proxies.Chart initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new native_widgets.proxies.Chart(context, mendixObject);
	}

	public static native_widgets.proxies.Chart load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return native_widgets.proxies.Chart.initialize(context, mendixObject);
	}

	public static java.util.List<native_widgets.proxies.Chart> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<native_widgets.proxies.Chart> result = new java.util.ArrayList<native_widgets.proxies.Chart>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//Native_Widgets.Chart" + xpathConstraint))
			result.add(native_widgets.proxies.Chart.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of value
	 */
	public final java.lang.Integer getvalue()
	{
		return getvalue(getContext());
	}

	/**
	 * @param context
	 * @return value of value
	 */
	public final java.lang.Integer getvalue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.value.toString());
	}

	/**
	 * Set value of value
	 * @param value
	 */
	public final void setvalue(java.lang.Integer value)
	{
		setvalue(getContext(), value);
	}

	/**
	 * Set value of value
	 * @param context
	 * @param value
	 */
	public final void setvalue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer value)
	{
		getMendixObject().setValue(context, MemberNames.value.toString(), value);
	}

	/**
	 * @return value of value2
	 */
	public final java.lang.Integer getvalue2()
	{
		return getvalue2(getContext());
	}

	/**
	 * @param context
	 * @return value of value2
	 */
	public final java.lang.Integer getvalue2(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.value2.toString());
	}

	/**
	 * Set value of value2
	 * @param value2
	 */
	public final void setvalue2(java.lang.Integer value2)
	{
		setvalue2(getContext(), value2);
	}

	/**
	 * Set value of value2
	 * @param context
	 * @param value2
	 */
	public final void setvalue2(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer value2)
	{
		getMendixObject().setValue(context, MemberNames.value2.toString(), value2);
	}

	/**
	 * @return value of value3
	 */
	public final java.lang.Integer getvalue3()
	{
		return getvalue3(getContext());
	}

	/**
	 * @param context
	 * @return value of value3
	 */
	public final java.lang.Integer getvalue3(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.value3.toString());
	}

	/**
	 * Set value of value3
	 * @param value3
	 */
	public final void setvalue3(java.lang.Integer value3)
	{
		setvalue3(getContext(), value3);
	}

	/**
	 * Set value of value3
	 * @param context
	 * @param value3
	 */
	public final void setvalue3(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer value3)
	{
		getMendixObject().setValue(context, MemberNames.value3.toString(), value3);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return chartMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final native_widgets.proxies.Chart that = (native_widgets.proxies.Chart) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Native_Widgets.Chart";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
