// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package native_widgets.proxies;

public class Entity extends system.proxies.User
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Native_Widgets.Entity";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		String("String"),
		Bool("Bool"),
		BoolTrue("BoolTrue"),
		Datetime("Datetime"),
		Enums("Enums"),
		Decimal("Decimal"),
		Name("Name"),
		Password("Password"),
		LastLogin("LastLogin"),
		Blocked("Blocked"),
		Active("Active"),
		FailedLogins("FailedLogins"),
		WebServiceUser("WebServiceUser"),
		IsAnonymous("IsAnonymous"),
		Entity_User("Native_Widgets.Entity_User"),
		UserRoles("System.UserRoles"),
		User_Language("System.User_Language"),
		User_TimeZone("System.User_TimeZone");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Entity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Native_Widgets.Entity"));
	}

	protected Entity(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject entityMendixObject)
	{
		super(context, entityMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("Native_Widgets.Entity", entityMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Native_Widgets.Entity");
	}

	/**
	 * @deprecated Use 'Entity.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static native_widgets.proxies.Entity initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return native_widgets.proxies.Entity.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static native_widgets.proxies.Entity initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new native_widgets.proxies.Entity(context, mendixObject);
	}

	public static native_widgets.proxies.Entity load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return native_widgets.proxies.Entity.initialize(context, mendixObject);
	}

	public static java.util.List<native_widgets.proxies.Entity> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<native_widgets.proxies.Entity> result = new java.util.ArrayList<native_widgets.proxies.Entity>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//Native_Widgets.Entity" + xpathConstraint))
			result.add(native_widgets.proxies.Entity.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of String
	 */
	public final java.lang.String getString()
	{
		return getString(getContext());
	}

	/**
	 * @param context
	 * @return value of String
	 */
	public final java.lang.String getString(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.String.toString());
	}

	/**
	 * Set value of String
	 * @param string
	 */
	public final void setString(java.lang.String string)
	{
		setString(getContext(), string);
	}

	/**
	 * Set value of String
	 * @param context
	 * @param string
	 */
	public final void setString(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String string)
	{
		getMendixObject().setValue(context, MemberNames.String.toString(), string);
	}

	/**
	 * @return value of Bool
	 */
	public final java.lang.Boolean getBool()
	{
		return getBool(getContext());
	}

	/**
	 * @param context
	 * @return value of Bool
	 */
	public final java.lang.Boolean getBool(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Bool.toString());
	}

	/**
	 * Set value of Bool
	 * @param bool
	 */
	public final void setBool(java.lang.Boolean bool)
	{
		setBool(getContext(), bool);
	}

	/**
	 * Set value of Bool
	 * @param context
	 * @param bool
	 */
	public final void setBool(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean bool)
	{
		getMendixObject().setValue(context, MemberNames.Bool.toString(), bool);
	}

	/**
	 * @return value of BoolTrue
	 */
	public final java.lang.Boolean getBoolTrue()
	{
		return getBoolTrue(getContext());
	}

	/**
	 * @param context
	 * @return value of BoolTrue
	 */
	public final java.lang.Boolean getBoolTrue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.BoolTrue.toString());
	}

	/**
	 * Set value of BoolTrue
	 * @param booltrue
	 */
	public final void setBoolTrue(java.lang.Boolean booltrue)
	{
		setBoolTrue(getContext(), booltrue);
	}

	/**
	 * Set value of BoolTrue
	 * @param context
	 * @param booltrue
	 */
	public final void setBoolTrue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean booltrue)
	{
		getMendixObject().setValue(context, MemberNames.BoolTrue.toString(), booltrue);
	}

	/**
	 * @return value of Datetime
	 */
	public final java.util.Date getDatetime()
	{
		return getDatetime(getContext());
	}

	/**
	 * @param context
	 * @return value of Datetime
	 */
	public final java.util.Date getDatetime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Datetime.toString());
	}

	/**
	 * Set value of Datetime
	 * @param datetime
	 */
	public final void setDatetime(java.util.Date datetime)
	{
		setDatetime(getContext(), datetime);
	}

	/**
	 * Set value of Datetime
	 * @param context
	 * @param datetime
	 */
	public final void setDatetime(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date datetime)
	{
		getMendixObject().setValue(context, MemberNames.Datetime.toString(), datetime);
	}

	/**
	 * Set value of Enums
	 * @param enums
	 */
	public final native_widgets.proxies.Enumeration getEnums()
	{
		return getEnums(getContext());
	}

	/**
	 * @param context
	 * @return value of Enums
	 */
	public final native_widgets.proxies.Enumeration getEnums(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Enums.toString());
		if (obj == null)
			return null;

		return native_widgets.proxies.Enumeration.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Enums
	 * @param enums
	 */
	public final void setEnums(native_widgets.proxies.Enumeration enums)
	{
		setEnums(getContext(), enums);
	}

	/**
	 * Set value of Enums
	 * @param context
	 * @param enums
	 */
	public final void setEnums(com.mendix.systemwideinterfaces.core.IContext context, native_widgets.proxies.Enumeration enums)
	{
		if (enums != null)
			getMendixObject().setValue(context, MemberNames.Enums.toString(), enums.toString());
		else
			getMendixObject().setValue(context, MemberNames.Enums.toString(), null);
	}

	/**
	 * @return value of Decimal
	 */
	public final java.math.BigDecimal getDecimal()
	{
		return getDecimal(getContext());
	}

	/**
	 * @param context
	 * @return value of Decimal
	 */
	public final java.math.BigDecimal getDecimal(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Decimal.toString());
	}

	/**
	 * Set value of Decimal
	 * @param decimal
	 */
	public final void setDecimal(java.math.BigDecimal decimal)
	{
		setDecimal(getContext(), decimal);
	}

	/**
	 * Set value of Decimal
	 * @param context
	 * @param decimal
	 */
	public final void setDecimal(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal decimal)
	{
		getMendixObject().setValue(context, MemberNames.Decimal.toString(), decimal);
	}

	/**
	 * @return value of Entity_User
	 */
	public final native_widgets.proxies.User getEntity_User() throws com.mendix.core.CoreException
	{
		return getEntity_User(getContext());
	}

	/**
	 * @param context
	 * @return value of Entity_User
	 */
	public final native_widgets.proxies.User getEntity_User(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		native_widgets.proxies.User result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Entity_User.toString());
		if (identifier != null)
			result = native_widgets.proxies.User.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Entity_User
	 * @param entity_user
	 */
	public final void setEntity_User(native_widgets.proxies.User entity_user)
	{
		setEntity_User(getContext(), entity_user);
	}

	/**
	 * Set value of Entity_User
	 * @param context
	 * @param entity_user
	 */
	public final void setEntity_User(com.mendix.systemwideinterfaces.core.IContext context, native_widgets.proxies.User entity_user)
	{
		if (entity_user == null)
			getMendixObject().setValue(context, MemberNames.Entity_User.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Entity_User.toString(), entity_user.getMendixObject().getId());
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final native_widgets.proxies.Entity that = (native_widgets.proxies.Entity) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Native_Widgets.Entity";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
