// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package native_widgets.proxies;

public class Maps
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject mapsMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Native_Widgets.Maps";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		MarkerTitle("MarkerTitle"),
		MarkerDescription("MarkerDescription"),
		MarkerLatitude("MarkerLatitude"),
		MarkerLongitude("MarkerLongitude"),
		RegionLatitude("RegionLatitude"),
		RegionLongitude("RegionLongitude"),
		RegionLatitudeDelta("RegionLatitudeDelta"),
		RegionLongitudeDelta("RegionLongitudeDelta"),
		DevMode("DevMode");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Maps(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Native_Widgets.Maps"));
	}

	protected Maps(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mapsMendixObject)
	{
		if (mapsMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Native_Widgets.Maps", mapsMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Native_Widgets.Maps");

		this.mapsMendixObject = mapsMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Maps.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static native_widgets.proxies.Maps initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return native_widgets.proxies.Maps.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static native_widgets.proxies.Maps initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new native_widgets.proxies.Maps(context, mendixObject);
	}

	public static native_widgets.proxies.Maps load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return native_widgets.proxies.Maps.initialize(context, mendixObject);
	}

	public static java.util.List<native_widgets.proxies.Maps> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<native_widgets.proxies.Maps> result = new java.util.ArrayList<native_widgets.proxies.Maps>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//Native_Widgets.Maps" + xpathConstraint))
			result.add(native_widgets.proxies.Maps.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of MarkerTitle
	 */
	public final java.lang.String getMarkerTitle()
	{
		return getMarkerTitle(getContext());
	}

	/**
	 * @param context
	 * @return value of MarkerTitle
	 */
	public final java.lang.String getMarkerTitle(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MarkerTitle.toString());
	}

	/**
	 * Set value of MarkerTitle
	 * @param markertitle
	 */
	public final void setMarkerTitle(java.lang.String markertitle)
	{
		setMarkerTitle(getContext(), markertitle);
	}

	/**
	 * Set value of MarkerTitle
	 * @param context
	 * @param markertitle
	 */
	public final void setMarkerTitle(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String markertitle)
	{
		getMendixObject().setValue(context, MemberNames.MarkerTitle.toString(), markertitle);
	}

	/**
	 * @return value of MarkerDescription
	 */
	public final java.lang.String getMarkerDescription()
	{
		return getMarkerDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of MarkerDescription
	 */
	public final java.lang.String getMarkerDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MarkerDescription.toString());
	}

	/**
	 * Set value of MarkerDescription
	 * @param markerdescription
	 */
	public final void setMarkerDescription(java.lang.String markerdescription)
	{
		setMarkerDescription(getContext(), markerdescription);
	}

	/**
	 * Set value of MarkerDescription
	 * @param context
	 * @param markerdescription
	 */
	public final void setMarkerDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String markerdescription)
	{
		getMendixObject().setValue(context, MemberNames.MarkerDescription.toString(), markerdescription);
	}

	/**
	 * @return value of MarkerLatitude
	 */
	public final java.math.BigDecimal getMarkerLatitude()
	{
		return getMarkerLatitude(getContext());
	}

	/**
	 * @param context
	 * @return value of MarkerLatitude
	 */
	public final java.math.BigDecimal getMarkerLatitude(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.MarkerLatitude.toString());
	}

	/**
	 * Set value of MarkerLatitude
	 * @param markerlatitude
	 */
	public final void setMarkerLatitude(java.math.BigDecimal markerlatitude)
	{
		setMarkerLatitude(getContext(), markerlatitude);
	}

	/**
	 * Set value of MarkerLatitude
	 * @param context
	 * @param markerlatitude
	 */
	public final void setMarkerLatitude(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal markerlatitude)
	{
		getMendixObject().setValue(context, MemberNames.MarkerLatitude.toString(), markerlatitude);
	}

	/**
	 * @return value of MarkerLongitude
	 */
	public final java.math.BigDecimal getMarkerLongitude()
	{
		return getMarkerLongitude(getContext());
	}

	/**
	 * @param context
	 * @return value of MarkerLongitude
	 */
	public final java.math.BigDecimal getMarkerLongitude(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.MarkerLongitude.toString());
	}

	/**
	 * Set value of MarkerLongitude
	 * @param markerlongitude
	 */
	public final void setMarkerLongitude(java.math.BigDecimal markerlongitude)
	{
		setMarkerLongitude(getContext(), markerlongitude);
	}

	/**
	 * Set value of MarkerLongitude
	 * @param context
	 * @param markerlongitude
	 */
	public final void setMarkerLongitude(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal markerlongitude)
	{
		getMendixObject().setValue(context, MemberNames.MarkerLongitude.toString(), markerlongitude);
	}

	/**
	 * @return value of RegionLatitude
	 */
	public final java.math.BigDecimal getRegionLatitude()
	{
		return getRegionLatitude(getContext());
	}

	/**
	 * @param context
	 * @return value of RegionLatitude
	 */
	public final java.math.BigDecimal getRegionLatitude(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.RegionLatitude.toString());
	}

	/**
	 * Set value of RegionLatitude
	 * @param regionlatitude
	 */
	public final void setRegionLatitude(java.math.BigDecimal regionlatitude)
	{
		setRegionLatitude(getContext(), regionlatitude);
	}

	/**
	 * Set value of RegionLatitude
	 * @param context
	 * @param regionlatitude
	 */
	public final void setRegionLatitude(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal regionlatitude)
	{
		getMendixObject().setValue(context, MemberNames.RegionLatitude.toString(), regionlatitude);
	}

	/**
	 * @return value of RegionLongitude
	 */
	public final java.math.BigDecimal getRegionLongitude()
	{
		return getRegionLongitude(getContext());
	}

	/**
	 * @param context
	 * @return value of RegionLongitude
	 */
	public final java.math.BigDecimal getRegionLongitude(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.RegionLongitude.toString());
	}

	/**
	 * Set value of RegionLongitude
	 * @param regionlongitude
	 */
	public final void setRegionLongitude(java.math.BigDecimal regionlongitude)
	{
		setRegionLongitude(getContext(), regionlongitude);
	}

	/**
	 * Set value of RegionLongitude
	 * @param context
	 * @param regionlongitude
	 */
	public final void setRegionLongitude(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal regionlongitude)
	{
		getMendixObject().setValue(context, MemberNames.RegionLongitude.toString(), regionlongitude);
	}

	/**
	 * @return value of RegionLatitudeDelta
	 */
	public final java.math.BigDecimal getRegionLatitudeDelta()
	{
		return getRegionLatitudeDelta(getContext());
	}

	/**
	 * @param context
	 * @return value of RegionLatitudeDelta
	 */
	public final java.math.BigDecimal getRegionLatitudeDelta(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.RegionLatitudeDelta.toString());
	}

	/**
	 * Set value of RegionLatitudeDelta
	 * @param regionlatitudedelta
	 */
	public final void setRegionLatitudeDelta(java.math.BigDecimal regionlatitudedelta)
	{
		setRegionLatitudeDelta(getContext(), regionlatitudedelta);
	}

	/**
	 * Set value of RegionLatitudeDelta
	 * @param context
	 * @param regionlatitudedelta
	 */
	public final void setRegionLatitudeDelta(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal regionlatitudedelta)
	{
		getMendixObject().setValue(context, MemberNames.RegionLatitudeDelta.toString(), regionlatitudedelta);
	}

	/**
	 * @return value of RegionLongitudeDelta
	 */
	public final java.math.BigDecimal getRegionLongitudeDelta()
	{
		return getRegionLongitudeDelta(getContext());
	}

	/**
	 * @param context
	 * @return value of RegionLongitudeDelta
	 */
	public final java.math.BigDecimal getRegionLongitudeDelta(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.RegionLongitudeDelta.toString());
	}

	/**
	 * Set value of RegionLongitudeDelta
	 * @param regionlongitudedelta
	 */
	public final void setRegionLongitudeDelta(java.math.BigDecimal regionlongitudedelta)
	{
		setRegionLongitudeDelta(getContext(), regionlongitudedelta);
	}

	/**
	 * Set value of RegionLongitudeDelta
	 * @param context
	 * @param regionlongitudedelta
	 */
	public final void setRegionLongitudeDelta(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal regionlongitudedelta)
	{
		getMendixObject().setValue(context, MemberNames.RegionLongitudeDelta.toString(), regionlongitudedelta);
	}

	/**
	 * @return value of DevMode
	 */
	public final java.lang.Boolean getDevMode()
	{
		return getDevMode(getContext());
	}

	/**
	 * @param context
	 * @return value of DevMode
	 */
	public final java.lang.Boolean getDevMode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.DevMode.toString());
	}

	/**
	 * Set value of DevMode
	 * @param devmode
	 */
	public final void setDevMode(java.lang.Boolean devmode)
	{
		setDevMode(getContext(), devmode);
	}

	/**
	 * Set value of DevMode
	 * @param context
	 * @param devmode
	 */
	public final void setDevMode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean devmode)
	{
		getMendixObject().setValue(context, MemberNames.DevMode.toString(), devmode);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return mapsMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final native_widgets.proxies.Maps that = (native_widgets.proxies.Maps) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Native_Widgets.Maps";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
