// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package native_pagetemplates.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;

public class Microflows
{
	// These are the microflows for the Native_PageTemplates module
	public static void aCT_GenericObject_DeleteAll(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("Native_PageTemplates.ACT_GenericObject_DeleteAll").withParams(params).execute(context);
	}
	public static void aCT_Images_DeleteAll(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("Native_PageTemplates.ACT_Images_DeleteAll").withParams(params).execute(context);
	}
	public static void aCT_People_DeleteAll(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("Native_PageTemplates.ACT_People_DeleteAll").withParams(params).execute(context);
	}
	public static void aCT_ShowPage_GenericObject_New(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("Native_PageTemplates.ACT_ShowPage_GenericObject_New").withParams(params).execute(context);
	}
	public static void aCT_ShowPage_Images_New(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("Native_PageTemplates.ACT_ShowPage_Images_New").withParams(params).execute(context);
	}
	public static void aCT_ShowPage_Images_Rounded_NewEdit(IContext context, native_pagetemplates.proxies.Images _images)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Images", _images == null ? null : _images.getMendixObject());
		Core.microflowCall("Native_PageTemplates.ACT_ShowPage_Images_Rounded_NewEdit").withParams(params).execute(context);
	}
	public static void aCT_ShowPage_People_New(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("Native_PageTemplates.ACT_ShowPage_People_New").withParams(params).execute(context);
	}
}