// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package native_pagetemplates.proxies;

public class BottomSheet
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject bottomSheetMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Native_PageTemplates.BottomSheet";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		state("state"),
		expanded("expanded");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public BottomSheet(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Native_PageTemplates.BottomSheet"));
	}

	protected BottomSheet(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject bottomSheetMendixObject)
	{
		if (bottomSheetMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Native_PageTemplates.BottomSheet", bottomSheetMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Native_PageTemplates.BottomSheet");

		this.bottomSheetMendixObject = bottomSheetMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'BottomSheet.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static native_pagetemplates.proxies.BottomSheet initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return native_pagetemplates.proxies.BottomSheet.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static native_pagetemplates.proxies.BottomSheet initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new native_pagetemplates.proxies.BottomSheet(context, mendixObject);
	}

	public static native_pagetemplates.proxies.BottomSheet load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return native_pagetemplates.proxies.BottomSheet.initialize(context, mendixObject);
	}

	public static java.util.List<native_pagetemplates.proxies.BottomSheet> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<native_pagetemplates.proxies.BottomSheet> result = new java.util.ArrayList<native_pagetemplates.proxies.BottomSheet>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//Native_PageTemplates.BottomSheet" + xpathConstraint))
			result.add(native_pagetemplates.proxies.BottomSheet.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of state
	 */
	public final java.lang.Boolean getstate()
	{
		return getstate(getContext());
	}

	/**
	 * @param context
	 * @return value of state
	 */
	public final java.lang.Boolean getstate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.state.toString());
	}

	/**
	 * Set value of state
	 * @param state
	 */
	public final void setstate(java.lang.Boolean state)
	{
		setstate(getContext(), state);
	}

	/**
	 * Set value of state
	 * @param context
	 * @param state
	 */
	public final void setstate(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean state)
	{
		getMendixObject().setValue(context, MemberNames.state.toString(), state);
	}

	/**
	 * @return value of expanded
	 */
	public final java.lang.Boolean getexpanded()
	{
		return getexpanded(getContext());
	}

	/**
	 * @param context
	 * @return value of expanded
	 */
	public final java.lang.Boolean getexpanded(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.expanded.toString());
	}

	/**
	 * Set value of expanded
	 * @param expanded
	 */
	public final void setexpanded(java.lang.Boolean expanded)
	{
		setexpanded(getContext(), expanded);
	}

	/**
	 * Set value of expanded
	 * @param context
	 * @param expanded
	 */
	public final void setexpanded(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean expanded)
	{
		getMendixObject().setValue(context, MemberNames.expanded.toString(), expanded);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return bottomSheetMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final native_pagetemplates.proxies.BottomSheet that = (native_pagetemplates.proxies.BottomSheet) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Native_PageTemplates.BottomSheet";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
