// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package native_pagetemplates.proxies;

public class GenericObject
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject genericObjectMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Native_PageTemplates.GenericObject";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Autonumber("Autonumber"),
		Binary("Binary"),
		String("String"),
		Boolean_("Boolean_"),
		DateTime("DateTime"),
		Decimal("Decimal"),
		Enumeration("Enumeration"),
		HashedString("HashedString"),
		Integer("Integer"),
		Float_("Float_"),
		Long_("Long_"),
		Currency("Currency"),
		Location("Location"),
		Title("Title");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public GenericObject(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Native_PageTemplates.GenericObject"));
	}

	protected GenericObject(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject genericObjectMendixObject)
	{
		if (genericObjectMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Native_PageTemplates.GenericObject", genericObjectMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Native_PageTemplates.GenericObject");

		this.genericObjectMendixObject = genericObjectMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'GenericObject.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static native_pagetemplates.proxies.GenericObject initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return native_pagetemplates.proxies.GenericObject.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static native_pagetemplates.proxies.GenericObject initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new native_pagetemplates.proxies.GenericObject(context, mendixObject);
	}

	public static native_pagetemplates.proxies.GenericObject load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return native_pagetemplates.proxies.GenericObject.initialize(context, mendixObject);
	}

	public static java.util.List<native_pagetemplates.proxies.GenericObject> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<native_pagetemplates.proxies.GenericObject> result = new java.util.ArrayList<native_pagetemplates.proxies.GenericObject>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//Native_PageTemplates.GenericObject" + xpathConstraint))
			result.add(native_pagetemplates.proxies.GenericObject.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Autonumber
	 */
	public final java.lang.Long getAutonumber()
	{
		return getAutonumber(getContext());
	}

	/**
	 * @param context
	 * @return value of Autonumber
	 */
	public final java.lang.Long getAutonumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.Autonumber.toString());
	}

	/**
	 * Set value of Autonumber
	 * @param autonumber
	 */
	public final void setAutonumber(java.lang.Long autonumber)
	{
		setAutonumber(getContext(), autonumber);
	}

	/**
	 * Set value of Autonumber
	 * @param context
	 * @param autonumber
	 */
	public final void setAutonumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long autonumber)
	{
		getMendixObject().setValue(context, MemberNames.Autonumber.toString(), autonumber);
	}

	/**
	  * The contents of the binary field will be written to the output stream.
	  * The output stream will be closed at the end.
	  *
	  * @param context
	  * @param outputStream
	  */
	public final void getBinary(com.mendix.systemwideinterfaces.core.IContext context, java.io.OutputStream outputStream)
	{
		com.mendix.core.objectmanagement.member.MendixBinary binary = (com.mendix.core.objectmanagement.member.MendixBinary) getMendixObject().getMember(context, MemberNames.Binary.toString());
		binary.retrieveValue(context, outputStream);
	}

	/**
	  * Stores the bytes from the given InputStream.
	  *
	  * Please note that the input stream will be immediately sent to the data store,
	  * whether you commit the Mendix object or not.
	  *
	  * @param context
	  * @param inputStream
	  * @param length the number of bytes in the stream
	  */
	public final void setBinary(com.mendix.systemwideinterfaces.core.IContext context, java.io.InputStream inputStream, long length)
	{
		if (getMendixObject().getState() == com.mendix.systemwideinterfaces.core.IMendixObject.ObjectState.INSTANTIATED)
			try { commit(); } catch (com.mendix.core.CoreException ex) { }
		com.mendix.core.objectmanagement.member.MendixBinary binary = (com.mendix.core.objectmanagement.member.MendixBinary) getMendixObject().getMember(context, MemberNames.Binary.toString());
		binary.storeValue(context, inputStream, length);
	}

	/**
	 * @return value of String
	 */
	public final java.lang.String getString()
	{
		return getString(getContext());
	}

	/**
	 * @param context
	 * @return value of String
	 */
	public final java.lang.String getString(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.String.toString());
	}

	/**
	 * Set value of String
	 * @param string
	 */
	public final void setString(java.lang.String string)
	{
		setString(getContext(), string);
	}

	/**
	 * Set value of String
	 * @param context
	 * @param string
	 */
	public final void setString(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String string)
	{
		getMendixObject().setValue(context, MemberNames.String.toString(), string);
	}

	/**
	 * @return value of Boolean_
	 */
	public final java.lang.Boolean getBoolean_()
	{
		return getBoolean_(getContext());
	}

	/**
	 * @param context
	 * @return value of Boolean_
	 */
	public final java.lang.Boolean getBoolean_(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Boolean_.toString());
	}

	/**
	 * Set value of Boolean_
	 * @param boolean_
	 */
	public final void setBoolean_(java.lang.Boolean boolean_)
	{
		setBoolean_(getContext(), boolean_);
	}

	/**
	 * Set value of Boolean_
	 * @param context
	 * @param boolean_
	 */
	public final void setBoolean_(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean boolean_)
	{
		getMendixObject().setValue(context, MemberNames.Boolean_.toString(), boolean_);
	}

	/**
	 * @return value of DateTime
	 */
	public final java.util.Date getDateTime()
	{
		return getDateTime(getContext());
	}

	/**
	 * @param context
	 * @return value of DateTime
	 */
	public final java.util.Date getDateTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.DateTime.toString());
	}

	/**
	 * Set value of DateTime
	 * @param datetime
	 */
	public final void setDateTime(java.util.Date datetime)
	{
		setDateTime(getContext(), datetime);
	}

	/**
	 * Set value of DateTime
	 * @param context
	 * @param datetime
	 */
	public final void setDateTime(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date datetime)
	{
		getMendixObject().setValue(context, MemberNames.DateTime.toString(), datetime);
	}

	/**
	 * @return value of Decimal
	 */
	public final java.math.BigDecimal getDecimal()
	{
		return getDecimal(getContext());
	}

	/**
	 * @param context
	 * @return value of Decimal
	 */
	public final java.math.BigDecimal getDecimal(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Decimal.toString());
	}

	/**
	 * Set value of Decimal
	 * @param decimal
	 */
	public final void setDecimal(java.math.BigDecimal decimal)
	{
		setDecimal(getContext(), decimal);
	}

	/**
	 * Set value of Decimal
	 * @param context
	 * @param decimal
	 */
	public final void setDecimal(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal decimal)
	{
		getMendixObject().setValue(context, MemberNames.Decimal.toString(), decimal);
	}

	/**
	 * Set value of Enumeration
	 * @param enumeration
	 */
	public final atlas_ui_data.proxies.DefaultEnumeration getEnumeration()
	{
		return getEnumeration(getContext());
	}

	/**
	 * @param context
	 * @return value of Enumeration
	 */
	public final atlas_ui_data.proxies.DefaultEnumeration getEnumeration(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Enumeration.toString());
		if (obj == null)
			return null;

		return atlas_ui_data.proxies.DefaultEnumeration.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Enumeration
	 * @param enumeration
	 */
	public final void setEnumeration(atlas_ui_data.proxies.DefaultEnumeration enumeration)
	{
		setEnumeration(getContext(), enumeration);
	}

	/**
	 * Set value of Enumeration
	 * @param context
	 * @param enumeration
	 */
	public final void setEnumeration(com.mendix.systemwideinterfaces.core.IContext context, atlas_ui_data.proxies.DefaultEnumeration enumeration)
	{
		if (enumeration != null)
			getMendixObject().setValue(context, MemberNames.Enumeration.toString(), enumeration.toString());
		else
			getMendixObject().setValue(context, MemberNames.Enumeration.toString(), null);
	}

	/**
	 * Set value of HashedString
	 * @param hashedstring
	 */
	public final void setHashedString(java.lang.String hashedstring)
	{
		setHashedString(getContext(), hashedstring);
	}

	/**
	 * Set value of HashedString
	 * @param context
	 * @param hashedstring
	 */
	public final void setHashedString(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String hashedstring)
	{
		getMendixObject().setValue(context, MemberNames.HashedString.toString(), hashedstring);
	}

	/**
	 * @return value of Integer
	 */
	public final java.lang.Integer getInteger()
	{
		return getInteger(getContext());
	}

	/**
	 * @param context
	 * @return value of Integer
	 */
	public final java.lang.Integer getInteger(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Integer.toString());
	}

	/**
	 * Set value of Integer
	 * @param integer
	 */
	public final void setInteger(java.lang.Integer integer)
	{
		setInteger(getContext(), integer);
	}

	/**
	 * Set value of Integer
	 * @param context
	 * @param integer
	 */
	public final void setInteger(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer integer)
	{
		getMendixObject().setValue(context, MemberNames.Integer.toString(), integer);
	}

	/**
	 * @return value of Float_
	 */
	public final java.math.BigDecimal getFloat_()
	{
		return getFloat_(getContext());
	}

	/**
	 * @param context
	 * @return value of Float_
	 */
	public final java.math.BigDecimal getFloat_(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Float_.toString());
	}

	/**
	 * Set value of Float_
	 * @param float_
	 */
	public final void setFloat_(java.math.BigDecimal float_)
	{
		setFloat_(getContext(), float_);
	}

	/**
	 * Set value of Float_
	 * @param context
	 * @param float_
	 */
	public final void setFloat_(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal float_)
	{
		getMendixObject().setValue(context, MemberNames.Float_.toString(), float_);
	}

	/**
	 * @return value of Long_
	 */
	public final java.lang.Long getLong_()
	{
		return getLong_(getContext());
	}

	/**
	 * @param context
	 * @return value of Long_
	 */
	public final java.lang.Long getLong_(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.Long_.toString());
	}

	/**
	 * Set value of Long_
	 * @param long_
	 */
	public final void setLong_(java.lang.Long long_)
	{
		setLong_(getContext(), long_);
	}

	/**
	 * Set value of Long_
	 * @param context
	 * @param long_
	 */
	public final void setLong_(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long long_)
	{
		getMendixObject().setValue(context, MemberNames.Long_.toString(), long_);
	}

	/**
	 * @return value of Currency
	 */
	public final java.math.BigDecimal getCurrency()
	{
		return getCurrency(getContext());
	}

	/**
	 * @param context
	 * @return value of Currency
	 */
	public final java.math.BigDecimal getCurrency(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Currency.toString());
	}

	/**
	 * Set value of Currency
	 * @param currency
	 */
	public final void setCurrency(java.math.BigDecimal currency)
	{
		setCurrency(getContext(), currency);
	}

	/**
	 * Set value of Currency
	 * @param context
	 * @param currency
	 */
	public final void setCurrency(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal currency)
	{
		getMendixObject().setValue(context, MemberNames.Currency.toString(), currency);
	}

	/**
	 * @return value of Location
	 */
	public final java.lang.String getLocation()
	{
		return getLocation(getContext());
	}

	/**
	 * @param context
	 * @return value of Location
	 */
	public final java.lang.String getLocation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Location.toString());
	}

	/**
	 * Set value of Location
	 * @param location
	 */
	public final void setLocation(java.lang.String location)
	{
		setLocation(getContext(), location);
	}

	/**
	 * Set value of Location
	 * @param context
	 * @param location
	 */
	public final void setLocation(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String location)
	{
		getMendixObject().setValue(context, MemberNames.Location.toString(), location);
	}

	/**
	 * @return value of Title
	 */
	public final java.lang.String getTitle()
	{
		return getTitle(getContext());
	}

	/**
	 * @param context
	 * @return value of Title
	 */
	public final java.lang.String getTitle(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Title.toString());
	}

	/**
	 * Set value of Title
	 * @param title
	 */
	public final void setTitle(java.lang.String title)
	{
		setTitle(getContext(), title);
	}

	/**
	 * Set value of Title
	 * @param context
	 * @param title
	 */
	public final void setTitle(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String title)
	{
		getMendixObject().setValue(context, MemberNames.Title.toString(), title);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return genericObjectMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final native_pagetemplates.proxies.GenericObject that = (native_pagetemplates.proxies.GenericObject) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Native_PageTemplates.GenericObject";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
