// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package native_pagetemplates.proxies;

public class Images_Rounded_1x extends system.proxies.Image
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Native_PageTemplates.Images_Rounded_1x";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		PublicThumbnailPath("PublicThumbnailPath"),
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Size("Size"),
		Images_Images_Rounded_1x("Native_PageTemplates.Images_Images_Rounded_1x");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Images_Rounded_1x(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Native_PageTemplates.Images_Rounded_1x"));
	}

	protected Images_Rounded_1x(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject images_Rounded_1xMendixObject)
	{
		super(context, images_Rounded_1xMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("Native_PageTemplates.Images_Rounded_1x", images_Rounded_1xMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Native_PageTemplates.Images_Rounded_1x");
	}

	/**
	 * @deprecated Use 'Images_Rounded_1x.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static native_pagetemplates.proxies.Images_Rounded_1x initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return native_pagetemplates.proxies.Images_Rounded_1x.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static native_pagetemplates.proxies.Images_Rounded_1x initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new native_pagetemplates.proxies.Images_Rounded_1x(context, mendixObject);
	}

	public static native_pagetemplates.proxies.Images_Rounded_1x load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return native_pagetemplates.proxies.Images_Rounded_1x.initialize(context, mendixObject);
	}

	public static java.util.List<native_pagetemplates.proxies.Images_Rounded_1x> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<native_pagetemplates.proxies.Images_Rounded_1x> result = new java.util.ArrayList<native_pagetemplates.proxies.Images_Rounded_1x>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//Native_PageTemplates.Images_Rounded_1x" + xpathConstraint))
			result.add(native_pagetemplates.proxies.Images_Rounded_1x.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of Images_Images_Rounded_1x
	 */
	public final native_pagetemplates.proxies.Images getImages_Images_Rounded_1x() throws com.mendix.core.CoreException
	{
		return getImages_Images_Rounded_1x(getContext());
	}

	/**
	 * @param context
	 * @return value of Images_Images_Rounded_1x
	 */
	public final native_pagetemplates.proxies.Images getImages_Images_Rounded_1x(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		native_pagetemplates.proxies.Images result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Images_Images_Rounded_1x.toString());
		if (identifier != null)
			result = native_pagetemplates.proxies.Images.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Images_Images_Rounded_1x
	 * @param images_images_rounded_1x
	 */
	public final void setImages_Images_Rounded_1x(native_pagetemplates.proxies.Images images_images_rounded_1x)
	{
		setImages_Images_Rounded_1x(getContext(), images_images_rounded_1x);
	}

	/**
	 * Set value of Images_Images_Rounded_1x
	 * @param context
	 * @param images_images_rounded_1x
	 */
	public final void setImages_Images_Rounded_1x(com.mendix.systemwideinterfaces.core.IContext context, native_pagetemplates.proxies.Images images_images_rounded_1x)
	{
		if (images_images_rounded_1x == null)
			getMendixObject().setValue(context, MemberNames.Images_Images_Rounded_1x.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Images_Images_Rounded_1x.toString(), images_images_rounded_1x.getMendixObject().getId());
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final native_pagetemplates.proxies.Images_Rounded_1x that = (native_pagetemplates.proxies.Images_Rounded_1x) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Native_PageTemplates.Images_Rounded_1x";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
