// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package rest.proxies;

public class JsonObject
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject jsonObjectMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Rest.JsonObject";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		XValueEnum("XValueEnum"),
		YValue("YValue"),
		XCoordinate("XCoordinate"),
		YCoordinate("YCoordinate"),
		bubbleSize("bubbleSize"),
		name("name"),
		value("value"),
		X("X"),
		Y("Y"),
		Z("Z"),
		JsonObject_Root("Rest.JsonObject_Root"),
		JsonObject_RespondeCollection("Rest.JsonObject_RespondeCollection");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public JsonObject(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Rest.JsonObject"));
	}

	protected JsonObject(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject jsonObjectMendixObject)
	{
		if (jsonObjectMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Rest.JsonObject", jsonObjectMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Rest.JsonObject");

		this.jsonObjectMendixObject = jsonObjectMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'JsonObject.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static rest.proxies.JsonObject initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return rest.proxies.JsonObject.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static rest.proxies.JsonObject initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new rest.proxies.JsonObject(context, mendixObject);
	}

	public static rest.proxies.JsonObject load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return rest.proxies.JsonObject.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of XValueEnum
	 */
	public final java.lang.String getXValueEnum()
	{
		return getXValueEnum(getContext());
	}

	/**
	 * @param context
	 * @return value of XValueEnum
	 */
	public final java.lang.String getXValueEnum(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.XValueEnum.toString());
	}

	/**
	 * Set value of XValueEnum
	 * @param xvalueenum
	 */
	public final void setXValueEnum(java.lang.String xvalueenum)
	{
		setXValueEnum(getContext(), xvalueenum);
	}

	/**
	 * Set value of XValueEnum
	 * @param context
	 * @param xvalueenum
	 */
	public final void setXValueEnum(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xvalueenum)
	{
		getMendixObject().setValue(context, MemberNames.XValueEnum.toString(), xvalueenum);
	}

	/**
	 * @return value of YValue
	 */
	public final java.lang.String getYValue()
	{
		return getYValue(getContext());
	}

	/**
	 * @param context
	 * @return value of YValue
	 */
	public final java.lang.String getYValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.YValue.toString());
	}

	/**
	 * Set value of YValue
	 * @param yvalue
	 */
	public final void setYValue(java.lang.String yvalue)
	{
		setYValue(getContext(), yvalue);
	}

	/**
	 * Set value of YValue
	 * @param context
	 * @param yvalue
	 */
	public final void setYValue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String yvalue)
	{
		getMendixObject().setValue(context, MemberNames.YValue.toString(), yvalue);
	}

	/**
	 * @return value of XCoordinate
	 */
	public final java.lang.Integer getXCoordinate()
	{
		return getXCoordinate(getContext());
	}

	/**
	 * @param context
	 * @return value of XCoordinate
	 */
	public final java.lang.Integer getXCoordinate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.XCoordinate.toString());
	}

	/**
	 * Set value of XCoordinate
	 * @param xcoordinate
	 */
	public final void setXCoordinate(java.lang.Integer xcoordinate)
	{
		setXCoordinate(getContext(), xcoordinate);
	}

	/**
	 * Set value of XCoordinate
	 * @param context
	 * @param xcoordinate
	 */
	public final void setXCoordinate(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer xcoordinate)
	{
		getMendixObject().setValue(context, MemberNames.XCoordinate.toString(), xcoordinate);
	}

	/**
	 * @return value of YCoordinate
	 */
	public final java.lang.Integer getYCoordinate()
	{
		return getYCoordinate(getContext());
	}

	/**
	 * @param context
	 * @return value of YCoordinate
	 */
	public final java.lang.Integer getYCoordinate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.YCoordinate.toString());
	}

	/**
	 * Set value of YCoordinate
	 * @param ycoordinate
	 */
	public final void setYCoordinate(java.lang.Integer ycoordinate)
	{
		setYCoordinate(getContext(), ycoordinate);
	}

	/**
	 * Set value of YCoordinate
	 * @param context
	 * @param ycoordinate
	 */
	public final void setYCoordinate(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer ycoordinate)
	{
		getMendixObject().setValue(context, MemberNames.YCoordinate.toString(), ycoordinate);
	}

	/**
	 * @return value of bubbleSize
	 */
	public final java.lang.Integer getbubbleSize()
	{
		return getbubbleSize(getContext());
	}

	/**
	 * @param context
	 * @return value of bubbleSize
	 */
	public final java.lang.Integer getbubbleSize(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.bubbleSize.toString());
	}

	/**
	 * Set value of bubbleSize
	 * @param bubblesize
	 */
	public final void setbubbleSize(java.lang.Integer bubblesize)
	{
		setbubbleSize(getContext(), bubblesize);
	}

	/**
	 * Set value of bubbleSize
	 * @param context
	 * @param bubblesize
	 */
	public final void setbubbleSize(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer bubblesize)
	{
		getMendixObject().setValue(context, MemberNames.bubbleSize.toString(), bubblesize);
	}

	/**
	 * @return value of name
	 */
	public final java.lang.String getname()
	{
		return getname(getContext());
	}

	/**
	 * @param context
	 * @return value of name
	 */
	public final java.lang.String getname(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.name.toString());
	}

	/**
	 * Set value of name
	 * @param name
	 */
	public final void setname(java.lang.String name)
	{
		setname(getContext(), name);
	}

	/**
	 * Set value of name
	 * @param context
	 * @param name
	 */
	public final void setname(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.name.toString(), name);
	}

	/**
	 * @return value of value
	 */
	public final java.lang.Integer getvalue()
	{
		return getvalue(getContext());
	}

	/**
	 * @param context
	 * @return value of value
	 */
	public final java.lang.Integer getvalue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.value.toString());
	}

	/**
	 * Set value of value
	 * @param value
	 */
	public final void setvalue(java.lang.Integer value)
	{
		setvalue(getContext(), value);
	}

	/**
	 * Set value of value
	 * @param context
	 * @param value
	 */
	public final void setvalue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer value)
	{
		getMendixObject().setValue(context, MemberNames.value.toString(), value);
	}

	/**
	 * @return value of X
	 */
	public final java.lang.String getX()
	{
		return getX(getContext());
	}

	/**
	 * @param context
	 * @return value of X
	 */
	public final java.lang.String getX(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.X.toString());
	}

	/**
	 * Set value of X
	 * @param x
	 */
	public final void setX(java.lang.String x)
	{
		setX(getContext(), x);
	}

	/**
	 * Set value of X
	 * @param context
	 * @param x
	 */
	public final void setX(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String x)
	{
		getMendixObject().setValue(context, MemberNames.X.toString(), x);
	}

	/**
	 * @return value of Y
	 */
	public final java.lang.String getY()
	{
		return getY(getContext());
	}

	/**
	 * @param context
	 * @return value of Y
	 */
	public final java.lang.String getY(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Y.toString());
	}

	/**
	 * Set value of Y
	 * @param y
	 */
	public final void setY(java.lang.String y)
	{
		setY(getContext(), y);
	}

	/**
	 * Set value of Y
	 * @param context
	 * @param y
	 */
	public final void setY(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String y)
	{
		getMendixObject().setValue(context, MemberNames.Y.toString(), y);
	}

	/**
	 * @return value of Z
	 */
	public final java.lang.Integer getZ()
	{
		return getZ(getContext());
	}

	/**
	 * @param context
	 * @return value of Z
	 */
	public final java.lang.Integer getZ(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Z.toString());
	}

	/**
	 * Set value of Z
	 * @param z
	 */
	public final void setZ(java.lang.Integer z)
	{
		setZ(getContext(), z);
	}

	/**
	 * Set value of Z
	 * @param context
	 * @param z
	 */
	public final void setZ(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer z)
	{
		getMendixObject().setValue(context, MemberNames.Z.toString(), z);
	}

	/**
	 * @return value of JsonObject_Root
	 */
	public final rest.proxies.Root getJsonObject_Root() throws com.mendix.core.CoreException
	{
		return getJsonObject_Root(getContext());
	}

	/**
	 * @param context
	 * @return value of JsonObject_Root
	 */
	public final rest.proxies.Root getJsonObject_Root(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		rest.proxies.Root result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.JsonObject_Root.toString());
		if (identifier != null)
			result = rest.proxies.Root.load(context, identifier);
		return result;
	}

	/**
	 * Set value of JsonObject_Root
	 * @param jsonobject_root
	 */
	public final void setJsonObject_Root(rest.proxies.Root jsonobject_root)
	{
		setJsonObject_Root(getContext(), jsonobject_root);
	}

	/**
	 * Set value of JsonObject_Root
	 * @param context
	 * @param jsonobject_root
	 */
	public final void setJsonObject_Root(com.mendix.systemwideinterfaces.core.IContext context, rest.proxies.Root jsonobject_root)
	{
		if (jsonobject_root == null)
			getMendixObject().setValue(context, MemberNames.JsonObject_Root.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.JsonObject_Root.toString(), jsonobject_root.getMendixObject().getId());
	}

	/**
	 * @return value of JsonObject_RespondeCollection
	 */
	public final rest.proxies.RespondeCollection getJsonObject_RespondeCollection() throws com.mendix.core.CoreException
	{
		return getJsonObject_RespondeCollection(getContext());
	}

	/**
	 * @param context
	 * @return value of JsonObject_RespondeCollection
	 */
	public final rest.proxies.RespondeCollection getJsonObject_RespondeCollection(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		rest.proxies.RespondeCollection result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.JsonObject_RespondeCollection.toString());
		if (identifier != null)
			result = rest.proxies.RespondeCollection.load(context, identifier);
		return result;
	}

	/**
	 * Set value of JsonObject_RespondeCollection
	 * @param jsonobject_respondecollection
	 */
	public final void setJsonObject_RespondeCollection(rest.proxies.RespondeCollection jsonobject_respondecollection)
	{
		setJsonObject_RespondeCollection(getContext(), jsonobject_respondecollection);
	}

	/**
	 * Set value of JsonObject_RespondeCollection
	 * @param context
	 * @param jsonobject_respondecollection
	 */
	public final void setJsonObject_RespondeCollection(com.mendix.systemwideinterfaces.core.IContext context, rest.proxies.RespondeCollection jsonobject_respondecollection)
	{
		if (jsonobject_respondecollection == null)
			getMendixObject().setValue(context, MemberNames.JsonObject_RespondeCollection.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.JsonObject_RespondeCollection.toString(), jsonobject_respondecollection.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return jsonObjectMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final rest.proxies.JsonObject that = (rest.proxies.JsonObject) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Rest.JsonObject";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
