// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package rest.proxies;

public class RespondeCollection
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject respondeCollectionMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Rest.RespondeCollection";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		RespondeCollection_Values("Rest.RespondeCollection_Values"),
		RespondeCollection_SeriesCore("Rest.RespondeCollection_SeriesCore");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public RespondeCollection(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Rest.RespondeCollection"));
	}

	protected RespondeCollection(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject respondeCollectionMendixObject)
	{
		if (respondeCollectionMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Rest.RespondeCollection", respondeCollectionMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Rest.RespondeCollection");

		this.respondeCollectionMendixObject = respondeCollectionMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'RespondeCollection.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static rest.proxies.RespondeCollection initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return rest.proxies.RespondeCollection.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static rest.proxies.RespondeCollection initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new rest.proxies.RespondeCollection(context, mendixObject);
	}

	public static rest.proxies.RespondeCollection load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return rest.proxies.RespondeCollection.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of RespondeCollection_Values
	 */
	public final java.util.List<myfirstmodule.proxies.Values> getRespondeCollection_Values() throws com.mendix.core.CoreException
	{
		return getRespondeCollection_Values(getContext());
	}

	/**
	 * @param context
	 * @return value of RespondeCollection_Values
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<myfirstmodule.proxies.Values> getRespondeCollection_Values(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<myfirstmodule.proxies.Values> result = new java.util.ArrayList<myfirstmodule.proxies.Values>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.RespondeCollection_Values.toString());
		if (valueObject == null)
			return result;
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject))
			result.add(myfirstmodule.proxies.Values.initialize(context, mendixObject));
		return result;
	}

	/**
	 * Set value of RespondeCollection_Values
	 * @param respondecollection_values
	 */
	public final void setRespondeCollection_Values(java.util.List<myfirstmodule.proxies.Values> respondecollection_values)
	{
		setRespondeCollection_Values(getContext(), respondecollection_values);
	}

	/**
	 * Set value of RespondeCollection_Values
	 * @param context
	 * @param respondecollection_values
	 */
	public final void setRespondeCollection_Values(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<myfirstmodule.proxies.Values> respondecollection_values)
	{
		java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier> identifiers = new java.util.ArrayList<com.mendix.systemwideinterfaces.core.IMendixIdentifier>();
		for (myfirstmodule.proxies.Values proxyObject : respondecollection_values)
			identifiers.add(proxyObject.getMendixObject().getId());
		getMendixObject().setValue(context, MemberNames.RespondeCollection_Values.toString(), identifiers);
	}

	/**
	 * @return value of RespondeCollection_SeriesCore
	 */
	public final java.util.List<myfirstmodule.proxies.SeriesCore> getRespondeCollection_SeriesCore() throws com.mendix.core.CoreException
	{
		return getRespondeCollection_SeriesCore(getContext());
	}

	/**
	 * @param context
	 * @return value of RespondeCollection_SeriesCore
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<myfirstmodule.proxies.SeriesCore> getRespondeCollection_SeriesCore(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<myfirstmodule.proxies.SeriesCore> result = new java.util.ArrayList<myfirstmodule.proxies.SeriesCore>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.RespondeCollection_SeriesCore.toString());
		if (valueObject == null)
			return result;
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject))
			result.add(myfirstmodule.proxies.SeriesCore.initialize(context, mendixObject));
		return result;
	}

	/**
	 * Set value of RespondeCollection_SeriesCore
	 * @param respondecollection_seriescore
	 */
	public final void setRespondeCollection_SeriesCore(java.util.List<myfirstmodule.proxies.SeriesCore> respondecollection_seriescore)
	{
		setRespondeCollection_SeriesCore(getContext(), respondecollection_seriescore);
	}

	/**
	 * Set value of RespondeCollection_SeriesCore
	 * @param context
	 * @param respondecollection_seriescore
	 */
	public final void setRespondeCollection_SeriesCore(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<myfirstmodule.proxies.SeriesCore> respondecollection_seriescore)
	{
		java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier> identifiers = new java.util.ArrayList<com.mendix.systemwideinterfaces.core.IMendixIdentifier>();
		for (myfirstmodule.proxies.SeriesCore proxyObject : respondecollection_seriescore)
			identifiers.add(proxyObject.getMendixObject().getId());
		getMendixObject().setValue(context, MemberNames.RespondeCollection_SeriesCore.toString(), identifiers);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return respondeCollectionMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final rest.proxies.RespondeCollection that = (rest.proxies.RespondeCollection) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Rest.RespondeCollection";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
