// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package myfirstmodule.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;

public class CloneImage extends UserAction<IMendixObject>
{
	/** @deprecated use sourceImage.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __sourceImage;
	private final myfirstmodule.proxies.Img sourceImage;

	public CloneImage(
		IContext context,
		IMendixObject _sourceImage
	)
	{
		super(context);
		this.__sourceImage = _sourceImage;
		this.sourceImage = _sourceImage == null ? null : myfirstmodule.proxies.Img.initialize(getContext(), _sourceImage);
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
          IContext context = getContext();

          // Debug: check what we actually received
          if (__sourceImage == null) {
              throw new IllegalArgumentException("__sourceImage is null - nothing was passed to the action");
          }
          if (sourceImage == null) {
              throw new IllegalArgumentException("sourceImage proxy is null - proxy initialization failed");
          }

          IMendixObject source = sourceImage.getMendixObject();
          if (source == null) {
              throw new IllegalArgumentException("getMendixObject() returned null");
          }

          IMendixObject clone = com.mendix.core.Core.instantiate(context, source.getType());

          clone.setValue(context, "Name", source.getValue(context, "Name"));

          try (java.io.InputStream is = com.mendix.core.Core.getFileDocumentContent(context, source)) {
              if (is != null) {
                  com.mendix.core.Core.storeFileDocumentContent(context, clone,
                      (String) source.getValue(context, "Name"), is);
              }
          }

          com.mendix.core.Core.commit(context, clone);

          return clone;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "CloneImage";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
