// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package myfirstmodule.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.UserAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class JA_CreateSampleImage extends UserAction<IMendixObject>
{
	public JA_CreateSampleImage(IContext context)
	{
		super(context);
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE

		java.io.File file = new java.io.File(com.mendix.core.Core.getConfiguration().getResourcesPath(), "e2e/sample.png");
		com.mendix.systemwideinterfaces.core.IMendixObject img = com.mendix.core.Core.instantiate(getContext(), "MyFirstModule.Img");
		img.setValue(getContext(), "Name", "e2e-sample.png");
		try (java.io.InputStream stream = new java.io.FileInputStream(file)) {
			com.mendix.core.Core.storeImageDocumentContent(getContext(), img, stream, 100, 100);
		}
		return img;

		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_CreateSampleImage";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
