// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package employeedb.proxies;

public class BirtyValue implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject birtyValueMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EmployeeDB.BirtyValue";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		index("index"),
		birth_day("birth_day"),
		birth_month("birth_month"),
		birth_year("birth_year"),
		birth_date("birth_date");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public BirtyValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected BirtyValue(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject birtyValueMendixObject)
	{
		if (birtyValueMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!birtyValueMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.birtyValueMendixObject = birtyValueMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static employeedb.proxies.BirtyValue initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new employeedb.proxies.BirtyValue(context, mendixObject);
	}

	public static employeedb.proxies.BirtyValue load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return employeedb.proxies.BirtyValue.initialize(context, mendixObject);
	}

	/**
	 * @return value of index
	 */
	public final java.lang.Integer getindex()
	{
		return getindex(getContext());
	}

	/**
	 * @param context
	 * @return value of index
	 */
	public final java.lang.Integer getindex(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.index.toString());
	}

	/**
	 * Set value of index
	 * @param index
	 */
	public final void setindex(java.lang.Integer index)
	{
		setindex(getContext(), index);
	}

	/**
	 * Set value of index
	 * @param context
	 * @param index
	 */
	public final void setindex(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer index)
	{
		getMendixObject().setValue(context, MemberNames.index.toString(), index);
	}

	/**
	 * @return value of birth_day
	 */
	public final java.lang.Integer getbirth_day()
	{
		return getbirth_day(getContext());
	}

	/**
	 * @param context
	 * @return value of birth_day
	 */
	public final java.lang.Integer getbirth_day(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.birth_day.toString());
	}

	/**
	 * Set value of birth_day
	 * @param birth_day
	 */
	public final void setbirth_day(java.lang.Integer birth_day)
	{
		setbirth_day(getContext(), birth_day);
	}

	/**
	 * Set value of birth_day
	 * @param context
	 * @param birth_day
	 */
	public final void setbirth_day(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer birth_day)
	{
		getMendixObject().setValue(context, MemberNames.birth_day.toString(), birth_day);
	}

	/**
	 * @return value of birth_month
	 */
	public final java.lang.Integer getbirth_month()
	{
		return getbirth_month(getContext());
	}

	/**
	 * @param context
	 * @return value of birth_month
	 */
	public final java.lang.Integer getbirth_month(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.birth_month.toString());
	}

	/**
	 * Set value of birth_month
	 * @param birth_month
	 */
	public final void setbirth_month(java.lang.Integer birth_month)
	{
		setbirth_month(getContext(), birth_month);
	}

	/**
	 * Set value of birth_month
	 * @param context
	 * @param birth_month
	 */
	public final void setbirth_month(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer birth_month)
	{
		getMendixObject().setValue(context, MemberNames.birth_month.toString(), birth_month);
	}

	/**
	 * @return value of birth_year
	 */
	public final java.lang.Integer getbirth_year()
	{
		return getbirth_year(getContext());
	}

	/**
	 * @param context
	 * @return value of birth_year
	 */
	public final java.lang.Integer getbirth_year(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.birth_year.toString());
	}

	/**
	 * Set value of birth_year
	 * @param birth_year
	 */
	public final void setbirth_year(java.lang.Integer birth_year)
	{
		setbirth_year(getContext(), birth_year);
	}

	/**
	 * Set value of birth_year
	 * @param context
	 * @param birth_year
	 */
	public final void setbirth_year(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer birth_year)
	{
		getMendixObject().setValue(context, MemberNames.birth_year.toString(), birth_year);
	}

	/**
	 * @return value of birth_date
	 */
	public final java.util.Date getbirth_date()
	{
		return getbirth_date(getContext());
	}

	/**
	 * @param context
	 * @return value of birth_date
	 */
	public final java.util.Date getbirth_date(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.birth_date.toString());
	}

	/**
	 * Set value of birth_date
	 * @param birth_date
	 */
	public final void setbirth_date(java.util.Date birth_date)
	{
		setbirth_date(getContext(), birth_date);
	}

	/**
	 * Set value of birth_date
	 * @param context
	 * @param birth_date
	 */
	public final void setbirth_date(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date birth_date)
	{
		getMendixObject().setValue(context, MemberNames.birth_date.toString(), birth_date);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return birtyValueMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final employeedb.proxies.BirtyValue that = (employeedb.proxies.BirtyValue) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
