// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package employeedb.proxies;

public enum Color
{
	Aqua(new java.lang.String[][] { new java.lang.String[] { "en_US", "Aqua" } }),
	Black(new java.lang.String[][] { new java.lang.String[] { "en_US", "Black" } }),
	Blue(new java.lang.String[][] { new java.lang.String[] { "en_US", "Blue" } }),
	Blush(new java.lang.String[][] { new java.lang.String[] { "en_US", "Blush" } }),
	Cyan(new java.lang.String[][] { new java.lang.String[] { "en_US", "Cyan" } }),
	Green(new java.lang.String[][] { new java.lang.String[] { "en_US", "Green" } }),
	Pink(new java.lang.String[][] { new java.lang.String[] { "en_US", "Pink" } }),
	Red(new java.lang.String[][] { new java.lang.String[] { "en_US", "Red" } });

	private final java.util.Map<java.lang.String, java.lang.String> captions;

	private Color(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<>();
		for (java.lang.String[] captionString : captionStrings) {
			captions.put(captionString[0], captionString[1]);
		}
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		return captions.getOrDefault(languageCode, "en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
