// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package employeedb.proxies;

public enum Color
{
	Aqua("b162ff57-96d2-448a-a0c6-bba1d9c88646"),
	Black("0dddbe21-d71b-4c71-b802-f03a5b9cfc94"),
	Blue("35eaf740-de17-44b8-a2be-2fd93715d8a1"),
	Blush("880a4ff4-790e-4260-a27a-db44fa05f851"),
	Cyan("4c238d92-bc41-4a86-8cf0-70d85fa3d658"),
	Green("d0924ef1-b296-4063-bc54-870a7cf2028b"),
	Pink("36ad47d6-02f3-4458-8a65-4797c857461b"),
	Red("64db4586-6097-45d6-93bb-1c144e106aa5");

	private final java.lang.String i18nCaptionKey;
	
	private Color(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
