// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package employeedb.proxies;

public class Snapshot implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject snapshotMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EmployeeDB.Snapshot";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		snapshot_id("snapshot_id"),
		snapshot_version("snapshot_version");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Snapshot(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Snapshot(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject snapshotMendixObject)
	{
		if (snapshotMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, snapshotMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.snapshotMendixObject = snapshotMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static employeedb.proxies.Snapshot initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new employeedb.proxies.Snapshot(context, mendixObject);
	}

	public static employeedb.proxies.Snapshot load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return employeedb.proxies.Snapshot.initialize(context, mendixObject);
	}

	public static java.util.List<employeedb.proxies.Snapshot> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> employeedb.proxies.Snapshot.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of snapshot_id
	 */
	public final java.lang.String getsnapshot_id()
	{
		return getsnapshot_id(getContext());
	}

	/**
	 * @param context
	 * @return value of snapshot_id
	 */
	public final java.lang.String getsnapshot_id(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.snapshot_id.toString());
	}

	/**
	 * Set value of snapshot_id
	 * @param snapshot_id
	 */
	public final void setsnapshot_id(java.lang.String snapshot_id)
	{
		setsnapshot_id(getContext(), snapshot_id);
	}

	/**
	 * Set value of snapshot_id
	 * @param context
	 * @param snapshot_id
	 */
	public final void setsnapshot_id(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String snapshot_id)
	{
		getMendixObject().setValue(context, MemberNames.snapshot_id.toString(), snapshot_id);
	}

	/**
	 * @return value of snapshot_version
	 */
	public final java.lang.Integer getsnapshot_version()
	{
		return getsnapshot_version(getContext());
	}

	/**
	 * @param context
	 * @return value of snapshot_version
	 */
	public final java.lang.Integer getsnapshot_version(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.snapshot_version.toString());
	}

	/**
	 * Set value of snapshot_version
	 * @param snapshot_version
	 */
	public final void setsnapshot_version(java.lang.Integer snapshot_version)
	{
		setsnapshot_version(getContext(), snapshot_version);
	}

	/**
	 * Set value of snapshot_version
	 * @param context
	 * @param snapshot_version
	 */
	public final void setsnapshot_version(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer snapshot_version)
	{
		getMendixObject().setValue(context, MemberNames.snapshot_version.toString(), snapshot_version);
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return snapshotMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final employeedb.proxies.Snapshot that = (employeedb.proxies.Snapshot) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
