// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package bootstrapbadge.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the BootstrapBadge module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder calledMicroflowBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("BootstrapBadge.CalledMicroflow");
		return builder;
	}

	public static void calledMicroflow(IContext context)
	{
		calledMicroflowBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder callMicroflowBuilder(
		bootstrapbadge.proxies.Badge _badge
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("BootstrapBadge.CallMicroflow");
		builder = builder.withParam("Badge", _badge);
		return builder;
	}

	public static void callMicroflow(
		IContext context,
		bootstrapbadge.proxies.Badge _badge
	)
	{
		callMicroflowBuilder(
				_badge
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder closePageBuilder(
		bootstrapbadge.proxies.Badge _badge
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("BootstrapBadge.ClosePage");
		builder = builder.withParam("Badge", _badge);
		return builder;
	}

	public static void closePage(
		IContext context,
		bootstrapbadge.proxies.Badge _badge
	)
	{
		closePageBuilder(
				_badge
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dataOnlyBuilder(
		bootstrapbadge.proxies.Badge _badge
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("BootstrapBadge.DataOnly");
		builder = builder.withParam("Badge", _badge);
		return builder;
	}

	public static bootstrapbadge.proxies.Badge dataOnly(
		IContext context,
		bootstrapbadge.proxies.Badge _badge
	)
	{
		Object result = dataOnlyBuilder(
				_badge
			)
			.execute(context);
		return result == null ? null : bootstrapbadge.proxies.Badge.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder disableButtonBuilder(
		bootstrapbadge.proxies.Badge _badge
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("BootstrapBadge.DisableButton");
		builder = builder.withParam("Badge", _badge);
		return builder;
	}

	public static bootstrapbadge.proxies.Badge disableButton(
		IContext context,
		bootstrapbadge.proxies.Badge _badge
	)
	{
		Object result = disableButtonBuilder(
				_badge
			)
			.execute(context);
		return result == null ? null : bootstrapbadge.proxies.Badge.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder do_NothingBuilder(
		bootstrapbadge.proxies.Badge _badge
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("BootstrapBadge.Do_Nothing");
		builder = builder.withParam("Badge", _badge);
		return builder;
	}

	public static void do_Nothing(
		IContext context,
		bootstrapbadge.proxies.Badge _badge
	)
	{
		do_NothingBuilder(
				_badge
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_Data_Label_NoStyleBuilder(
		bootstrapbadge.proxies.Badge _badge
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("BootstrapBadge.DS_Data_Label_NoStyle");
		builder = builder.withParam("Badge", _badge);
		return builder;
	}

	public static bootstrapbadge.proxies.Badge dS_Data_Label_NoStyle(
		IContext context,
		bootstrapbadge.proxies.Badge _badge
	)
	{
		Object result = dS_Data_Label_NoStyleBuilder(
				_badge
			)
			.execute(context);
		return result == null ? null : bootstrapbadge.proxies.Badge.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_Data_Label_StyleBuilder(
		bootstrapbadge.proxies.Badge _badge
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("BootstrapBadge.DS_Data_Label_Style");
		builder = builder.withParam("Badge", _badge);
		return builder;
	}

	public static bootstrapbadge.proxies.Badge dS_Data_Label_Style(
		IContext context,
		bootstrapbadge.proxies.Badge _badge
	)
	{
		Object result = dS_Data_Label_StyleBuilder(
				_badge
			)
			.execute(context);
		return result == null ? null : bootstrapbadge.proxies.Badge.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_Data_NoLabel_NoStyleBuilder(
		bootstrapbadge.proxies.Badge _badge
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("BootstrapBadge.DS_Data_NoLabel_NoStyle");
		builder = builder.withParam("Badge", _badge);
		return builder;
	}

	public static bootstrapbadge.proxies.Badge dS_Data_NoLabel_NoStyle(
		IContext context,
		bootstrapbadge.proxies.Badge _badge
	)
	{
		Object result = dS_Data_NoLabel_NoStyleBuilder(
				_badge
			)
			.execute(context);
		return result == null ? null : bootstrapbadge.proxies.Badge.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_Data_NoLabel_StyleBuilder(
		bootstrapbadge.proxies.Badge _badge
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("BootstrapBadge.DS_Data_NoLabel_Style");
		builder = builder.withParam("Badge", _badge);
		return builder;
	}

	public static bootstrapbadge.proxies.Badge dS_Data_NoLabel_Style(
		IContext context,
		bootstrapbadge.proxies.Badge _badge
	)
	{
		Object result = dS_Data_NoLabel_StyleBuilder(
				_badge
			)
			.execute(context);
		return result == null ? null : bootstrapbadge.proxies.Badge.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_NoContextBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("BootstrapBadge.DS_NoContext");
		return builder;
	}

	public static bootstrapbadge.proxies.Badge dS_NoContext(IContext context)
	{
		Object result = dS_NoContextBuilder().execute(context);
		return result == null ? null : bootstrapbadge.proxies.Badge.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_NoData_Label_Style_Static_DataBuilder(
		bootstrapbadge.proxies.Badge _badge
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("BootstrapBadge.DS_NoData_Label_Style_Static_Data");
		builder = builder.withParam("Badge", _badge);
		return builder;
	}

	public static bootstrapbadge.proxies.Badge dS_NoData_Label_Style_Static_Data(
		IContext context,
		bootstrapbadge.proxies.Badge _badge
	)
	{
		Object result = dS_NoData_Label_Style_Static_DataBuilder(
				_badge
			)
			.execute(context);
		return result == null ? null : bootstrapbadge.proxies.Badge.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_NoData_NoLabel_NoStyleBuilder(
		bootstrapbadge.proxies.Badge _badge
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("BootstrapBadge.DS_NoData_NoLabel_NoStyle");
		builder = builder.withParam("Badge", _badge);
		return builder;
	}

	public static bootstrapbadge.proxies.Badge dS_NoData_NoLabel_NoStyle(
		IContext context,
		bootstrapbadge.proxies.Badge _badge
	)
	{
		Object result = dS_NoData_NoLabel_NoStyleBuilder(
				_badge
			)
			.execute(context);
		return result == null ? null : bootstrapbadge.proxies.Badge.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_OtherProgressBuilder(
		bootstrapbadge.proxies.Badge _badge
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("BootstrapBadge.DS_OtherProgress");
		builder = builder.withParam("Badge", _badge);
		return builder;
	}

	public static bootstrapbadge.proxies.Badge dS_OtherProgress(
		IContext context,
		bootstrapbadge.proxies.Badge _badge
	)
	{
		Object result = dS_OtherProgressBuilder(
				_badge
			)
			.execute(context);
		return result == null ? null : bootstrapbadge.proxies.Badge.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dSS_GetBadgeBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("BootstrapBadge.DSS_GetBadge");
		return builder;
	}

	public static bootstrapbadge.proxies.Badge dSS_GetBadge(IContext context)
	{
		Object result = dSS_GetBadgeBuilder().execute(context);
		return result == null ? null : bootstrapbadge.proxies.Badge.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder iVK_CallMicroflowBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("BootstrapBadge.IVK_CallMicroflow");
		return builder;
	}

	public static void iVK_CallMicroflow(IContext context)
	{
		iVK_CallMicroflowBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder iVK_CallNanoflowBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("BootstrapBadge.IVK_CallNanoflow");
		return builder;
	}

	public static void iVK_CallNanoflow(IContext context)
	{
		iVK_CallNanoflowBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder iVK_ClosePageBuilder(
		bootstrapbadge.proxies.Badge _badge
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("BootstrapBadge.IVK_ClosePage");
		builder = builder.withParam("Badge", _badge);
		return builder;
	}

	public static void iVK_ClosePage(
		IContext context,
		bootstrapbadge.proxies.Badge _badge
	)
	{
		iVK_ClosePageBuilder(
				_badge
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder iVK_ClosePopupBuilder(
		bootstrapbadge.proxies.Badge _badge
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("BootstrapBadge.IVK_ClosePopup");
		builder = builder.withParam("Badge", _badge);
		return builder;
	}

	public static void iVK_ClosePopup(
		IContext context,
		bootstrapbadge.proxies.Badge _badge
	)
	{
		iVK_ClosePopupBuilder(
				_badge
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder iVK_ErrorBuilder(
		bootstrapbadge.proxies.Badge _badge
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("BootstrapBadge.IVK_Error");
		builder = builder.withParam("Badge", _badge);
		return builder;
	}

	public static void iVK_Error(
		IContext context,
		bootstrapbadge.proxies.Badge _badge
	)
	{
		iVK_ErrorBuilder(
				_badge
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder iVK_OnclickBuilder(
		bootstrapbadge.proxies.Badge _badge
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("BootstrapBadge.IVK_Onclick");
		builder = builder.withParam("Badge", _badge);
		return builder;
	}

	public static void iVK_Onclick(
		IContext context,
		bootstrapbadge.proxies.Badge _badge
	)
	{
		iVK_OnclickBuilder(
				_badge
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder iVK_RefreshBuilder(
		bootstrapbadge.proxies.Badge _badge
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("BootstrapBadge.IVK_Refresh");
		builder = builder.withParam("Badge", _badge);
		return builder;
	}

	public static void iVK_Refresh(
		IContext context,
		bootstrapbadge.proxies.Badge _badge
	)
	{
		iVK_RefreshBuilder(
				_badge
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder iVK_ShowPageBuilder(
		bootstrapbadge.proxies.Badge _badge
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("BootstrapBadge.IVK_ShowPage");
		builder = builder.withParam("Badge", _badge);
		return builder;
	}

	public static void iVK_ShowPage(
		IContext context,
		bootstrapbadge.proxies.Badge _badge
	)
	{
		iVK_ShowPageBuilder(
				_badge
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder noDataNoLabelBuilder(
		bootstrapbadge.proxies.Badge _badge
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("BootstrapBadge.NoDataNoLabel");
		builder = builder.withParam("Badge", _badge);
		return builder;
	}

	public static bootstrapbadge.proxies.Badge noDataNoLabel(
		IContext context,
		bootstrapbadge.proxies.Badge _badge
	)
	{
		Object result = noDataNoLabelBuilder(
				_badge
			)
			.execute(context);
		return result == null ? null : bootstrapbadge.proxies.Badge.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder noStyleBuilder(
		bootstrapbadge.proxies.Badge _badge
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("BootstrapBadge.NoStyle");
		builder = builder.withParam("Badge", _badge);
		return builder;
	}

	public static bootstrapbadge.proxies.Badge noStyle(
		IContext context,
		bootstrapbadge.proxies.Badge _badge
	)
	{
		Object result = noStyleBuilder(
				_badge
			)
			.execute(context);
		return result == null ? null : bootstrapbadge.proxies.Badge.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder onStartupBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("BootstrapBadge.OnStartup");
		return builder;
	}

	public static boolean onStartup(IContext context)
	{
		Object result = onStartupBuilder().execute(context);
		return (boolean) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder onStartupCreateDataBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("BootstrapBadge.OnStartupCreateData");
		return builder;
	}

	public static boolean onStartupCreateData(IContext context)
	{
		Object result = onStartupCreateDataBuilder().execute(context);
		return (boolean) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder opn_ClosePopupBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("BootstrapBadge.Opn_ClosePopup");
		return builder;
	}

	public static void opn_ClosePopup(IContext context)
	{
		opn_ClosePopupBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder opn_EmptyLabelAndDataBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("BootstrapBadge.opn_EmptyLabelAndData");
		return builder;
	}

	public static void opn_EmptyLabelAndData(IContext context)
	{
		opn_EmptyLabelAndDataBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder opn_OnclickBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("BootstrapBadge.Opn_Onclick");
		return builder;
	}

	public static void opn_Onclick(IContext context)
	{
		opn_OnclickBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder opn_OnclickClosePageBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("BootstrapBadge.opn_OnclickClosePage");
		return builder;
	}

	public static void opn_OnclickClosePage(IContext context)
	{
		opn_OnclickClosePageBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder opn_OnclickOpenPageBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("BootstrapBadge.Opn_OnclickOpenPage");
		return builder;
	}

	public static void opn_OnclickOpenPage(IContext context)
	{
		opn_OnclickOpenPageBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder opnHomeBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("BootstrapBadge.OpnHome");
		return builder;
	}

	public static void opnHome(IContext context)
	{
		opnHomeBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder testBuilder(
		bootstrapbadge.proxies.Badge _badge
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("BootstrapBadge.test");
		builder = builder.withParam("Badge", _badge);
		return builder;
	}

	public static void test(
		IContext context,
		bootstrapbadge.proxies.Badge _badge
	)
	{
		testBuilder(
				_badge
			)
			.execute(context);
	}
}
