// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package webactions.proxies;

public enum PictureQuality
{
	original("4523f10a-ea35-4400-9023-a89811b5cc65"),
	low("6db6c240-d738-4f24-b939-435ec3c49054"),
	medium("7cb4f68f-9e2c-45cb-99bc-cef75bf967af"),
	high("f8e5e6fc-3083-4898-9d2c-ba755e39cf62"),
	custom("5e87e0dd-4766-4d3f-bc11-5bdf0778c49e");

	private final java.lang.String i18nCaptionKey;
	
	private PictureQuality(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
