// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package feedbackmodule.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

public class XSS_Sanitizer extends CustomJavaAction<java.lang.String>
{
	private final java.lang.String stringToSanitize;

	public XSS_Sanitizer(
		IContext context,
		java.lang.String _stringToSanitize
	)
	{
		super(context);
		this.stringToSanitize = _stringToSanitize;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		throw new com.mendix.systemwideinterfaces.MendixRuntimeException("Java action was not implemented");
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "XSS_Sanitizer";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
