// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package anychartmodule.proxies;

public class Chart
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject chartMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AnyChartModule.Chart";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		Data("Data"),
		Layout("Layout"),
		Chart_Series("AnyChartModule.Chart_Series");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Chart(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "AnyChartModule.Chart"));
	}

	protected Chart(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject chartMendixObject)
	{
		if (chartMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("AnyChartModule.Chart", chartMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a AnyChartModule.Chart");

		this.chartMendixObject = chartMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Chart.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static anychartmodule.proxies.Chart initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return anychartmodule.proxies.Chart.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static anychartmodule.proxies.Chart initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new anychartmodule.proxies.Chart(context, mendixObject);
	}

	public static anychartmodule.proxies.Chart load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return anychartmodule.proxies.Chart.initialize(context, mendixObject);
	}

	public static java.util.List<anychartmodule.proxies.Chart> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<anychartmodule.proxies.Chart> result = new java.util.ArrayList<anychartmodule.proxies.Chart>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//AnyChartModule.Chart" + xpathConstraint))
			result.add(anychartmodule.proxies.Chart.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of Data
	 */
	public final java.lang.String getData()
	{
		return getData(getContext());
	}

	/**
	 * @param context
	 * @return value of Data
	 */
	public final java.lang.String getData(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Data.toString());
	}

	/**
	 * Set value of Data
	 * @param data
	 */
	public final void setData(java.lang.String data)
	{
		setData(getContext(), data);
	}

	/**
	 * Set value of Data
	 * @param context
	 * @param data
	 */
	public final void setData(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String data)
	{
		getMendixObject().setValue(context, MemberNames.Data.toString(), data);
	}

	/**
	 * @return value of Layout
	 */
	public final java.lang.String getLayout()
	{
		return getLayout(getContext());
	}

	/**
	 * @param context
	 * @return value of Layout
	 */
	public final java.lang.String getLayout(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Layout.toString());
	}

	/**
	 * Set value of Layout
	 * @param layout
	 */
	public final void setLayout(java.lang.String layout)
	{
		setLayout(getContext(), layout);
	}

	/**
	 * Set value of Layout
	 * @param context
	 * @param layout
	 */
	public final void setLayout(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String layout)
	{
		getMendixObject().setValue(context, MemberNames.Layout.toString(), layout);
	}

	/**
	 * @return value of Chart_Series
	 */
	public final java.util.List<anychartmodule.proxies.Series> getChart_Series() throws com.mendix.core.CoreException
	{
		return getChart_Series(getContext());
	}

	/**
	 * @param context
	 * @return value of Chart_Series
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<anychartmodule.proxies.Series> getChart_Series(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<anychartmodule.proxies.Series> result = new java.util.ArrayList<anychartmodule.proxies.Series>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.Chart_Series.toString());
		if (valueObject == null)
			return result;
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject))
			result.add(anychartmodule.proxies.Series.initialize(context, mendixObject));
		return result;
	}

	/**
	 * Set value of Chart_Series
	 * @param chart_series
	 */
	public final void setChart_Series(java.util.List<anychartmodule.proxies.Series> chart_series)
	{
		setChart_Series(getContext(), chart_series);
	}

	/**
	 * Set value of Chart_Series
	 * @param context
	 * @param chart_series
	 */
	public final void setChart_Series(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<anychartmodule.proxies.Series> chart_series)
	{
		java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier> identifiers = new java.util.ArrayList<com.mendix.systemwideinterfaces.core.IMendixIdentifier>();
		for (anychartmodule.proxies.Series proxyObject : chart_series)
			identifiers.add(proxyObject.getMendixObject().getId());
		getMendixObject().setValue(context, MemberNames.Chart_Series.toString(), identifiers);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return chartMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final anychartmodule.proxies.Chart that = (anychartmodule.proxies.Chart) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "AnyChartModule.Chart";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
