// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package anychartmodule.proxies;

public class Y
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject yMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AnyChartModule.Y";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Y_JsonObject("AnyChartModule.Y_JsonObject");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Y(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "AnyChartModule.Y"));
	}

	protected Y(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject yMendixObject)
	{
		if (yMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("AnyChartModule.Y", yMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a AnyChartModule.Y");

		this.yMendixObject = yMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Y.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static anychartmodule.proxies.Y initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return anychartmodule.proxies.Y.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static anychartmodule.proxies.Y initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new anychartmodule.proxies.Y(context, mendixObject);
	}

	public static anychartmodule.proxies.Y load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return anychartmodule.proxies.Y.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Y_JsonObject
	 */
	public final anychartmodule.proxies.JsonObject getY_JsonObject() throws com.mendix.core.CoreException
	{
		return getY_JsonObject(getContext());
	}

	/**
	 * @param context
	 * @return value of Y_JsonObject
	 */
	public final anychartmodule.proxies.JsonObject getY_JsonObject(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		anychartmodule.proxies.JsonObject result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Y_JsonObject.toString());
		if (identifier != null)
			result = anychartmodule.proxies.JsonObject.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Y_JsonObject
	 * @param y_jsonobject
	 */
	public final void setY_JsonObject(anychartmodule.proxies.JsonObject y_jsonobject)
	{
		setY_JsonObject(getContext(), y_jsonobject);
	}

	/**
	 * Set value of Y_JsonObject
	 * @param context
	 * @param y_jsonobject
	 */
	public final void setY_JsonObject(com.mendix.systemwideinterfaces.core.IContext context, anychartmodule.proxies.JsonObject y_jsonobject)
	{
		if (y_jsonobject == null)
			getMendixObject().setValue(context, MemberNames.Y_JsonObject.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Y_JsonObject.toString(), y_jsonobject.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return yMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final anychartmodule.proxies.Y that = (anychartmodule.proxies.Y) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "AnyChartModule.Y";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
