// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package datawidgets.proxies;

public class DataGrid implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject dataGridMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "DataWidgets.DataGrid";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		StringAttribute("StringAttribute"),
		NumberAttribute("NumberAttribute"),
		DateAttribute("DateAttribute"),
		EnumAttribute("EnumAttribute"),
		BooleanAttribute("BooleanAttribute");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public DataGrid(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected DataGrid(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject dataGridMendixObject)
	{
		if (dataGridMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, dataGridMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.dataGridMendixObject = dataGridMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static datawidgets.proxies.DataGrid initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new datawidgets.proxies.DataGrid(context, mendixObject);
	}

	public static datawidgets.proxies.DataGrid load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return datawidgets.proxies.DataGrid.initialize(context, mendixObject);
	}

	public static java.util.List<datawidgets.proxies.DataGrid> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> datawidgets.proxies.DataGrid.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of StringAttribute
	 */
	public final java.lang.String getStringAttribute()
	{
		return getStringAttribute(getContext());
	}

	/**
	 * @param context
	 * @return value of StringAttribute
	 */
	public final java.lang.String getStringAttribute(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.StringAttribute.toString());
	}

	/**
	 * Set value of StringAttribute
	 * @param stringattribute
	 */
	public final void setStringAttribute(java.lang.String stringattribute)
	{
		setStringAttribute(getContext(), stringattribute);
	}

	/**
	 * Set value of StringAttribute
	 * @param context
	 * @param stringattribute
	 */
	public final void setStringAttribute(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String stringattribute)
	{
		getMendixObject().setValue(context, MemberNames.StringAttribute.toString(), stringattribute);
	}

	/**
	 * @return value of NumberAttribute
	 */
	public final java.math.BigDecimal getNumberAttribute()
	{
		return getNumberAttribute(getContext());
	}

	/**
	 * @param context
	 * @return value of NumberAttribute
	 */
	public final java.math.BigDecimal getNumberAttribute(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.NumberAttribute.toString());
	}

	/**
	 * Set value of NumberAttribute
	 * @param numberattribute
	 */
	public final void setNumberAttribute(java.math.BigDecimal numberattribute)
	{
		setNumberAttribute(getContext(), numberattribute);
	}

	/**
	 * Set value of NumberAttribute
	 * @param context
	 * @param numberattribute
	 */
	public final void setNumberAttribute(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal numberattribute)
	{
		getMendixObject().setValue(context, MemberNames.NumberAttribute.toString(), numberattribute);
	}

	/**
	 * @return value of DateAttribute
	 */
	public final java.util.Date getDateAttribute()
	{
		return getDateAttribute(getContext());
	}

	/**
	 * @param context
	 * @return value of DateAttribute
	 */
	public final java.util.Date getDateAttribute(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.DateAttribute.toString());
	}

	/**
	 * Set value of DateAttribute
	 * @param dateattribute
	 */
	public final void setDateAttribute(java.util.Date dateattribute)
	{
		setDateAttribute(getContext(), dateattribute);
	}

	/**
	 * Set value of DateAttribute
	 * @param context
	 * @param dateattribute
	 */
	public final void setDateAttribute(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date dateattribute)
	{
		getMendixObject().setValue(context, MemberNames.DateAttribute.toString(), dateattribute);
	}

	/**
	 * Get value of EnumAttribute
	 * @param enumattribute
	 */
	public final datawidgets.proxies.Enumeration_Example getEnumAttribute()
	{
		return getEnumAttribute(getContext());
	}

	/**
	 * @param context
	 * @return value of EnumAttribute
	 */
	public final datawidgets.proxies.Enumeration_Example getEnumAttribute(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.EnumAttribute.toString());
		if (obj == null) {
			return null;
		}
		return datawidgets.proxies.Enumeration_Example.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of EnumAttribute
	 * @param enumattribute
	 */
	public final void setEnumAttribute(datawidgets.proxies.Enumeration_Example enumattribute)
	{
		setEnumAttribute(getContext(), enumattribute);
	}

	/**
	 * Set value of EnumAttribute
	 * @param context
	 * @param enumattribute
	 */
	public final void setEnumAttribute(com.mendix.systemwideinterfaces.core.IContext context, datawidgets.proxies.Enumeration_Example enumattribute)
	{
		if (enumattribute != null) {
			getMendixObject().setValue(context, MemberNames.EnumAttribute.toString(), enumattribute.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.EnumAttribute.toString(), null);
		}
	}

	/**
	 * @return value of BooleanAttribute
	 */
	public final java.lang.Boolean getBooleanAttribute()
	{
		return getBooleanAttribute(getContext());
	}

	/**
	 * @param context
	 * @return value of BooleanAttribute
	 */
	public final java.lang.Boolean getBooleanAttribute(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.BooleanAttribute.toString());
	}

	/**
	 * Set value of BooleanAttribute
	 * @param booleanattribute
	 */
	public final void setBooleanAttribute(java.lang.Boolean booleanattribute)
	{
		setBooleanAttribute(getContext(), booleanattribute);
	}

	/**
	 * Set value of BooleanAttribute
	 * @param context
	 * @param booleanattribute
	 */
	public final void setBooleanAttribute(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean booleanattribute)
	{
		getMendixObject().setValue(context, MemberNames.BooleanAttribute.toString(), booleanattribute);
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return dataGridMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final datawidgets.proxies.DataGrid that = (datawidgets.proxies.DataGrid) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
