// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package datawidgets.proxies;

public enum Filter_Operators
{
	contains("75a8e25a-0f95-4bf2-bdf6-f063273d0b66"),
	startsWith("2b93b57f-9d50-42ac-bd0a-d5065a158623"),
	endsWith("51d1f831-c687-4a6f-8185-401064daf84a"),
	between("13da1f2d-f755-4943-9a4d-a395fd4cfbeb"),
	greater("681495bc-4806-4ceb-b9f1-0ad25353f26e"),
	greaterEqual("7798f534-118b-42e4-bfcc-40c01a97cd3a"),
	equal("6b939f3b-6374-4454-a5a6-8f2acd40ba99"),
	notEqual("953e2432-5ef0-4d19-9770-563c642b5346"),
	smaller("d9e2df64-88fb-4867-afcc-ec3c40cb8b95"),
	smallerEqual("b2a28222-1e12-4331-8771-c45606545d86"),
	empty("5760f6e9-d1f3-4e7e-acfe-ea3a5ac472fc"),
	notEmpty("790400e1-2e3b-4037-8417-bd3dbb553c95");

	private final java.lang.String i18nCaptionKey;
	
	private Filter_Operators(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
