// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package datawidgets.proxies;

public enum Filter_Operators
{
	contains("ff645d06-d1d0-4d5d-aa73-28b55634ea0c"),
	startsWith("ddddce6f-3f18-4471-b27b-71732918ef2e"),
	endsWith("331c5178-1b6e-441a-8f02-43a6c310789a"),
	between("39d6a140-31e7-4ce1-80a1-e7c37133d0f1"),
	greater("32f82516-32a6-493a-916c-42e51e36d39b"),
	greaterEqual("3e625c0d-0311-43c1-b9dd-90966d61b7ae"),
	equal("f5d35d1e-e949-4811-9456-1e2453d854de"),
	notEqual("e4f9c617-d5b2-409a-b757-bfe6777ca25b"),
	smaller("5e2632d8-e8d4-4181-bd59-eef166258e6d"),
	smallerEqual("2219f34e-ea3a-4629-824d-04f96e954e5d"),
	empty("7f2f63a3-3970-497b-8b77-f15fedbc55c4"),
	notEmpty("a49cca97-595f-439f-a177-d01a855eaeab");

	private final java.lang.String i18nCaptionKey;
	
	private Filter_Operators(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
