// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package datawidgets.proxies;

public enum Filter_Operators
{
	contains("4e2834a9-af47-46c7-a797-cbd673400ab0"),
	startsWith("9dc41062-2991-4ee2-a36f-80a18042fef3"),
	endsWith("07d0f652-3d81-4c6e-9fac-cb9504aab8a4"),
	between("a6f31877-096c-4b2a-ae24-bcff63492ce6"),
	greater("41a0df90-464b-42c1-91e0-00780663cfb7"),
	greaterEqual("c59cd003-d951-47b1-a8ca-80690f33ea92"),
	equal("ee35fdd3-12d3-4361-a8de-cb4649c3bddb"),
	notEqual("f21d1137-2a58-4fb1-bbdd-e4662fa1e88f"),
	smaller("6e74a01b-636e-4cf8-ab8e-16e3305c5f61"),
	smallerEqual("7ea08e33-8564-44cb-968d-0e08b48ec8da"),
	empty("781e3c2d-9f8d-417f-be90-c06a6f9043e6"),
	notEmpty("04f34321-c392-4ca7-b558-a62a6bd2d9a1");

	private final java.lang.String i18nCaptionKey;
	
	private Filter_Operators(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
