// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package allcustomwidgets.proxies;

public class SampleCountry
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject sampleCountryMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AllCustomWidgets.SampleCountry";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		OfficialLanguage("OfficialLanguage"),
		Code("Code"),
		Date("Date"),
		IsPrimary("IsPrimary"),
		GDP("GDP"),
		AutoNumber("AutoNumber"),
		SampleCountry_SampleContinent("AllCustomWidgets.SampleCountry_SampleContinent");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public SampleCountry(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "AllCustomWidgets.SampleCountry"));
	}

	protected SampleCountry(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject sampleCountryMendixObject)
	{
		if (sampleCountryMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("AllCustomWidgets.SampleCountry", sampleCountryMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a AllCustomWidgets.SampleCountry");

		this.sampleCountryMendixObject = sampleCountryMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'SampleCountry.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static allcustomwidgets.proxies.SampleCountry initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return allcustomwidgets.proxies.SampleCountry.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static allcustomwidgets.proxies.SampleCountry initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new allcustomwidgets.proxies.SampleCountry(context, mendixObject);
	}

	public static allcustomwidgets.proxies.SampleCountry load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return allcustomwidgets.proxies.SampleCountry.initialize(context, mendixObject);
	}

	public static java.util.List<allcustomwidgets.proxies.SampleCountry> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<allcustomwidgets.proxies.SampleCountry> result = new java.util.ArrayList<allcustomwidgets.proxies.SampleCountry>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//AllCustomWidgets.SampleCountry" + xpathConstraint))
			result.add(allcustomwidgets.proxies.SampleCountry.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of OfficialLanguage
	 */
	public final java.lang.String getOfficialLanguage()
	{
		return getOfficialLanguage(getContext());
	}

	/**
	 * @param context
	 * @return value of OfficialLanguage
	 */
	public final java.lang.String getOfficialLanguage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.OfficialLanguage.toString());
	}

	/**
	 * Set value of OfficialLanguage
	 * @param officiallanguage
	 */
	public final void setOfficialLanguage(java.lang.String officiallanguage)
	{
		setOfficialLanguage(getContext(), officiallanguage);
	}

	/**
	 * Set value of OfficialLanguage
	 * @param context
	 * @param officiallanguage
	 */
	public final void setOfficialLanguage(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String officiallanguage)
	{
		getMendixObject().setValue(context, MemberNames.OfficialLanguage.toString(), officiallanguage);
	}

	/**
	 * @return value of Code
	 */
	public final java.lang.Integer getCode()
	{
		return getCode(getContext());
	}

	/**
	 * @param context
	 * @return value of Code
	 */
	public final java.lang.Integer getCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Code.toString());
	}

	/**
	 * Set value of Code
	 * @param code
	 */
	public final void setCode(java.lang.Integer code)
	{
		setCode(getContext(), code);
	}

	/**
	 * Set value of Code
	 * @param context
	 * @param code
	 */
	public final void setCode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer code)
	{
		getMendixObject().setValue(context, MemberNames.Code.toString(), code);
	}

	/**
	 * @return value of Date
	 */
	public final java.util.Date getDate()
	{
		return getDate(getContext());
	}

	/**
	 * @param context
	 * @return value of Date
	 */
	public final java.util.Date getDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Date.toString());
	}

	/**
	 * Set value of Date
	 * @param date
	 */
	public final void setDate(java.util.Date date)
	{
		setDate(getContext(), date);
	}

	/**
	 * Set value of Date
	 * @param context
	 * @param date
	 */
	public final void setDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date date)
	{
		getMendixObject().setValue(context, MemberNames.Date.toString(), date);
	}

	/**
	 * @return value of IsPrimary
	 */
	public final java.lang.Boolean getIsPrimary()
	{
		return getIsPrimary(getContext());
	}

	/**
	 * @param context
	 * @return value of IsPrimary
	 */
	public final java.lang.Boolean getIsPrimary(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsPrimary.toString());
	}

	/**
	 * Set value of IsPrimary
	 * @param isprimary
	 */
	public final void setIsPrimary(java.lang.Boolean isprimary)
	{
		setIsPrimary(getContext(), isprimary);
	}

	/**
	 * Set value of IsPrimary
	 * @param context
	 * @param isprimary
	 */
	public final void setIsPrimary(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isprimary)
	{
		getMendixObject().setValue(context, MemberNames.IsPrimary.toString(), isprimary);
	}

	/**
	 * Set value of GDP
	 * @param gdp
	 */
	public final checkboxfilter.proxies.GDP getGDP()
	{
		return getGDP(getContext());
	}

	/**
	 * @param context
	 * @return value of GDP
	 */
	public final checkboxfilter.proxies.GDP getGDP(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.GDP.toString());
		if (obj == null)
			return null;

		return checkboxfilter.proxies.GDP.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of GDP
	 * @param gdp
	 */
	public final void setGDP(checkboxfilter.proxies.GDP gdp)
	{
		setGDP(getContext(), gdp);
	}

	/**
	 * Set value of GDP
	 * @param context
	 * @param gdp
	 */
	public final void setGDP(com.mendix.systemwideinterfaces.core.IContext context, checkboxfilter.proxies.GDP gdp)
	{
		if (gdp != null)
			getMendixObject().setValue(context, MemberNames.GDP.toString(), gdp.toString());
		else
			getMendixObject().setValue(context, MemberNames.GDP.toString(), null);
	}

	/**
	 * @return value of AutoNumber
	 */
	public final java.lang.Long getAutoNumber()
	{
		return getAutoNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of AutoNumber
	 */
	public final java.lang.Long getAutoNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.AutoNumber.toString());
	}

	/**
	 * Set value of AutoNumber
	 * @param autonumber
	 */
	public final void setAutoNumber(java.lang.Long autonumber)
	{
		setAutoNumber(getContext(), autonumber);
	}

	/**
	 * Set value of AutoNumber
	 * @param context
	 * @param autonumber
	 */
	public final void setAutoNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long autonumber)
	{
		getMendixObject().setValue(context, MemberNames.AutoNumber.toString(), autonumber);
	}

	/**
	 * @return value of SampleCountry_SampleContinent
	 */
	public final allcustomwidgets.proxies.SampleContinent getSampleCountry_SampleContinent() throws com.mendix.core.CoreException
	{
		return getSampleCountry_SampleContinent(getContext());
	}

	/**
	 * @param context
	 * @return value of SampleCountry_SampleContinent
	 */
	public final allcustomwidgets.proxies.SampleContinent getSampleCountry_SampleContinent(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		allcustomwidgets.proxies.SampleContinent result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.SampleCountry_SampleContinent.toString());
		if (identifier != null)
			result = allcustomwidgets.proxies.SampleContinent.load(context, identifier);
		return result;
	}

	/**
	 * Set value of SampleCountry_SampleContinent
	 * @param samplecountry_samplecontinent
	 */
	public final void setSampleCountry_SampleContinent(allcustomwidgets.proxies.SampleContinent samplecountry_samplecontinent)
	{
		setSampleCountry_SampleContinent(getContext(), samplecountry_samplecontinent);
	}

	/**
	 * Set value of SampleCountry_SampleContinent
	 * @param context
	 * @param samplecountry_samplecontinent
	 */
	public final void setSampleCountry_SampleContinent(com.mendix.systemwideinterfaces.core.IContext context, allcustomwidgets.proxies.SampleContinent samplecountry_samplecontinent)
	{
		if (samplecountry_samplecontinent == null)
			getMendixObject().setValue(context, MemberNames.SampleCountry_SampleContinent.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.SampleCountry_SampleContinent.toString(), samplecountry_samplecontinent.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return sampleCountryMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final allcustomwidgets.proxies.SampleCountry that = (allcustomwidgets.proxies.SampleCountry) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "AllCustomWidgets.SampleCountry";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
