// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package datagrid.proxies;

public enum Enumeration_Example
{
	Example_1("acd15d53-ea4b-4e9d-aa08-5efbd7d492cf"),
	Example_2("98cf9650-557c-460b-9013-a14a2a623fdf");

	private final java.lang.String i18nCaptionKey;
	
	private Enumeration_Example(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
