// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package textboxsearch.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the TextboxSearch module
	public static java.util.List<textboxsearch.proxies.Country> dS_EmptyListView(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		java.util.List<IMendixObject> objs = Core.microflowCall("TextboxSearch.DS_EmptyListView").withParams(params).execute(context);
		java.util.List<textboxsearch.proxies.Country> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(textboxsearch.proxies.Country.initialize(context, obj));
		}
		return result;
	}
	public static textboxsearch.proxies.Country dS_getCountry(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("TextboxSearch.DS_getCountry").withParams(params).execute(context);
		return result == null ? null : textboxsearch.proxies.Country.initialize(context, result);
	}
	public static java.util.List<textboxsearch.proxies.Country> dS_Microflow(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		java.util.List<IMendixObject> objs = Core.microflowCall("TextboxSearch.DS_Microflow").withParams(params).execute(context);
		java.util.List<textboxsearch.proxies.Country> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(textboxsearch.proxies.Country.initialize(context, obj));
		}
		return result;
	}
	public static textboxsearch.proxies.Continent getContinent(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("TextboxSearch.getContinent").withParams(params).execute(context);
		return result == null ? null : textboxsearch.proxies.Continent.initialize(context, result);
	}
	public static void iVK_AddListItem(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("TextboxSearch.IVK_AddListItem").withParams(params).execute(context);
	}
	public static void iVK_CreateSampleData(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("TextboxSearch.IVK_CreateSampleData").withParams(params).execute(context);
	}
	public static void iVK_Delete(IContext context, textboxsearch.proxies.Country _country)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Country", _country == null ? null : _country.getMendixObject());
		Core.microflowCall("TextboxSearch.IVK_Delete").withParams(params).execute(context);
	}
}