// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package charts_howto.proxies;

public class Series
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject seriesMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Charts_HowTo.Series";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		Series_Values("Charts_HowTo.Series_Values");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Series(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Charts_HowTo.Series"));
	}

	protected Series(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject seriesMendixObject)
	{
		if (seriesMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Charts_HowTo.Series", seriesMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Charts_HowTo.Series");

		this.seriesMendixObject = seriesMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Series.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static charts_howto.proxies.Series initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return charts_howto.proxies.Series.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static charts_howto.proxies.Series initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new charts_howto.proxies.Series(context, mendixObject);
	}

	public static charts_howto.proxies.Series load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return charts_howto.proxies.Series.initialize(context, mendixObject);
	}

	public static java.util.List<charts_howto.proxies.Series> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<charts_howto.proxies.Series> result = new java.util.ArrayList<charts_howto.proxies.Series>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//Charts_HowTo.Series" + xpathConstraint))
			result.add(charts_howto.proxies.Series.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of Series_Values
	 */
	public final charts_howto.proxies.Values getSeries_Values() throws com.mendix.core.CoreException
	{
		return getSeries_Values(getContext());
	}

	/**
	 * @param context
	 * @return value of Series_Values
	 */
	public final charts_howto.proxies.Values getSeries_Values(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		charts_howto.proxies.Values result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Series_Values.toString());
		if (identifier != null)
			result = charts_howto.proxies.Values.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Series_Values
	 * @param series_values
	 */
	public final void setSeries_Values(charts_howto.proxies.Values series_values)
	{
		setSeries_Values(getContext(), series_values);
	}

	/**
	 * Set value of Series_Values
	 * @param context
	 * @param series_values
	 */
	public final void setSeries_Values(com.mendix.systemwideinterfaces.core.IContext context, charts_howto.proxies.Values series_values)
	{
		if (series_values == null)
			getMendixObject().setValue(context, MemberNames.Series_Values.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Series_Values.toString(), series_values.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return seriesMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final charts_howto.proxies.Series that = (charts_howto.proxies.Series) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Charts_HowTo.Series";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
