// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package charts_howto.proxies;

public class Values
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject valuesMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Charts_HowTo.Values";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		xValue("xValue"),
		yValue("yValue");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Values(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Charts_HowTo.Values"));
	}

	protected Values(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject valuesMendixObject)
	{
		if (valuesMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Charts_HowTo.Values", valuesMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Charts_HowTo.Values");

		this.valuesMendixObject = valuesMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Values.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static charts_howto.proxies.Values initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return charts_howto.proxies.Values.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static charts_howto.proxies.Values initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new charts_howto.proxies.Values(context, mendixObject);
	}

	public static charts_howto.proxies.Values load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return charts_howto.proxies.Values.initialize(context, mendixObject);
	}

	public static java.util.List<charts_howto.proxies.Values> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<charts_howto.proxies.Values> result = new java.util.ArrayList<charts_howto.proxies.Values>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//Charts_HowTo.Values" + xpathConstraint))
			result.add(charts_howto.proxies.Values.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of xValue
	 */
	public final java.lang.String getxValue()
	{
		return getxValue(getContext());
	}

	/**
	 * @param context
	 * @return value of xValue
	 */
	public final java.lang.String getxValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.xValue.toString());
	}

	/**
	 * Set value of xValue
	 * @param xvalue
	 */
	public final void setxValue(java.lang.String xvalue)
	{
		setxValue(getContext(), xvalue);
	}

	/**
	 * Set value of xValue
	 * @param context
	 * @param xvalue
	 */
	public final void setxValue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xvalue)
	{
		getMendixObject().setValue(context, MemberNames.xValue.toString(), xvalue);
	}

	/**
	 * @return value of yValue
	 */
	public final java.math.BigDecimal getyValue()
	{
		return getyValue(getContext());
	}

	/**
	 * @param context
	 * @return value of yValue
	 */
	public final java.math.BigDecimal getyValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.yValue.toString());
	}

	/**
	 * Set value of yValue
	 * @param yvalue
	 */
	public final void setyValue(java.math.BigDecimal yvalue)
	{
		setyValue(getContext(), yvalue);
	}

	/**
	 * Set value of yValue
	 * @param context
	 * @param yvalue
	 */
	public final void setyValue(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal yvalue)
	{
		getMendixObject().setValue(context, MemberNames.yValue.toString(), yvalue);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return valuesMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final charts_howto.proxies.Values that = (charts_howto.proxies.Values) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Charts_HowTo.Values";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
