// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package employeedb.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the EmployeeDB module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aC_AfterMxStartupBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("EmployeeDB.AC_AfterMxStartup");
		return builder;
	}

	public static boolean aC_AfterMxStartup(IContext context)
	{
		Object result = aC_AfterMxStartupBuilder().execute(context);
		return (boolean) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aC_DropEmployeeDBBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("EmployeeDB.AC_DropEmployeeDB");
		return builder;
	}

	public static void aC_DropEmployeeDB(IContext context)
	{
		aC_DropEmployeeDBBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aC_SetupEmployeeDBBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("EmployeeDB.AC_SetupEmployeeDB");
		return builder;
	}

	public static void aC_SetupEmployeeDB(IContext context)
	{
		aC_SetupEmployeeDBBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aC_SetupFromSnapshotBuilder(
		java.lang.String _snapshotJSON
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("EmployeeDB.AC_SetupFromSnapshot");
		builder = builder.withParam("snapshotJSON", _snapshotJSON);
		return builder;
	}

	public static void aC_SetupFromSnapshot(
		IContext context,
		java.lang.String _snapshotJSON
	)
	{
		aC_SetupFromSnapshotBuilder(
				_snapshotJSON
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aRG_SnapshotBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("EmployeeDB.ARG_Snapshot");
		return builder;
	}

	public static java.lang.String aRG_Snapshot(IContext context)
	{
		Object result = aRG_SnapshotBuilder().execute(context);
		return (java.lang.String) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder createCompanyIDListBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("EmployeeDB.CreateCompanyIDList");
		return builder;
	}

	public static java.util.List<employeedb.proxies.IntValue> createCompanyIDList(IContext context)
	{
		Object result = createCompanyIDListBuilder().execute(context);
		return result == null ? null : com.mendix.utils.ListUtils.map((java.util.List<IMendixObject>) result, obj -> employeedb.proxies.IntValue.initialize(context, obj));
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder createCountryIDListBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("EmployeeDB.CreateCountryIDList");
		return builder;
	}

	public static java.util.List<employeedb.proxies.IntValue> createCountryIDList(IContext context)
	{
		Object result = createCountryIDListBuilder().execute(context);
		return result == null ? null : com.mendix.utils.ListUtils.map((java.util.List<IMendixObject>) result, obj -> employeedb.proxies.IntValue.initialize(context, obj));
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder createRoleIDListBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("EmployeeDB.CreateRoleIDList");
		return builder;
	}

	public static java.util.List<employeedb.proxies.IntValue> createRoleIDList(IContext context)
	{
		Object result = createRoleIDListBuilder().execute(context);
		return result == null ? null : com.mendix.utils.ListUtils.map((java.util.List<IMendixObject>) result, obj -> employeedb.proxies.IntValue.initialize(context, obj));
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_EmployeeBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("EmployeeDB.DS_Employee");
		return builder;
	}

	public static java.util.List<employeedb.proxies.Employee> dS_Employee(IContext context)
	{
		Object result = dS_EmployeeBuilder().execute(context);
		return result == null ? null : com.mendix.utils.ListUtils.map((java.util.List<IMendixObject>) result, obj -> employeedb.proxies.Employee.initialize(context, obj));
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder genEmployeesBuilder(
		java.lang.Long _count
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("EmployeeDB.GenEmployees");
		builder = builder.withParam("count", _count);
		return builder;
	}

	public static void genEmployees(
		IContext context,
		java.lang.Long _count
	)
	{
		genEmployeesBuilder(
				_count
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder getRandBDBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("EmployeeDB.GetRandBD");
		return builder;
	}

	public static employeedb.proxies.BirtyValue getRandBD(IContext context)
	{
		Object result = getRandBDBuilder().execute(context);
		return result == null ? null : employeedb.proxies.BirtyValue.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder getRandColorBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("EmployeeDB.GetRandColor");
		return builder;
	}

	public static employeedb.proxies.Color getRandColor(IContext context)
	{
		Object result = getRandColorBuilder().execute(context);
		return result == null ? null : employeedb.proxies.Color.valueOf((java.lang.String) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder getRandFirstNameBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("EmployeeDB.GetRandFirstName");
		return builder;
	}

	public static java.lang.String getRandFirstName(IContext context)
	{
		Object result = getRandFirstNameBuilder().execute(context);
		return (java.lang.String) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder getRandFromIntListBuilder(
		java.util.List<employeedb.proxies.IntValue> _intValueList
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("EmployeeDB.GetRandFromIntList");
		builder = builder.withParam("IntValueList", _intValueList);
		return builder;
	}

	public static java.lang.Long getRandFromIntList(
		IContext context,
		java.util.List<employeedb.proxies.IntValue> _intValueList
	)
	{
		Object result = getRandFromIntListBuilder(
				_intValueList
			)
			.execute(context);
		return (java.lang.Long) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder getRandLastNameBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("EmployeeDB.GetRandLastName");
		return builder;
	}

	public static java.lang.String getRandLastName(IContext context)
	{
		Object result = getRandLastNameBuilder().execute(context);
		return (java.lang.String) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder getRandomNBuilder(
		java.lang.Long _min,
		java.lang.Long _max
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("EmployeeDB.GetRandomN");
		builder = builder.withParam("min", _min);
		builder = builder.withParam("max", _max);
		return builder;
	}

	public static java.lang.Long getRandomN(
		IContext context,
		java.lang.Long _min,
		java.lang.Long _max
	)
	{
		Object result = getRandomNBuilder(
				_min,
				_max
			)
			.execute(context);
		return (java.lang.Long) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder jSON_SNAPSHOT_FIVE_COMPANIESBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("EmployeeDB.JSON_SNAPSHOT_FIVE_COMPANIES");
		return builder;
	}

	public static java.lang.String jSON_SNAPSHOT_FIVE_COMPANIES(IContext context)
	{
		Object result = jSON_SNAPSHOT_FIVE_COMPANIESBuilder().execute(context);
		return (java.lang.String) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder jSON_SNAPSHOT_LARGEBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("EmployeeDB.JSON_SNAPSHOT_LARGE");
		return builder;
	}

	public static java.lang.String jSON_SNAPSHOT_LARGE(IContext context)
	{
		Object result = jSON_SNAPSHOT_LARGEBuilder().execute(context);
		return (java.lang.String) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder jSON_SNAPSHOT_MEDIUMBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("EmployeeDB.JSON_SNAPSHOT_MEDIUM");
		return builder;
	}

	public static java.lang.String jSON_SNAPSHOT_MEDIUM(IContext context)
	{
		Object result = jSON_SNAPSHOT_MEDIUMBuilder().execute(context);
		return (java.lang.String) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder jSON_SNAPSHOT_SMALLBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("EmployeeDB.JSON_SNAPSHOT_SMALL");
		return builder;
	}

	public static java.lang.String jSON_SNAPSHOT_SMALL(IContext context)
	{
		Object result = jSON_SNAPSHOT_SMALLBuilder().execute(context);
		return (java.lang.String) result;
	}
}
