// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package textboxsearch.proxies;

public class Country
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject countryMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "TextboxSearch.Country";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		OfficialLanguage("OfficialLanguage"),
		Code("Code"),
		Date("Date"),
		Attribute("Attribute"),
		Number("Number"),
		Country_Continent("TextboxSearch.Country_Continent");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Country(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "TextboxSearch.Country"));
	}

	protected Country(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject countryMendixObject)
	{
		if (countryMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("TextboxSearch.Country", countryMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a TextboxSearch.Country");

		this.countryMendixObject = countryMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Country.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static textboxsearch.proxies.Country initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return textboxsearch.proxies.Country.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static textboxsearch.proxies.Country initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new textboxsearch.proxies.Country(context, mendixObject);
	}

	public static textboxsearch.proxies.Country load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return textboxsearch.proxies.Country.initialize(context, mendixObject);
	}

	public static java.util.List<textboxsearch.proxies.Country> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<textboxsearch.proxies.Country> result = new java.util.ArrayList<textboxsearch.proxies.Country>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//TextboxSearch.Country" + xpathConstraint))
			result.add(textboxsearch.proxies.Country.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of OfficialLanguage
	 */
	public final java.lang.String getOfficialLanguage()
	{
		return getOfficialLanguage(getContext());
	}

	/**
	 * @param context
	 * @return value of OfficialLanguage
	 */
	public final java.lang.String getOfficialLanguage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.OfficialLanguage.toString());
	}

	/**
	 * Set value of OfficialLanguage
	 * @param officiallanguage
	 */
	public final void setOfficialLanguage(java.lang.String officiallanguage)
	{
		setOfficialLanguage(getContext(), officiallanguage);
	}

	/**
	 * Set value of OfficialLanguage
	 * @param context
	 * @param officiallanguage
	 */
	public final void setOfficialLanguage(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String officiallanguage)
	{
		getMendixObject().setValue(context, MemberNames.OfficialLanguage.toString(), officiallanguage);
	}

	/**
	 * @return value of Code
	 */
	public final java.lang.Integer getCode()
	{
		return getCode(getContext());
	}

	/**
	 * @param context
	 * @return value of Code
	 */
	public final java.lang.Integer getCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Code.toString());
	}

	/**
	 * Set value of Code
	 * @param code
	 */
	public final void setCode(java.lang.Integer code)
	{
		setCode(getContext(), code);
	}

	/**
	 * Set value of Code
	 * @param context
	 * @param code
	 */
	public final void setCode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer code)
	{
		getMendixObject().setValue(context, MemberNames.Code.toString(), code);
	}

	/**
	 * @return value of Date
	 */
	public final java.util.Date getDate()
	{
		return getDate(getContext());
	}

	/**
	 * @param context
	 * @return value of Date
	 */
	public final java.util.Date getDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Date.toString());
	}

	/**
	 * Set value of Date
	 * @param date
	 */
	public final void setDate(java.util.Date date)
	{
		setDate(getContext(), date);
	}

	/**
	 * Set value of Date
	 * @param context
	 * @param date
	 */
	public final void setDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date date)
	{
		getMendixObject().setValue(context, MemberNames.Date.toString(), date);
	}

	/**
	 * Set value of Attribute
	 * @param attribute
	 */
	public final textboxsearch.proxies.Enumeration getAttribute()
	{
		return getAttribute(getContext());
	}

	/**
	 * @param context
	 * @return value of Attribute
	 */
	public final textboxsearch.proxies.Enumeration getAttribute(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Attribute.toString());
		if (obj == null)
			return null;

		return textboxsearch.proxies.Enumeration.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Attribute
	 * @param attribute
	 */
	public final void setAttribute(textboxsearch.proxies.Enumeration attribute)
	{
		setAttribute(getContext(), attribute);
	}

	/**
	 * Set value of Attribute
	 * @param context
	 * @param attribute
	 */
	public final void setAttribute(com.mendix.systemwideinterfaces.core.IContext context, textboxsearch.proxies.Enumeration attribute)
	{
		if (attribute != null)
			getMendixObject().setValue(context, MemberNames.Attribute.toString(), attribute.toString());
		else
			getMendixObject().setValue(context, MemberNames.Attribute.toString(), null);
	}

	/**
	 * @return value of Number
	 */
	public final java.lang.Long getNumber()
	{
		return getNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of Number
	 */
	public final java.lang.Long getNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.Number.toString());
	}

	/**
	 * Set value of Number
	 * @param number
	 */
	public final void setNumber(java.lang.Long number)
	{
		setNumber(getContext(), number);
	}

	/**
	 * Set value of Number
	 * @param context
	 * @param number
	 */
	public final void setNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long number)
	{
		getMendixObject().setValue(context, MemberNames.Number.toString(), number);
	}

	/**
	 * @return value of Country_Continent
	 */
	public final textboxsearch.proxies.Continent getCountry_Continent() throws com.mendix.core.CoreException
	{
		return getCountry_Continent(getContext());
	}

	/**
	 * @param context
	 * @return value of Country_Continent
	 */
	public final textboxsearch.proxies.Continent getCountry_Continent(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		textboxsearch.proxies.Continent result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Country_Continent.toString());
		if (identifier != null)
			result = textboxsearch.proxies.Continent.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Country_Continent
	 * @param country_continent
	 */
	public final void setCountry_Continent(textboxsearch.proxies.Continent country_continent)
	{
		setCountry_Continent(getContext(), country_continent);
	}

	/**
	 * Set value of Country_Continent
	 * @param context
	 * @param country_continent
	 */
	public final void setCountry_Continent(com.mendix.systemwideinterfaces.core.IContext context, textboxsearch.proxies.Continent country_continent)
	{
		if (country_continent == null)
			getMendixObject().setValue(context, MemberNames.Country_Continent.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Country_Continent.toString(), country_continent.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return countryMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final textboxsearch.proxies.Country that = (textboxsearch.proxies.Country) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "TextboxSearch.Country";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
